
%============================================================================
% Library Facts
%============================================================================

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-11.2.0/binutils-2.25.1-c4vc37k2uyubdocd43lpvrykeycuzqj7/lib/libbfd-2.25.1.so
%----------------------------------------------------------------------------
abi_typelocation("a","libintl_dgettext","Both","Integer8","(%rdi)").
abi_typelocation("a","libintl_dgettext","Both","Integer8","(%rsi)").
abi_typelocation("a","libintl_dgettext","Export","Integer8","(%rax)").
abi_typelocation("a","libintl_dgettext","Import","Integer8","()").
abi_typelocation("a","libintl_dgettext","Import","Integer8","()").
abi_typelocation("a","libintl_dgettext","Export","Integer8","()").
abi_typelocation("a","libintl_dgettext","Export","Integer8","(%rax)").
abi_typelocation("a","inflateEnd","Export","Integer32","%rax").
abi_typelocation("a","inflateReset","Export","Integer32","%rax").
abi_typelocation("a","inflate","Import","Integer32","%rdi").
abi_typelocation("a","inflate","Export","Integer32","%rax").
abi_typelocation("a","inflateInit_","Import","Integer32","%rdi").
abi_typelocation("a","inflateInit_","Export","Integer32","%rax").
abi_typelocation("a","compress","Import","Integer8","(())").
abi_typelocation("a","compress","Import","Integer8","((()+8))").
abi_typelocation("a","compress","Import","Integer32","(()+8)+8").
abi_typelocation("a","compress","Import","Integer32","(()+8)+12").
abi_typelocation("a","compress","Import","Integer32","(()+8)+16").
abi_typelocation("a","compress","Import","Integer32","(()+8)+20").
abi_typelocation("a","compress","Import","Integer32","(()+8)+24").
abi_typelocation("a","compress","Import","Integer8","(()+8)+28").
abi_typelocation("a","compress","Import","Integer8","(()+8)+29").
abi_typelocation("a","compress","Import","Integer8","(()+8)+30").
abi_typelocation("a","compress","Import","Integer8","(()+8)+31").
abi_typelocation("a","compress","Import","Void","((()+8)+32)").
abi_typelocation("a","compress","Import","Void","((()+8)+40)").
abi_typelocation("a","compress","Import","Void","((()+8)+48)").
abi_typelocation("a","compress","Import","Void","((()+8)+56)").
abi_typelocation("a","compress","Import","Void","((()+8)+64)").
abi_typelocation("a","compress","Import","Void","((()+8)+72)").
abi_typelocation("a","compress","Import","Void","((()+8)+80)").
abi_typelocation("a","compress","Import","Void","((()+8)+88)").
abi_typelocation("a","compress","Import","Void","((()+8)+96)").
abi_typelocation("a","compress","Import","Void","((()+8)+104)").
abi_typelocation("a","compress","Import","Void","((()+8)+112)").
abi_typelocation("a","compress","Import","Void","((()+8)+120)").
abi_typelocation("a","compress","Import","Void","((()+8)+128)").
abi_typelocation("a","compress","Import","Void","((()+8)+136)").
abi_typelocation("a","compress","Import","Void","((()+8)+144)").
abi_typelocation("a","compress","Import","Void","((()+8)+152)").
abi_typelocation("a","compress","Import","Void","((()+8)+160)").
abi_typelocation("a","compress","Import","Void","((()+8)+168)").
abi_typelocation("a","compress","Import","Array[32:4]","(()+8)+176").
abi_typelocation("a","compress","Import","Void","((()+8)+176)").
abi_typelocation("a","compress","Import","Array[32:4]","(()+8)+208").
abi_typelocation("a","compress","Import","Void","((()+8)+208)").
abi_typelocation("a","compress","Import","Array","(()+8)+240").
abi_typelocation("a","compress","Import","Void","((()+8)+240)").
abi_typelocation("a","compress","Import","Void","((()+8)+272)").
abi_typelocation("a","compress","Import","Void","((()+8)+280)").
abi_typelocation("a","compress","Import","Void","((()+8)+288)").
abi_typelocation("a","compress","Import","Void","((()+8)+296)").
abi_typelocation("a","compress","Import","Void","((()+8)+304)").
abi_typelocation("a","compress","Import","Void","((()+8)+312)").
abi_typelocation("a","compress","Import","Void","((()+8)+320)").
abi_typelocation("a","compress","Import","Void","((()+8)+328)").
abi_typelocation("a","compress","Import","Void","((()+8)+336)").
abi_typelocation("a","compress","Import","Void","((()+8)+344)").
abi_typelocation("a","compress","Import","Void","((()+8)+352)").
abi_typelocation("a","compress","Import","Void","((()+8)+360)").
abi_typelocation("a","compress","Import","Void","((()+8)+368)").
abi_typelocation("a","compress","Import","Void","((()+8)+376)").
abi_typelocation("a","compress","Import","Void","((()+8)+384)").
abi_typelocation("a","compress","Import","Void","((()+8)+392)").
abi_typelocation("a","compress","Import","Void","((()+8)+400)").
abi_typelocation("a","compress","Import","Void","((()+8)+408)").
abi_typelocation("a","compress","Import","Void","((()+8)+416)").
abi_typelocation("a","compress","Import","Void","((()+8)+424)").
abi_typelocation("a","compress","Import","Void","((()+8)+432)").
abi_typelocation("a","compress","Import","Void","((()+8)+440)").
abi_typelocation("a","compress","Import","Void","((()+8)+448)").
abi_typelocation("a","compress","Import","Void","((()+8)+456)").
abi_typelocation("a","compress","Import","Void","((()+8)+464)").
abi_typelocation("a","compress","Import","Void","((()+8)+472)").
abi_typelocation("a","compress","Import","Void","((()+8)+480)").
abi_typelocation("a","compress","Import","Void","((()+8)+488)").
abi_typelocation("a","compress","Import","Void","((()+8)+496)").
abi_typelocation("a","compress","Import","Void","((()+8)+504)").
abi_typelocation("a","compress","Import","Void","((()+8)+512)").
abi_typelocation("a","compress","Import","Void","((()+8)+520)").
abi_typelocation("a","compress","Import","Void","((()+8)+528)").
abi_typelocation("a","compress","Import","Void","((()+8)+536)").
abi_typelocation("a","compress","Import","Void","((()+8)+544)").
abi_typelocation("a","compress","Import","Void","((()+8)+552)").
abi_typelocation("a","compress","Import","Void","((()+8)+560)").
abi_typelocation("a","compress","Import","Void","((()+8)+568)").
abi_typelocation("a","compress","Import","Void","((()+8)+576)").
abi_typelocation("a","compress","Import","Void","((()+8)+584)").
abi_typelocation("a","compress","Import","Void","((()+8)+592)").
abi_typelocation("a","compress","Import","Void","((()+8)+600)").
abi_typelocation("a","compress","Import","Void","((()+8)+608)").
abi_typelocation("a","compress","Import","Void","((()+8)+616)").
abi_typelocation("a","compress","Import","Void","((()+8)+624)").
abi_typelocation("a","compress","Import","Void","((()+8)+632)").
abi_typelocation("a","compress","Import","Void","((()+8)+640)").
abi_typelocation("a","compress","Import","Void","((()+8)+648)").
abi_typelocation("a","compress","Import","Void","((()+8)+656)").
abi_typelocation("a","compress","Import","Void","((()+8)+664)").
abi_typelocation("a","compress","Import","Void","((()+8)+672)").
abi_typelocation("a","compress","Import","Void","((()+8)+680)").
abi_typelocation("a","compress","Import","Void","((()+8)+688)").
abi_typelocation("a","compress","Import","Void","((()+8)+696)").
abi_typelocation("a","compress","Import","Void","((()+8)+704)").
abi_typelocation("a","compress","Import","Void","((()+8)+712)").
abi_typelocation("a","compress","Import","Void","((()+8)+720)").
abi_typelocation("a","compress","Import","Void","((()+8)+728)").
abi_typelocation("a","compress","Import","Void","((()+8)+736)").
abi_typelocation("a","compress","Import","Void","((()+8)+744)").
abi_typelocation("a","compress","Import","Void","((()+8)+752)").
abi_typelocation("a","compress","Import","Void","((()+8)+760)").
abi_typelocation("a","compress","Import","Void","((()+8)+768)").
abi_typelocation("a","compress","Import","Void","((()+8)+776)").
abi_typelocation("a","compress","Import","Void","((()+8)+784)").
abi_typelocation("a","compress","Import","Void","((()+8)+792)").
abi_typelocation("a","compress","Import","Void","((()+8)+800)").
abi_typelocation("a","compress","Import","Void","((()+8)+808)").
abi_typelocation("a","compress","Import","Void","((()+8)+816)").
abi_typelocation("a","compress","Import","Opaque","((()+8)+824)").
abi_typelocation("a","compress","Import","Void","(()+16)").
abi_typelocation("a","compress","Import","Void","((()+24))").
abi_typelocation("a","compress","Import","Void","((()+24)+8)").
abi_typelocation("a","compress","Import","Void","((()+24)+16)").
abi_typelocation("a","compress","Import","Void","((()+24)+24)").
abi_typelocation("a","compress","Import","Void","((()+24)+32)").
abi_typelocation("a","compress","Import","Void","((()+24)+40)").
abi_typelocation("a","compress","Import","Void","((()+24)+48)").
abi_typelocation("a","compress","Import","Void","((()+24)+56)").
abi_typelocation("a","compress","Import","Opaque","(()+32)").
abi_typelocation("a","compress","Import","Opaque","(()+40)").
abi_typelocation("a","compress","Import","Integer64","()+48").
abi_typelocation("a","compress","Import","Integer64","()+56").
abi_typelocation("a","compress","Import","Integer32","()+64").
abi_typelocation("a","compress","Import","Integer32","()").
abi_typelocation("a","compress","Import","Integer32","()").
abi_typelocation("a","compress","Import","Integer32","()").
abi_typelocation("a","compress","Import","Integer32","()").
abi_typelocation("a","compress","Import","Integer32","()").
abi_typelocation("a","compress","Import","Integer32","()").
abi_typelocation("a","compress","Import","Integer32","()").
abi_typelocation("a","compress","Import","Integer32","()").
abi_typelocation("a","compress","Import","Integer32","()").
abi_typelocation("a","compress","Import","Integer32","()").
abi_typelocation("a","compress","Import","Integer32","()").
abi_typelocation("a","compress","Import","Integer32","()").
abi_typelocation("a","compress","Import","Integer32","()").
abi_typelocation("a","compress","Import","Integer64","()+72").
abi_typelocation("a","compress","Import","Integer64","()+80").
abi_typelocation("a","compress","Import","Opaque","(((()+88)))").
abi_typelocation("a","compress","Import","Integer8","(((()+88))+8)").
abi_typelocation("a","compress","Import","Integer64","((()+88))+16").
abi_typelocation("a","compress","Import","Void","(()+96)").
abi_typelocation("a","compress","Import","Void","(()+104)").
abi_typelocation("a","compress","Import","Integer32","()+112").
abi_typelocation("a","compress","Import","Integer32","()+116").
abi_typelocation("a","compress","Import","Integer32","()+120").
abi_typelocation("a","compress","Import","Integer32","()+88").
abi_typelocation("a","compress","Import","Opaque","(()+128)").
abi_typelocation("a","compress","Import","Opaque","(()+136)").
abi_typelocation("a","compress","Import","Integer32","()+144").
abi_typelocation("a","compress","Import","Integer32","()+148").
abi_typelocation("a","compress","Import","Integer64","()+152").
abi_typelocation("a","compress","Import","Opaque","(()+160)").
abi_typelocation("a","compress","Import","Integer32","()+168").
abi_typelocation("a","compress","Import","Integer32","()+172").
abi_typelocation("a","compress","Import","Integer32","(()+176)").
abi_typelocation("a","compress","Import","Integer32","(()+176)+4").
abi_typelocation("a","compress","Import","Integer32","(()+176)+8").
abi_typelocation("a","compress","Import","Integer32","(()+176)+12").
abi_typelocation("a","compress","Import","Integer64","(()+176)+16").
abi_typelocation("a","compress","Import","Integer8","((()+176)+24)").
abi_typelocation("a","compress","Import","Integer8","((()+176)+32)").
abi_typelocation("a","compress","Import","Integer32","(()+176)+40").
abi_typelocation("a","compress","Import","Integer32","(()+176)+44").
abi_typelocation("a","compress","Import","Void","((()+176)+48)").
abi_typelocation("a","compress","Import","Void","((()+176)+56)").
abi_typelocation("a","compress","Import","Void","((()+176)+64)").
abi_typelocation("a","compress","Import","Opaque","((()+176)+72)").
abi_typelocation("a","compress","Import","Void","(()+184)").
abi_typelocation("a","compress","Import","Opaque","(()+192)").
abi_typelocation("a","compress","Import","Opaque","(()+200)").
abi_typelocation("a","compress","Import","Opaque","(()+208)").
abi_typelocation("a","compress","Import","Opaque","(()+216)").
abi_typelocation("a","compress","Import","Opaque","(()+224)").
abi_typelocation("a","compress","Import","Union","()+232").
abi_typelocation("a","compress","Import","Void","(()+240)").
abi_typelocation("a","compress","Import","Void","(()+248)").
abi_typelocation("a","compress","Export","Integer32","%rax").
abi_typelocation("a","libintl_dgettext","Export","Integer8","(%rax)").
abi_typelocation("a","libintl_dgettext","Both","Integer8","(%rdi)").
abi_typelocation("a","libintl_dgettext","Both","Integer8","(%rsi)").
abi_typelocation("a","libintl_dgettext","Export","Integer8","(%rax)").
abi_typelocation("a","libintl_dgettext","Both","Integer8","(%rdi)").
abi_typelocation("a","libintl_dgettext","Both","Integer8","(%rsi)").
abi_typelocation("a","libintl_dgettext","Export","Integer8","(%rax)").
abi_typelocation("a","libintl_dgettext","Both","Void","((%rdi))").
abi_typelocation("a","libintl_dgettext","Both","Void","((%rsi))").
abi_typelocation("a","libintl_dgettext","Both","Void","((%rdi))").
abi_typelocation("a","libintl_dgettext","Both","Void","((%rsi))").
abi_typelocation("a","libintl_dgettext","Export","Integer8","%rax").
abi_typelocation("a","libintl_dgettext","Both","Void","((%rdi))").
abi_typelocation("a","libintl_dgettext","Both","Void","((%rsi))").
abi_typelocation("a","libintl_dgettext","Export","Integer8","%rax").
abi_typelocation("a","libintl_dgettext","Import","Void","(%rdi)").
abi_typelocation("a","libintl_dgettext","Import","Void","(%rsi)").
abi_typelocation("a","libintl_dgettext","Import","Void","()").
abi_typelocation("a","libintl_dgettext","Import","Void","()").
abi_typelocation("a","libintl_dgettext","Import","Integer8","%rdi").
abi_typelocation("a","libintl_dgettext","Import","Integer8","%rsi").
abi_typelocation("a","libintl_dgettext","Import","Array","%rax").
abi_typelocation("a","libintl_dgettext","Import","Integer8","%rax").
abi_typelocation("a","libintl_dgettext","Export","Integer8","()").

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-11.2.0/gettext-0.21-si6zn7yjchsib2pzgh4kilmur4jly4n3/lib/libintl.so.8.2.0
%----------------------------------------------------------------------------
abi_typelocation("b","libintl_dgettext","Export","Integer16","%rax").

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-11.2.0/zlib-1.2.12-luwgiwun44dt7hmxv4ki6xjnxyucze7f/lib/libz.so.1.2.12
%----------------------------------------------------------------------------
abi_typelocation("b","compressBound","Import","Integer8","%rdi").
abi_typelocation("b","compressBound","Export","Integer8","%rax").
abi_typelocation("b","compress","Import","Integer8","%rdi").
abi_typelocation("b","compress","Export","Integer64","%rax").
abi_typelocation("b","inflateEnd","Export","Integer64","%rax").
abi_typelocation("b","inflate","Import","Integer64","%rdi").
abi_typelocation("b","inflate","Export","Integer64","%rax").
abi_typelocation("b","inflateInit_","Import","Integer64","%rdi").
abi_typelocation("b","inflateInit_","Export","Integer64","%rax").
abi_typelocation("b","inflateEnd","Export","Integer8","%rax").
abi_typelocation("b","inflate","Import","Integer8","%rdi").
abi_typelocation("b","inflate","Export","Integer8","%rax").
abi_typelocation("b","inflateReset","Export","Integer8","%rax").
