
%============================================================================
% Library Facts
%============================================================================

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-haswell/gcc-11.2.0/binutils-2.32-gmgmelo3dp2yrdcjddntwqab4kanyd2n/lib/libbfd-2.32.so
%----------------------------------------------------------------------------
abi_typelocation("a","libintl_dgettext","Both","Integer8","(%rdi)").
abi_typelocation("a","libintl_dgettext","Both","Integer8","(%rsi)").
abi_typelocation("a","libintl_dgettext","Export","Integer8","(%rax)").
abi_typelocation("a","libintl_dgettext","Import","Void","(%rdi)").
abi_typelocation("a","libintl_dgettext","Import","Void","(%rsi)").
abi_typelocation("a","compress","Export","Integer32","%rax").
abi_typelocation("a","inflateEnd","Export","Integer32","%rax").
abi_typelocation("a","inflateReset","Export","Integer32","%rax").
abi_typelocation("a","inflate","Import","Integer32","%rdi").
abi_typelocation("a","inflate","Export","Integer32","%rax").
abi_typelocation("a","inflateInit_","Import","Integer32","%rdi").
abi_typelocation("a","inflateInit_","Export","Integer32","%rax").
abi_typelocation("a","libintl_dgettext","Export","Integer8","(%rax)").
abi_typelocation("a","libintl_dgettext","Import","Integer64","framebase+8").
abi_typelocation("a","libintl_dgettext","Import","Integer64","framebase+16").
abi_typelocation("a","libintl_dgettext","Import","Integer64","framebase+24").
abi_typelocation("a","libintl_dgettext","Import","Integer32","framebase+32").
abi_typelocation("a","libintl_dgettext","Import","Integer32","framebase+36").
abi_typelocation("a","libintl_dgettext","Import","Integer32","framebase+40").
abi_typelocation("a","libintl_dgettext","Import","Integer32","framebase+44").
abi_typelocation("a","libintl_dgettext","Import","Integer64","framebase+48").
abi_typelocation("a","libintl_dgettext","Import","Integer64","framebase+56").
abi_typelocation("a","libintl_dgettext","Import","Integer64","framebase+64").
abi_typelocation("a","libintl_dgettext","Import","Integer64","framebase+72").
abi_typelocation("a","libintl_dgettext","Import","Integer64","framebase+80").
abi_typelocation("a","libintl_dgettext","Import","Integer64","framebase+88").
abi_typelocation("a","libintl_dgettext","Import","Integer64","framebase+96").
abi_typelocation("a","libintl_dgettext","Import","Integer64","framebase+104").
abi_typelocation("a","libintl_dgettext","Import","Integer64","framebase+112").
abi_typelocation("a","libintl_dgettext","Import","Integer64","framebase+120").
abi_typelocation("a","libintl_dgettext","Import","Array[24:3]","framebase+128").
abi_typelocation("a","libintl_dgettext","Import","Integer64","framebase+128").
abi_typelocation("a","libintl_dgettext","Import","Integer64","framebase+152").
abi_typelocation("a","libintl_dgettext","Import","Integer64","framebase+160").
abi_typelocation("a","libintl_dgettext","Import","Integer64","framebase+168").
abi_typelocation("a","libintl_dgettext","Import","Integer32","framebase+176").
abi_typelocation("a","libintl_dgettext","Import","Integer32","framebase+180").
abi_typelocation("a","libintl_dgettext","Import","Integer32","framebase+184").
abi_typelocation("a","libintl_dgettext","Import","Integer32","framebase+188").
abi_typelocation("a","libintl_dgettext","Import","Integer64","framebase+192").
abi_typelocation("a","libintl_dgettext","Import","Integer64","framebase+200").
abi_typelocation("a","libintl_dgettext","Import","Integer64","framebase+208").
abi_typelocation("a","libintl_dgettext","Import","Integer64","framebase+216").
abi_typelocation("a","libintl_dgettext","Import","Integer64","framebase+224").
abi_typelocation("a","libintl_dgettext","Import","Integer64","framebase+232").
abi_typelocation("a","libintl_dgettext","Import","Integer64","framebase+240").
abi_typelocation("a","libintl_dgettext","Import","Integer64","framebase+248").
abi_typelocation("a","libintl_dgettext","Import","Integer64","framebase+256").
abi_typelocation("a","libintl_dgettext","Import","Integer64","framebase+264").
abi_typelocation("a","libintl_dgettext","Import","Array[24:3]","framebase+272").
abi_typelocation("a","libintl_dgettext","Import","Integer64","framebase+272").
abi_typelocation("a","libintl_dgettext","Import","Void","()").
abi_typelocation("a","libintl_dgettext","Import","Void","()").
abi_typelocation("a","libintl_dgettext","Export","Integer8","()").
abi_typelocation("a","libintl_dgettext","Import","Void","()").
abi_typelocation("a","libintl_dgettext","Import","Void","()").
abi_typelocation("a","libintl_dgettext","Import","Array","%rax").
abi_typelocation("a","libintl_dgettext","Import","Integer8","%rax").
abi_typelocation("a","libintl_dgettext","Import","Void","()").
abi_typelocation("a","libintl_dgettext","Import","Void","()").
abi_typelocation("a","libintl_dgettext","Import","Array","%rax").
abi_typelocation("a","libintl_dgettext","Import","Integer8","%rax").
abi_typelocation("a","libintl_dgettext","Import","Void","()").
abi_typelocation("a","libintl_dgettext","Import","Void","()").
abi_typelocation("a","libintl_dgettext","Import","Array","%rax").
abi_typelocation("a","libintl_dgettext","Import","Integer8","%rax").
abi_typelocation("a","libintl_dgettext","Export","Integer8","(%rax)").
abi_typelocation("a","libintl_dgettext","Import","Void","()").
abi_typelocation("a","libintl_dgettext","Import","Void","()").
abi_typelocation("a","libintl_dgettext","Import","Void","()").
abi_typelocation("a","libintl_dgettext","Import","Void","()").
abi_typelocation("a","libintl_dgettext","Import","Void","()").
abi_typelocation("a","libintl_dgettext","Import","Void","()").
abi_typelocation("a","libintl_dgettext","Import","Void","(())").
abi_typelocation("a","libintl_dgettext","Import","Void","(())").
abi_typelocation("a","libintl_dgettext","Import","Void","(())").
abi_typelocation("a","libintl_dgettext","Import","Void","(())").
abi_typelocation("a","libintl_dgettext","Import","Array","%rdi").
abi_typelocation("a","libintl_dgettext","Import","Integer8","%rdi").
abi_typelocation("a","libintl_dgettext","Import","Array","%rsi").
abi_typelocation("a","libintl_dgettext","Import","Integer8","%rsi").
abi_typelocation("a","libintl_dgettext","Export","Integer8","()").
abi_typelocation("a","libintl_dgettext","Import","Void","(())").
abi_typelocation("a","libintl_dgettext","Import","Void","(())").
abi_typelocation("a","libintl_dgettext","Import","Void","(())").
abi_typelocation("a","libintl_dgettext","Import","Void","(())").
abi_typelocation("a","libintl_dgettext","Import","Array","%rax").
abi_typelocation("a","libintl_dgettext","Import","Integer8","%rax").
abi_typelocation("a","libintl_dgettext","Export","Integer8","()").

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-haswell/gcc-11.2.0/gettext-0.21-vhvhgl5dzacdhd2alw2p6wvtgwmgvhgl/lib/libintl.so.8.2.0
%----------------------------------------------------------------------------
abi_typelocation("b","libintl_dgettext","Export","Integer16","%rax").

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-haswell/gcc-11.2.0/zlib-1.2.12-ychk3ix6mv3mgsrtnazfunnmu4vrspkk/lib/libz.so.1.2.12
%----------------------------------------------------------------------------
abi_typelocation("b","compressBound","Import","Integer8","%rdi").
abi_typelocation("b","compressBound","Export","Integer8","%rax").
abi_typelocation("b","compress","Import","Integer8","%rdi").
abi_typelocation("b","compress","Export","Integer64","%rax").
abi_typelocation("b","inflateEnd","Export","Integer64","%rax").
abi_typelocation("b","inflate","Import","Integer64","%rdi").
abi_typelocation("b","inflate","Export","Integer64","%rax").
abi_typelocation("b","inflateInit_","Import","Integer64","%rdi").
abi_typelocation("b","inflateInit_","Export","Integer64","%rax").
abi_typelocation("b","inflateEnd","Export","Integer8","%rax").
abi_typelocation("b","inflate","Import","Integer8","%rdi").
abi_typelocation("b","inflate","Export","Integer8","%rax").
abi_typelocation("b","inflateReset","Export","Integer8","%rax").
