
%============================================================================
% Library Facts
%============================================================================

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-broadwell/gcc-11.2.0/hdf5-1.10.2-wrbmguqucv7jmc7p5noonvliwg57xad7/lib/libhdf5_tools.so.101
%----------------------------------------------------------------------------
abi_typelocation("a","ompi_mpi_comm_world","Import","Empty","none").
abi_typelocation("a","ompi_mpi_char","Import","Empty","none").
abi_typelocation("a","ompi_mpi_byte","Import","Empty","none").
abi_typelocation("a","H5Gclose","Import","Integer64","%rdi").
abi_typelocation("a","H5Gclose","Export","Integer32","%rax").
abi_typelocation("a","H5Gopen2","Import","Integer64","%rdi").
abi_typelocation("a","H5Gopen2","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Gopen2","Import","Integer64","%rdx").
abi_typelocation("a","H5Gopen2","Export","Integer64","%rax").
abi_typelocation("a","H5Tclose","Import","Integer64","%rdi").
abi_typelocation("a","H5Tclose","Export","Integer32","%rax").
abi_typelocation("a","H5Tequal","Import","Integer64","%rdi").
abi_typelocation("a","H5Tequal","Import","Integer64","%rsi").
abi_typelocation("a","H5Tequal","Export","Integer32","%rax").
abi_typelocation("a","H5Topen2","Import","Integer64","%rdi").
abi_typelocation("a","H5Topen2","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Topen2","Import","Integer64","%rdx").
abi_typelocation("a","H5Topen2","Export","Integer64","%rax").
abi_typelocation("a","H5Dclose","Import","Integer64","%rdi").
abi_typelocation("a","H5Dclose","Export","Integer32","%rax").
abi_typelocation("a","H5Dopen2","Import","Integer64","%rdi").
abi_typelocation("a","H5Dopen2","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Dopen2","Import","Integer64","%rdx").
abi_typelocation("a","H5Dopen2","Export","Integer64","%rax").
abi_typelocation("a","MPI_Finalize","Export","Integer32","%rax").
abi_typelocation("a","MPI_Probe","Import","Integer32","%rdi").
abi_typelocation("a","MPI_Probe","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Probe","Import","Empty","(%rdx)").
abi_typelocation("a","MPI_Probe","Import","Integer32","(%rcx)").
abi_typelocation("a","MPI_Probe","Import","Integer32","(%rcx)+4").
abi_typelocation("a","MPI_Probe","Import","Integer32","(%rcx)+8").
abi_typelocation("a","MPI_Probe","Import","Integer32","(%rcx)+12").
abi_typelocation("a","MPI_Probe","Import","Integer64","(%rcx)+16").
abi_typelocation("a","MPI_Probe","Export","Integer32","%rax").
abi_typelocation("a","MPI_Recv","Both","Void","(%rdi)").
abi_typelocation("a","MPI_Recv","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Recv","Import","Empty","(%rdx)").
abi_typelocation("a","MPI_Recv","Import","Integer32","%rcx").
abi_typelocation("a","MPI_Recv","Import","Integer32","%r8").
abi_typelocation("a","MPI_Recv","Import","Empty","(%r9)").
abi_typelocation("a","MPI_Recv","Import","Integer32","(framebase+8)").
abi_typelocation("a","MPI_Recv","Import","Integer32","(framebase+8)+4").
abi_typelocation("a","MPI_Recv","Import","Integer32","(framebase+8)+8").
abi_typelocation("a","MPI_Recv","Import","Integer32","(framebase+8)+12").
abi_typelocation("a","MPI_Recv","Import","Integer64","(framebase+8)+16").
abi_typelocation("a","MPI_Recv","Export","Integer32","%rax").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","%rdi").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Iprobe","Import","Empty","(%rdx)").
abi_typelocation("a","MPI_Iprobe","Both","Integer32","(%rcx)").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","(%r8)").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","(%r8)+4").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","(%r8)+8").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","(%r8)+12").
abi_typelocation("a","MPI_Iprobe","Import","Integer64","(%r8)+16").
abi_typelocation("a","MPI_Iprobe","Export","Integer32","%rax").
abi_typelocation("a","H5Lunpack_elink_val","Import","Integer64","%rsi").
abi_typelocation("a","H5Lunpack_elink_val","Both","Integer32","(%rdx)").
abi_typelocation("a","H5Lunpack_elink_val","Both","Integer8","((%rcx))").
abi_typelocation("a","H5Lunpack_elink_val","Both","Integer8","((%r8))").
abi_typelocation("a","H5Lunpack_elink_val","Export","Integer32","%rax").
abi_typelocation("a","H5Fclose","Import","Integer64","%rdi").
abi_typelocation("a","H5Fclose","Export","Integer32","%rax").
abi_typelocation("a","H5Eset_auto1","Import","Void","(%rdi)").
abi_typelocation("a","H5Eset_auto1","Both","Void","(%rsi)").
abi_typelocation("a","H5Eset_auto1","Export","Integer32","%rax").
abi_typelocation("a","H5Eget_auto1","Both","Void","((%rdi))").
abi_typelocation("a","H5Eget_auto1","Both","Void","((%rsi))").
abi_typelocation("a","H5Eget_auto1","Export","Integer32","%rax").
abi_typelocation("a","H5Eset_auto2","Import","Integer64","%rdi").
abi_typelocation("a","H5Eset_auto2","Import","Void","(%rsi)").
abi_typelocation("a","H5Eset_auto2","Both","Void","(%rdx)").
abi_typelocation("a","H5Eset_auto2","Export","Integer32","%rax").
abi_typelocation("a","H5Eget_auto2","Import","Integer64","%rdi").
abi_typelocation("a","H5Eget_auto2","Both","Void","((%rsi))").
abi_typelocation("a","H5Eget_auto2","Both","Void","((%rdx))").
abi_typelocation("a","H5Eget_auto2","Export","Integer32","%rax").
abi_typelocation("a","H5Eauto_is_v2","Import","Integer64","%rdi").
abi_typelocation("a","H5Eauto_is_v2","Both","Integer32","(%rsi)").
abi_typelocation("a","H5Eauto_is_v2","Export","Integer32","%rax").
abi_typelocation("a","MPI_Abort","Import","Empty","(%rdi)").
abi_typelocation("a","MPI_Abort","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Abort","Export","Integer32","%rax").
abi_typelocation("a","HDfprintf","Import","Integer32","(%rdi)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+8)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+16)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+24)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+32)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+40)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+48)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+56)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+64)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+72)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+80)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+88)").
abi_typelocation("a","HDfprintf","Import","Empty","((%rdi)+96)").
abi_typelocation("a","HDfprintf","Import","Integer32","((%rdi)+104)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+8)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+16)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+24)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+32)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+40)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+48)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+56)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+64)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+72)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+80)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+88)").
abi_typelocation("a","HDfprintf","Import","Empty","(((%rdi)+104)+96)").
abi_typelocation("a","HDfprintf","Import","Opaque","(((%rdi)+104)+104)").
abi_typelocation("a","HDfprintf","Import","Integer32","((%rdi)+104)+112").
abi_typelocation("a","HDfprintf","Import","Integer32","((%rdi)+104)+116").
abi_typelocation("a","HDfprintf","Import","Integer64","((%rdi)+104)+120").
abi_typelocation("a","HDfprintf","Import","Integer16","((%rdi)+104)+128").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+104)+130").
abi_typelocation("a","HDfprintf","Import","Array[1:1]","((%rdi)+104)+131").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+104)+131").
abi_typelocation("a","HDfprintf","Import","Integer64","((%rdi)+104)+144").
abi_typelocation("a","HDfprintf","Import","Empty","(((%rdi)+104)+152)").
abi_typelocation("a","HDfprintf","Import","Empty","(((%rdi)+104)+160)").
abi_typelocation("a","HDfprintf","Import","Opaque","(((%rdi)+104)+168)").
abi_typelocation("a","HDfprintf","Import","Void","(((%rdi)+104)+176)").
abi_typelocation("a","HDfprintf","Import","Integer64","((%rdi)+104)+184").
abi_typelocation("a","HDfprintf","Import","Integer32","((%rdi)+104)+192").
abi_typelocation("a","HDfprintf","Import","Array[20:20]","((%rdi)+104)+196").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+104)+196").
abi_typelocation("a","HDfprintf","Import","Integer32","(%rdi)+112").
abi_typelocation("a","HDfprintf","Import","Integer32","(%rdi)+116").
abi_typelocation("a","HDfprintf","Import","Integer64","(%rdi)+120").
abi_typelocation("a","HDfprintf","Import","Integer16","(%rdi)+128").
abi_typelocation("a","HDfprintf","Import","Integer8","(%rdi)+130").
abi_typelocation("a","HDfprintf","Import","Array[1:1]","(%rdi)+131").
abi_typelocation("a","HDfprintf","Import","Integer8","(%rdi)+131").
abi_typelocation("a","HDfprintf","Import","Integer64","(%rdi)+144").
abi_typelocation("a","HDfprintf","Import","Empty","((%rdi)+152)").
abi_typelocation("a","HDfprintf","Import","Empty","((%rdi)+160)").
abi_typelocation("a","HDfprintf","Import","Opaque","((%rdi)+168)").
abi_typelocation("a","HDfprintf","Import","Void","((%rdi)+176)").
abi_typelocation("a","HDfprintf","Import","Integer64","(%rdi)+184").
abi_typelocation("a","HDfprintf","Import","Integer32","(%rdi)+192").
abi_typelocation("a","HDfprintf","Import","Array[20:20]","(%rdi)+196").
abi_typelocation("a","HDfprintf","Import","Integer8","(%rdi)+196").
abi_typelocation("a","HDfprintf","Both","Integer8","(%rsi)").
abi_typelocation("a","HDfprintf","Export","Integer32","%rax").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","%rdi").
abi_typelocation("a","H5Oget_info_by_name","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+8").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer32","(%rdx)+16").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer32","(%rdx)+20").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+24").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+32").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+40").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+48").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+56").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer32","(%rdx)+64").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer32","(%rdx)+68").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer32","(%rdx)+72").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer32","(%rdx)+76").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+80").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+88").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+96").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+104").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+112").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+120").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+128").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+136").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+144").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+152").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","%rcx").
abi_typelocation("a","H5Oget_info_by_name","Export","Integer32","%rax").
abi_typelocation("a","H5Lget_info","Import","Integer64","%rdi").
abi_typelocation("a","H5Lget_info","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Lget_info","Import","Integer32","(%rdx)").
abi_typelocation("a","H5Lget_info","Import","Integer8","(%rdx)+4").
abi_typelocation("a","H5Lget_info","Import","Integer64","(%rdx)+8").
abi_typelocation("a","H5Lget_info","Import","Integer32","(%rdx)+16").
abi_typelocation("a","H5Lget_info","Import","Union","(%rdx)+24").
abi_typelocation("a","H5Lget_info","Import","Integer64","%rcx").
abi_typelocation("a","H5Lget_info","Export","Integer32","%rax").
abi_typelocation("a","H5Lexists","Import","Integer64","%rdi").
abi_typelocation("a","H5Lexists","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Lexists","Import","Integer64","%rdx").
abi_typelocation("a","H5Lexists","Export","Integer32","%rax").
abi_typelocation("a","H5Epush2","Import","Integer64","%rdi").
abi_typelocation("a","H5Epush2","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Epush2","Both","Integer8","(%rdx)").
abi_typelocation("a","H5Epush2","Import","Integer32","%rcx").
abi_typelocation("a","H5Epush2","Import","Integer64","%r8").
abi_typelocation("a","H5Epush2","Import","Integer64","%r9").
abi_typelocation("a","H5Epush2","Import","Integer64","framebase+8").
abi_typelocation("a","H5Epush2","Both","Integer8","(framebase+16)").
abi_typelocation("a","H5Epush2","Export","Integer32","%rax").
abi_typelocation("a","MPI_Send","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Send","Import","Empty","(%rdx)").
abi_typelocation("a","MPI_Send","Import","Integer32","%rcx").
abi_typelocation("a","MPI_Send","Import","Integer32","%r8").
abi_typelocation("a","MPI_Send","Import","Empty","(%r9)").
abi_typelocation("a","MPI_Send","Export","Integer32","%rax").
abi_typelocation("a","H5Sget_simple_extent_ndims","Export","Integer16","%rax").
abi_typelocation("a","H5Tget_array_dims2","Export","Integer16","%rax").
abi_typelocation("a","H5Tget_array_ndims","Export","Integer16","%rax").
abi_typelocation("a","H5Tenum_nameof","Import","Integer64","%rdi").
abi_typelocation("a","H5Tget_member_offset","Import","Integer64","%rdi").
abi_typelocation("a","H5Tget_member_offset","Export","Integer64","%rax").
abi_typelocation("a","H5Tget_member_type","Import","Integer64","%rdi").
abi_typelocation("a","H5Tget_nmembers","Export","Integer16","%rax").
abi_typelocation("a","H5Eset_auto1","Import","Integer8","()").
abi_typelocation("a","H5Eset_auto2","Import","Integer8","()").
abi_typelocation("a","H5Tconvert","Import","Integer64","%rdi").
abi_typelocation("a","H5Tconvert","Import","Integer8","()").
abi_typelocation("a","H5Tconvert","Import","Integer8","()").
abi_typelocation("a","H5Epush2","Import","Integer32","%rdi").
abi_typelocation("a","H5Epush2","Import","Integer32","%rsi").
abi_typelocation("a","H5Epush2","Import","Integer64","%rdx").
abi_typelocation("a","H5Epush2","Import","Integer32","%rcx").
abi_typelocation("a","H5Tget_size","Export","Integer64","%rax").
abi_typelocation("a","H5Aget_name","Import","Integer64","%rdi").
abi_typelocation("a","H5Aget_name","Export","Integer8","%rax").
abi_typelocation("a","H5Oget_info","Import","Empty","(%rax)").
abi_typelocation("a","H5Eset_auto1","Import","Integer64","%rdi").
abi_typelocation("a","H5Eset_auto1","Import","Empty","(%rax)").
abi_typelocation("a","H5Eget_auto1","Import","Empty","(%rax)").
abi_typelocation("a","H5Eset_auto2","Import","Empty","(%rdi)").
abi_typelocation("a","H5Eset_auto2","Import","Integer64","%rsi").
abi_typelocation("a","H5Eset_auto2","Import","Empty","(%rax)").
abi_typelocation("a","H5Eget_auto2","Import","Empty","(%rax)").
abi_typelocation("a","H5Eauto_is_v2","Import","Empty","(%rax)").
abi_typelocation("a","H5Dvlen_reclaim","Import","Integer64","%rdi").
abi_typelocation("a","H5Dvlen_reclaim","Import","Empty","(%rax)").
abi_typelocation("a","H5Aread","Import","Integer64","%rdi").
abi_typelocation("a","H5Aread","Import","Empty","(%rax)").
abi_typelocation("a","H5Aclose","Import","Empty","(%rax)").
abi_typelocation("a","H5Sclose","Import","Empty","(%rax)").
abi_typelocation("a","H5Tclose","Import","Empty","(%rax)").
abi_typelocation("a","H5Sget_simple_extent_dims","Export","Integer32","%rax").
abi_typelocation("a","H5Tget_size","Export","Integer64","%rax").
abi_typelocation("a","H5Epush2","Import","Integer32","%rdi").
abi_typelocation("a","H5Epush2","Import","Empty","(%rax)").
abi_typelocation("a","H5Tget_member_type","Import","Integer64","%rdi").
abi_typelocation("a","H5Tget_nmembers","Export","Integer32","%rax").
abi_typelocation("a","H5Screate_simple","Import","Integer32","%rdi").
abi_typelocation("a","H5Dvlen_reclaim","Import","Integer64","%rdi").
abi_typelocation("a","H5Dread","Import","Integer64","%rdi").
abi_typelocation("a","H5Sget_simple_extent_dims","Export","Integer32","%rax").
abi_typelocation("a","H5Sget_simple_extent_ndims","Export","Integer32","%rax").
abi_typelocation("a","H5Eset_auto1","Import","Integer64","%rdi").
abi_typelocation("a","H5Eset_auto2","Import","Integer64","%rdi").
abi_typelocation("a","H5Epush2","Import","Integer64","%rdi").
abi_typelocation("a","H5Epush2","Import","Integer32","%rdi").
abi_typelocation("a","HDfprintf","Export","Integer32","%rax").
abi_typelocation("a","H5Aread","Both","Void","(%rdi)").
abi_typelocation("a","H5Oget_comment","Export","Integer64","%rax").
abi_typelocation("a","H5Pget_virtual_dsetname","Export","Integer64","%rax").
abi_typelocation("a","H5Pget_virtual_filename","Export","Integer64","%rax").
abi_typelocation("a","H5Pget_external","Import","Integer64","%rdi").
abi_typelocation("a","H5Pget_external_count","Export","Integer32","%rax").
abi_typelocation("a","H5Pget_filter2","Import","Integer64","%rdi").
abi_typelocation("a","H5Pget_chunk","Import","Integer32","%rdi").
abi_typelocation("a","H5Pget_chunk","Export","Integer32","%rax").
abi_typelocation("a","H5Pget_nfilters","Export","Integer32","%rax").
abi_typelocation("a","H5Pget_fill_value","Both","Void","(%rdi)").
abi_typelocation("a","H5Tconvert","Both","Void","(%rdi)").
abi_typelocation("a","H5Tconvert","Both","Void","(%rsi)").
abi_typelocation("a","H5Tget_member_value","Import","Integer64","%rdi").
abi_typelocation("a","H5Tget_member_value","Both","Void","(%rsi)").
abi_typelocation("a","H5Tget_array_dims2","Export","Integer32","%rax").
abi_typelocation("a","H5Tget_array_ndims","Export","Integer32","%rax").
abi_typelocation("a","H5Tget_member_type","Import","Integer64","%rdi").
abi_typelocation("a","H5Tget_member_name","Import","Integer64","%rdi").
abi_typelocation("a","H5Tget_nmembers","Export","Integer32","%rax").
abi_typelocation("a","H5free_memory","Both","Void","(%rdi)").
abi_typelocation("a","H5Dvlen_reclaim","Both","Void","(%rdi)").
abi_typelocation("a","H5Sget_simple_extent_dims","Export","Integer32","%rax").
abi_typelocation("a","H5Dread","Both","Void","(%rdi)").
abi_typelocation("a","H5Screate_simple","Import","Integer32","%rdi").
abi_typelocation("a","H5Sget_simple_extent_ndims","Export","Integer32","%rax").
abi_typelocation("a","H5Epush2","Import","Integer64","%rdi").
abi_typelocation("a","H5Rget_name","Export","Integer64","%rax").
abi_typelocation("a","HDfprintf","Export","Integer32","%rax").
abi_typelocation("a","H5Pget_filter2","Import","Integer32","%rdi").
abi_typelocation("a","H5Pget_filter2","Import","Integer8","()").
abi_typelocation("a","H5Pget_filter2","Import","Integer8","()").
abi_typelocation("a","H5Pget_filter2","Import","Integer8","()").
abi_typelocation("a","H5Epush2","Import","Integer32","%rdi").
abi_typelocation("a","H5Pget_nfilters","Export","Integer32","%rax").
abi_typelocation("a","H5SL_search","Export","Integer64","%rax").
abi_typelocation("a","H5SL_insert","Import","Integer64","%rdi").
abi_typelocation("a","H5SL_destroy","Import","Integer64","%rdi").
abi_typelocation("a","H5Tget_array_dims2","Both","Integer32","(%rdi)").
abi_typelocation("a","H5Tget_strpad","Export","Void","()").
abi_typelocation("a","H5Sget_select_elem_pointlist","Both","Integer32","(%rdi)").
abi_typelocation("a","H5Sget_select_hyper_blocklist","Both","Integer32","(%rdi)").
abi_typelocation("a","H5Eset_auto2","Import","Integer32","%rdi").
abi_typelocation("a","H5Sget_regular_hyperslab","Both","Integer32","(%rdi)").
abi_typelocation("a","H5Sget_regular_hyperslab","Both","Integer32","(%rsi)").
abi_typelocation("a","H5Sget_regular_hyperslab","Both","Integer32","(%rdx)").
abi_typelocation("a","H5Sget_regular_hyperslab","Both","Integer32","(%rcx)").
abi_typelocation("a","H5Epush2","Import","Integer32","%rdi").
abi_typelocation("a","H5Lget_val","Both","Void","(%rdi)").
abi_typelocation("a","H5Lget_val","Import","Integer64","%rsi").
abi_typelocation("a","HDfprintf","Import","Integer64","+8").
abi_typelocation("a","HDfprintf","Export","Integer32","%rax").
abi_typelocation("a","H5Aiterate_by_name","Import","Integer64","%rsi").
abi_typelocation("a","H5Lunpack_elink_val","Import","Integer64","%rdi").
abi_typelocation("a","H5Lget_val","Import","Integer64","%rdi").
abi_typelocation("a","H5Lget_val","Import","Integer64","%rsi").
abi_typelocation("a","H5Literate_by_name","Import","Integer64","%rsi").
abi_typelocation("a","H5Lvisit_by_name","Import","Integer64","%rdi").
abi_typelocation("a","H5Epush2","Import","Integer32","%rdi").
abi_typelocation("a","HDfprintf","Export","Integer32","%rax").

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-broadwell/gcc-11.2.0/hdf5-1.10.2-h3jezb6n4xygqj5qcgp5r7rnhm5vgpgk/lib/libhdf5.so.100.2.0
%----------------------------------------------------------------------------
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Integer32","var").
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Integer8","(var+8)").
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Integer8","(var+16)").
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Integer8","(var+24)").
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Integer8","(var+32)").
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Integer8","(var+40)").
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Integer8","(var+48)").
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Integer8","(var+56)").
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Integer8","(var+64)").
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Integer8","(var+72)").
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Integer8","(var+80)").
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Integer8","(var+88)").
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Empty","(var+96)").
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Opaque","(var+104)").
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Integer32","var+112").
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Integer32","var+116").
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Integer64","var+120").
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Integer16","var+128").
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Integer8","var+130").
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Array[1:1]","var").
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Integer8","var").
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Integer64","var+144").
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Empty","(var+152)").
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Empty","(var+160)").
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Opaque","(var+168)").
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Void","(var+176)").
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Integer64","var+184").
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Integer32","var+192").
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Array[20:20]","var").
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Integer8","var").
abi_typelocation("b","H5T_VAX_F32_g","Import","Integer32","var").
abi_typelocation("b","H5T_VAX_F32_g","Import","Integer8","(var+8)").
abi_typelocation("b","H5T_VAX_F32_g","Import","Integer8","(var+16)").
abi_typelocation("b","H5T_VAX_F32_g","Import","Integer8","(var+24)").
abi_typelocation("b","H5T_VAX_F32_g","Import","Integer8","(var+32)").
abi_typelocation("b","H5T_VAX_F32_g","Import","Integer8","(var+40)").
abi_typelocation("b","H5T_VAX_F32_g","Import","Integer8","(var+48)").
abi_typelocation("b","H5T_VAX_F32_g","Import","Integer8","(var+56)").
abi_typelocation("b","H5T_VAX_F32_g","Import","Integer8","(var+64)").
abi_typelocation("b","H5T_VAX_F32_g","Import","Integer8","(var+72)").
abi_typelocation("b","H5T_VAX_F32_g","Import","Integer8","(var+80)").
abi_typelocation("b","H5T_VAX_F32_g","Import","Integer8","(var+88)").
abi_typelocation("b","H5T_VAX_F32_g","Import","Empty","(var+96)").
abi_typelocation("b","H5T_VAX_F32_g","Import","Opaque","(var+104)").
abi_typelocation("b","H5T_VAX_F32_g","Import","Integer32","var+112").
abi_typelocation("b","H5T_VAX_F32_g","Import","Integer32","var+116").
abi_typelocation("b","H5T_VAX_F32_g","Import","Integer64","var+120").
abi_typelocation("b","H5T_VAX_F32_g","Import","Integer16","var+128").
abi_typelocation("b","H5T_VAX_F32_g","Import","Integer8","var+130").
abi_typelocation("b","H5T_VAX_F32_g","Import","Array[1:1]","var").
abi_typelocation("b","H5T_VAX_F32_g","Import","Integer8","var").
abi_typelocation("b","H5T_VAX_F32_g","Import","Integer64","var+144").
abi_typelocation("b","H5T_VAX_F32_g","Import","Empty","(var+152)").
abi_typelocation("b","H5T_VAX_F32_g","Import","Empty","(var+160)").
abi_typelocation("b","H5T_VAX_F32_g","Import","Opaque","(var+168)").
abi_typelocation("b","H5T_VAX_F32_g","Import","Void","(var+176)").
abi_typelocation("b","H5T_VAX_F32_g","Import","Integer64","var+184").
abi_typelocation("b","H5T_VAX_F32_g","Import","Integer32","var+192").
abi_typelocation("b","H5T_VAX_F32_g","Import","Array[20:20]","var").
abi_typelocation("b","H5T_VAX_F32_g","Import","Integer8","var").
abi_typelocation("b","H5T_VAX_F64_g","Import","Integer32","var").
abi_typelocation("b","H5T_VAX_F64_g","Import","Integer8","(var+8)").
abi_typelocation("b","H5T_VAX_F64_g","Import","Integer8","(var+16)").
abi_typelocation("b","H5T_VAX_F64_g","Import","Integer8","(var+24)").
abi_typelocation("b","H5T_VAX_F64_g","Import","Integer8","(var+32)").
abi_typelocation("b","H5T_VAX_F64_g","Import","Integer8","(var+40)").
abi_typelocation("b","H5T_VAX_F64_g","Import","Integer8","(var+48)").
abi_typelocation("b","H5T_VAX_F64_g","Import","Integer8","(var+56)").
abi_typelocation("b","H5T_VAX_F64_g","Import","Integer8","(var+64)").
abi_typelocation("b","H5T_VAX_F64_g","Import","Integer8","(var+72)").
abi_typelocation("b","H5T_VAX_F64_g","Import","Integer8","(var+80)").
abi_typelocation("b","H5T_VAX_F64_g","Import","Integer8","(var+88)").
abi_typelocation("b","H5T_VAX_F64_g","Import","Empty","(var+96)").
abi_typelocation("b","H5T_VAX_F64_g","Import","Opaque","(var+104)").
abi_typelocation("b","H5T_VAX_F64_g","Import","Integer32","var+112").
abi_typelocation("b","H5T_VAX_F64_g","Import","Integer32","var+116").
abi_typelocation("b","H5T_VAX_F64_g","Import","Integer64","var+120").
abi_typelocation("b","H5T_VAX_F64_g","Import","Integer16","var+128").
abi_typelocation("b","H5T_VAX_F64_g","Import","Integer8","var+130").
abi_typelocation("b","H5T_VAX_F64_g","Import","Array[1:1]","var").
abi_typelocation("b","H5T_VAX_F64_g","Import","Integer8","var").
abi_typelocation("b","H5T_VAX_F64_g","Import","Integer64","var+144").
abi_typelocation("b","H5T_VAX_F64_g","Import","Empty","(var+152)").
abi_typelocation("b","H5T_VAX_F64_g","Import","Empty","(var+160)").
abi_typelocation("b","H5T_VAX_F64_g","Import","Opaque","(var+168)").
abi_typelocation("b","H5T_VAX_F64_g","Import","Void","(var+176)").
abi_typelocation("b","H5T_VAX_F64_g","Import","Integer64","var+184").
abi_typelocation("b","H5T_VAX_F64_g","Import","Integer32","var+192").
abi_typelocation("b","H5T_VAX_F64_g","Import","Array[20:20]","var").
abi_typelocation("b","H5T_VAX_F64_g","Import","Integer8","var").
abi_typelocation("b","H5Eget_auto2","Import","Integer64","%rdi").
abi_typelocation("b","H5Eget_auto2","Both","Void","((%rsi))").
abi_typelocation("b","H5Eget_auto2","Both","Void","((%rdx))").
abi_typelocation("b","H5Eget_auto2","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Import","Integer32","(%rdi)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+8)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+16)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+24)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+32)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+40)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+48)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+56)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+64)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+72)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+80)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+88)").
abi_typelocation("b","HDfprintf","Import","Empty","((%rdi)+96)").
abi_typelocation("b","HDfprintf","Import","Integer32","((%rdi)+104)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+8)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+16)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+24)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+32)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+40)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+48)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+56)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+64)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+72)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+80)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+88)").
abi_typelocation("b","HDfprintf","Import","Empty","(((%rdi)+104)+96)").
abi_typelocation("b","HDfprintf","Import","Opaque","(((%rdi)+104)+104)").
abi_typelocation("b","HDfprintf","Import","Integer32","((%rdi)+104)+112").
abi_typelocation("b","HDfprintf","Import","Integer32","((%rdi)+104)+116").
abi_typelocation("b","HDfprintf","Import","Integer64","((%rdi)+104)+120").
abi_typelocation("b","HDfprintf","Import","Integer16","((%rdi)+104)+128").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+104)+130").
abi_typelocation("b","HDfprintf","Import","Array[1:1]","((%rdi)+104)+131").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+104)+131").
abi_typelocation("b","HDfprintf","Import","Integer64","((%rdi)+104)+144").
abi_typelocation("b","HDfprintf","Import","Empty","(((%rdi)+104)+152)").
abi_typelocation("b","HDfprintf","Import","Empty","(((%rdi)+104)+160)").
abi_typelocation("b","HDfprintf","Import","Opaque","(((%rdi)+104)+168)").
abi_typelocation("b","HDfprintf","Import","Void","(((%rdi)+104)+176)").
abi_typelocation("b","HDfprintf","Import","Integer64","((%rdi)+104)+184").
abi_typelocation("b","HDfprintf","Import","Integer32","((%rdi)+104)+192").
abi_typelocation("b","HDfprintf","Import","Array[20:20]","((%rdi)+104)+196").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+104)+196").
abi_typelocation("b","HDfprintf","Import","Integer32","(%rdi)+112").
abi_typelocation("b","HDfprintf","Import","Integer32","(%rdi)+116").
abi_typelocation("b","HDfprintf","Import","Integer64","(%rdi)+120").
abi_typelocation("b","HDfprintf","Import","Integer16","(%rdi)+128").
abi_typelocation("b","HDfprintf","Import","Integer8","(%rdi)+130").
abi_typelocation("b","HDfprintf","Import","Array[1:1]","(%rdi)+131").
abi_typelocation("b","HDfprintf","Import","Integer8","(%rdi)+131").
abi_typelocation("b","HDfprintf","Import","Integer64","(%rdi)+144").
abi_typelocation("b","HDfprintf","Import","Empty","((%rdi)+152)").
abi_typelocation("b","HDfprintf","Import","Empty","((%rdi)+160)").
abi_typelocation("b","HDfprintf","Import","Opaque","((%rdi)+168)").
abi_typelocation("b","HDfprintf","Import","Void","((%rdi)+176)").
abi_typelocation("b","HDfprintf","Import","Integer64","(%rdi)+184").
abi_typelocation("b","HDfprintf","Import","Integer32","(%rdi)+192").
abi_typelocation("b","HDfprintf","Import","Array[20:20]","(%rdi)+196").
abi_typelocation("b","HDfprintf","Import","Integer8","(%rdi)+196").
abi_typelocation("b","HDfprintf","Both","Integer8","(%rsi)").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","H5free_memory","Both","Void","(%rdi)").
abi_typelocation("b","H5free_memory","Export","Integer32","%rax").
abi_typelocation("b","H5close","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","H5Aiterate_by_name","Import","Integer8","()").
abi_typelocation("b","H5Aget_name","Import","Integer64","%rdi").
abi_typelocation("b","H5Aread","Import","Integer8","()").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","H5SL_insert","Import","Integer8","()").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","H5SL_insert","Import","Integer64","%rdi").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","H5SL_search","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Import","Integer32","%rdi").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","H5SL_insert","Import","Integer32","%rdi").
abi_typelocation("b","H5SL_search","Import","Integer32","%rdi").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","H5Eset_auto1","Import","Integer32","%rdi").
abi_typelocation("b","H5Pset_fapl_family","Import","Integer32","()").
abi_typelocation("b","H5Tconvert","Import","Integer8","%rdi").
abi_typelocation("b","H5Tconvert","Import","Integer8","%rsi").
abi_typelocation("b","H5Tconvert","Import","Integer8","%rdx").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","()").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","%rdi").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","%rdi").
abi_typelocation("b","H5Epush2","Import","Integer8","%rdi").
abi_typelocation("b","H5SL_destroy","Import","Integer64","%rdi").
abi_typelocation("b","HDfprintf","Import","Integer8","%rdi").
abi_typelocation("b","H5SL_insert","Import","Integer64","%rdi").
abi_typelocation("b","H5SL_search","Export","Integer64","%rax").
abi_typelocation("b","H5Gopen2","Import","Empty","none").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","H5Eset_auto1","Import","Array","%rdi").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","%rdi").
abi_typelocation("b","H5Eset_auto1","Export","Integer32","()").
abi_typelocation("b","H5Eget_auto1","Export","Integer32","()").
abi_typelocation("b","H5Eset_auto2","Export","Integer32","()").
abi_typelocation("b","H5Eget_auto2","Export","Integer32","()").
abi_typelocation("b","H5Eauto_is_v2","Export","Integer32","()").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","H5Eget_auto1","Import","Void","(())").
abi_typelocation("b","H5Lvisit_by_name","Import","Array","%rax").
abi_typelocation("b","H5Lvisit_by_name","Import","Integer8","%rax").
abi_typelocation("b","H5Literate_by_name","Import","Array","%rax").
abi_typelocation("b","H5Literate_by_name","Import","Integer8","%rax").
abi_typelocation("b","H5Lget_info","Import","Array","%rax").
abi_typelocation("b","H5Lget_info","Import","Integer8","%rax").
abi_typelocation("b","H5Lget_val","Import","Integer64","%rdi").
abi_typelocation("b","H5Lget_val","Import","Array","%rax").
abi_typelocation("b","H5Lget_val","Import","Integer8","%rax").
abi_typelocation("b","H5Lunpack_elink_val","Import","Integer64","%rdi").
abi_typelocation("b","H5Lunpack_elink_val","Import","Empty","(%rax)").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","H5Oclose","Import","Integer8","()").
abi_typelocation("b","H5Oget_comment","Import","Integer8","()").
abi_typelocation("b","H5Oget_comment","Import","Array","%rdi").
abi_typelocation("b","H5Oget_comment","Import","Integer8","%rdi").
abi_typelocation("b","H5Oget_info_by_name","Import","Integer8","()").
abi_typelocation("b","H5Oget_info_by_name","Import","Integer8","()").
abi_typelocation("b","H5Oget_info","Import","Integer8","()").
abi_typelocation("b","H5Oexists_by_name","Import","Integer8","()").
abi_typelocation("b","H5Oexists_by_name","Import","Integer8","()").
abi_typelocation("b","H5SL_search","Export","Integer64","%rax").
abi_typelocation("b","H5SL_insert","Import","Integer64","%rdi").
abi_typelocation("b","H5SL_destroy","Import","Integer64","%rdi").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","H5SL_search","Export","Integer64","%rax").
abi_typelocation("b","H5SL_destroy","Import","Integer64","%rdi").
abi_typelocation("b","H5SL_insert","Import","Integer64","%rdi").
abi_typelocation("b","HDfprintf","Import","Integer8","()").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Import","Integer8","%rdi").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Import","Integer8","%rdi").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Import","Integer8","%rdi").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","H5Pget_external","Import","Empty","none").
abi_typelocation("b","H5Pget_external_count","Export","Integer64","%rax").
abi_typelocation("b","H5Pget_virtual_dsetname","Import","Empty","none").
abi_typelocation("b","H5Pget_virtual_dsetname","Import","Empty","none").
abi_typelocation("b","H5Pget_virtual_filename","Import","Empty","none").
abi_typelocation("b","H5Pget_virtual_filename","Import","Empty","none").
abi_typelocation("b","H5Pget_virtual_srcspace","Import","Empty","none").
abi_typelocation("b","H5Pget_virtual_vspace","Import","Empty","none").
abi_typelocation("b","H5Pget_chunk","Import","Integer64","%rdi").
abi_typelocation("b","H5Pget_chunk","Export","Integer64","%rax").
abi_typelocation("b","H5SL_search","Import","Empty","none").
abi_typelocation("b","H5SL_insert","Import","Empty","none").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5Pget_filter2","Import","Integer64","%rdi").
abi_typelocation("b","H5Pget_nfilters","Export","Integer64","%rax").
abi_typelocation("b","H5Rget_name","Export","Integer8","(%rax)").
abi_typelocation("b","H5Rget_obj_type2","Import","Array","%rdi").
abi_typelocation("b","H5Rget_obj_type2","Import","Integer8","%rdi").
abi_typelocation("b","H5Screate_simple","Import","Integer64","%rdi").
abi_typelocation("b","H5Sget_simple_extent_dims","Export","Integer64","%rax").
abi_typelocation("b","H5Sget_simple_extent_ndims","Export","Integer64","%rax").
abi_typelocation("b","H5Sget_regular_hyperslab","Export","Integer32","(%rax)").
abi_typelocation("b","H5Sselect_hyperslab","Export","Integer32","(%rax)").
abi_typelocation("b","H5Sget_select_hyper_blocklist","Export","Integer32","(%rax)").
abi_typelocation("b","H5Sget_select_elem_pointlist","Import","Void","()").
abi_typelocation("b","H5Sget_select_elem_pointlist","Import","Void","()").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5SL_destroy","Import","Integer64","%rdi").
abi_typelocation("b","H5SL_search","Export","Integer64","%rax").
abi_typelocation("b","H5SL_insert","Import","Integer64","%rdi").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","H5Tconvert","Import","Integer32","()").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+8)").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+16)").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+24)").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+32)").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+40)").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+48)").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+56)").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+64)").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+72)").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+80)").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+88)").
abi_typelocation("b","H5Tconvert","Import","Empty","(()+96)").
abi_typelocation("b","H5Tconvert","Import","Opaque","(()+104)").
abi_typelocation("b","H5Tconvert","Import","Integer32","()+112").
abi_typelocation("b","H5Tconvert","Import","Integer32","()+116").
abi_typelocation("b","H5Tconvert","Import","Integer64","()+120").
abi_typelocation("b","H5Tconvert","Import","Integer16","()+128").
abi_typelocation("b","H5Tconvert","Import","Integer8","()+130").
abi_typelocation("b","H5Tconvert","Import","Array[1:1]","()+131").
abi_typelocation("b","H5Tconvert","Import","Integer8","()+131").
abi_typelocation("b","H5Tconvert","Import","Integer64","()+144").
abi_typelocation("b","H5Tconvert","Import","Empty","(()+152)").
abi_typelocation("b","H5Tconvert","Import","Empty","(()+160)").
abi_typelocation("b","H5Tconvert","Import","Opaque","(()+168)").
abi_typelocation("b","H5Tconvert","Import","Void","(()+176)").
abi_typelocation("b","H5Tconvert","Import","Integer64","()+184").
abi_typelocation("b","H5Tconvert","Import","Integer32","()+192").
abi_typelocation("b","H5Tconvert","Import","Array[20:20]","()+196").
abi_typelocation("b","H5Tconvert","Import","Integer8","()+196").
abi_typelocation("b","H5Tconvert","Import","Integer32","()").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+8)").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+16)").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+24)").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+32)").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+40)").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+48)").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+56)").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+64)").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+72)").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+80)").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+88)").
abi_typelocation("b","H5Tconvert","Import","Empty","(()+96)").
abi_typelocation("b","H5Tconvert","Import","Opaque","(()+104)").
abi_typelocation("b","H5Tconvert","Import","Integer32","()+112").
abi_typelocation("b","H5Tconvert","Import","Integer32","()+116").
abi_typelocation("b","H5Tconvert","Import","Integer64","()+120").
abi_typelocation("b","H5Tconvert","Import","Integer16","()+128").
abi_typelocation("b","H5Tconvert","Import","Integer8","()+130").
abi_typelocation("b","H5Tconvert","Import","Array[1:1]","()+131").
abi_typelocation("b","H5Tconvert","Import","Integer8","()+131").
abi_typelocation("b","H5Tconvert","Import","Integer64","()+144").
abi_typelocation("b","H5Tconvert","Import","Empty","(()+152)").
abi_typelocation("b","H5Tconvert","Import","Empty","(()+160)").
abi_typelocation("b","H5Tconvert","Import","Opaque","(()+168)").
abi_typelocation("b","H5Tconvert","Import","Void","(()+176)").
abi_typelocation("b","H5Tconvert","Import","Integer64","()+184").
abi_typelocation("b","H5Tconvert","Import","Integer32","()+192").
abi_typelocation("b","H5Tconvert","Import","Array[20:20]","()+196").
abi_typelocation("b","H5Tconvert","Import","Integer8","()+196").
abi_typelocation("b","H5Tconvert","Import","Integer8","()").
abi_typelocation("b","H5Tconvert","Import","Integer8","()").
abi_typelocation("b","H5Tconvert","Import","Integer32","()").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+8)").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+16)").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+24)").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+32)").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+40)").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+48)").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+56)").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+64)").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+72)").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+80)").
abi_typelocation("b","H5Tconvert","Import","Integer8","(()+88)").
abi_typelocation("b","H5Tconvert","Import","Empty","(()+96)").
abi_typelocation("b","H5Tconvert","Import","Opaque","(()+104)").
abi_typelocation("b","H5Tconvert","Import","Integer32","()+112").
abi_typelocation("b","H5Tconvert","Import","Integer32","()+116").
abi_typelocation("b","H5Tconvert","Import","Integer64","()+120").
abi_typelocation("b","H5Tconvert","Import","Integer16","()+128").
abi_typelocation("b","H5Tconvert","Import","Integer8","()+130").
abi_typelocation("b","H5Tconvert","Import","Array[1:1]","()+131").
abi_typelocation("b","H5Tconvert","Import","Integer8","()+131").
abi_typelocation("b","H5Tconvert","Import","Integer64","()+144").
abi_typelocation("b","H5Tconvert","Import","Empty","(()+152)").
abi_typelocation("b","H5Tconvert","Import","Empty","(()+160)").
abi_typelocation("b","H5Tconvert","Import","Opaque","(()+168)").
abi_typelocation("b","H5Tconvert","Import","Void","(()+176)").
abi_typelocation("b","H5Tconvert","Import","Integer64","()+184").
abi_typelocation("b","H5Tconvert","Import","Integer32","()+192").
abi_typelocation("b","H5Tconvert","Import","Array[20:20]","()+196").
abi_typelocation("b","H5Tconvert","Import","Integer8","()+196").
abi_typelocation("b","H5Tget_super","Import","Integer32","()").
abi_typelocation("b","H5Tget_super","Import","Integer8","(()+8)").
abi_typelocation("b","H5Tget_super","Import","Integer8","(()+16)").
abi_typelocation("b","H5Tget_super","Import","Integer8","(()+24)").
abi_typelocation("b","H5Tget_super","Import","Integer8","(()+32)").
abi_typelocation("b","H5Tget_super","Import","Integer8","(()+40)").
abi_typelocation("b","H5Tget_super","Import","Integer8","(()+48)").
abi_typelocation("b","H5Tget_super","Import","Integer8","(()+56)").
abi_typelocation("b","H5Tget_super","Import","Integer8","(()+64)").
abi_typelocation("b","H5Tget_super","Import","Integer8","(()+72)").
abi_typelocation("b","H5Tget_super","Import","Integer8","(()+80)").
abi_typelocation("b","H5Tget_super","Import","Integer8","(()+88)").
abi_typelocation("b","H5Tget_super","Import","Empty","(()+96)").
abi_typelocation("b","H5Tget_super","Import","Opaque","(()+104)").
abi_typelocation("b","H5Tget_super","Import","Integer32","()+112").
abi_typelocation("b","H5Tget_super","Import","Integer32","()+116").
abi_typelocation("b","H5Tget_super","Import","Integer64","()+120").
abi_typelocation("b","H5Tget_super","Import","Integer16","()+128").
abi_typelocation("b","H5Tget_super","Import","Integer8","()+130").
abi_typelocation("b","H5Tget_super","Import","Array[1:1]","()+131").
abi_typelocation("b","H5Tget_super","Import","Integer8","()+131").
abi_typelocation("b","H5Tget_super","Import","Integer64","()+144").
abi_typelocation("b","H5Tget_super","Import","Empty","(()+152)").
abi_typelocation("b","H5Tget_super","Import","Empty","(()+160)").
abi_typelocation("b","H5Tget_super","Import","Opaque","(()+168)").
abi_typelocation("b","H5Tget_super","Import","Void","(()+176)").
abi_typelocation("b","H5Tget_super","Import","Integer64","()+184").
abi_typelocation("b","H5Tget_super","Import","Integer32","()+192").
abi_typelocation("b","H5Tget_super","Import","Array[20:20]","()+196").
abi_typelocation("b","H5Tget_super","Import","Integer8","()+196").
abi_typelocation("b","H5Tget_super","Import","Integer32","()").
abi_typelocation("b","H5Tget_super","Import","Integer8","(()+8)").
abi_typelocation("b","H5Tget_super","Import","Integer8","(()+16)").
abi_typelocation("b","H5Tget_super","Import","Integer8","(()+24)").
abi_typelocation("b","H5Tget_super","Import","Integer8","(()+32)").
abi_typelocation("b","H5Tget_super","Import","Integer8","(()+40)").
abi_typelocation("b","H5Tget_super","Import","Integer8","(()+48)").
abi_typelocation("b","H5Tget_super","Import","Integer8","(()+56)").
abi_typelocation("b","H5Tget_super","Import","Integer8","(()+64)").
abi_typelocation("b","H5Tget_super","Import","Integer8","(()+72)").
abi_typelocation("b","H5Tget_super","Import","Integer8","(()+80)").
abi_typelocation("b","H5Tget_super","Import","Integer8","(()+88)").
abi_typelocation("b","H5Tget_super","Import","Empty","(()+96)").
abi_typelocation("b","H5Tget_super","Import","Opaque","(()+104)").
abi_typelocation("b","H5Tget_super","Import","Integer32","()+112").
abi_typelocation("b","H5Tget_super","Import","Integer32","()+116").
abi_typelocation("b","H5Tget_super","Import","Integer64","()+120").
abi_typelocation("b","H5Tget_super","Import","Integer16","()+128").
abi_typelocation("b","H5Tget_super","Import","Integer8","()+130").
abi_typelocation("b","H5Tget_super","Import","Array[1:1]","()+131").
abi_typelocation("b","H5Tget_super","Import","Integer8","()+131").
abi_typelocation("b","H5Tget_super","Import","Integer64","()+144").
abi_typelocation("b","H5Tget_super","Import","Empty","(()+152)").
abi_typelocation("b","H5Tget_super","Import","Empty","(()+160)").
abi_typelocation("b","H5Tget_super","Import","Opaque","(()+168)").
abi_typelocation("b","H5Tget_super","Import","Void","(()+176)").
abi_typelocation("b","H5Tget_super","Import","Integer64","()+184").
abi_typelocation("b","H5Tget_super","Import","Integer32","()+192").
abi_typelocation("b","H5Tget_super","Import","Array[20:20]","()+196").
abi_typelocation("b","H5Tget_super","Import","Integer8","()+196").
abi_typelocation("b","H5Tset_size","Import","Integer32","()").
abi_typelocation("b","H5Tset_size","Import","Integer8","(()+8)").
abi_typelocation("b","H5Tset_size","Import","Integer8","(()+16)").
abi_typelocation("b","H5Tset_size","Import","Integer8","(()+24)").
abi_typelocation("b","H5Tset_size","Import","Integer8","(()+32)").
abi_typelocation("b","H5Tset_size","Import","Integer8","(()+40)").
abi_typelocation("b","H5Tset_size","Import","Integer8","(()+48)").
abi_typelocation("b","H5Tset_size","Import","Integer8","(()+56)").
abi_typelocation("b","H5Tset_size","Import","Integer8","(()+64)").
abi_typelocation("b","H5Tset_size","Import","Integer8","(()+72)").
abi_typelocation("b","H5Tset_size","Import","Integer8","(()+80)").
abi_typelocation("b","H5Tset_size","Import","Integer8","(()+88)").
abi_typelocation("b","H5Tset_size","Import","Empty","(()+96)").
abi_typelocation("b","H5Tset_size","Import","Opaque","(()+104)").
abi_typelocation("b","H5Tset_size","Import","Integer32","()+112").
abi_typelocation("b","H5Tset_size","Import","Integer32","()+116").
abi_typelocation("b","H5Tset_size","Import","Integer64","()+120").
abi_typelocation("b","H5Tset_size","Import","Integer16","()+128").
abi_typelocation("b","H5Tset_size","Import","Integer8","()+130").
abi_typelocation("b","H5Tset_size","Import","Array[1:1]","()+131").
abi_typelocation("b","H5Tset_size","Import","Integer8","()+131").
abi_typelocation("b","H5Tset_size","Import","Integer64","()+144").
abi_typelocation("b","H5Tset_size","Import","Empty","(()+152)").
abi_typelocation("b","H5Tset_size","Import","Empty","(()+160)").
abi_typelocation("b","H5Tset_size","Import","Opaque","(()+168)").
abi_typelocation("b","H5Tset_size","Import","Void","(()+176)").
abi_typelocation("b","H5Tset_size","Import","Integer64","()+184").
abi_typelocation("b","H5Tset_size","Import","Integer32","()+192").
abi_typelocation("b","H5Tset_size","Import","Array[20:20]","()+196").
abi_typelocation("b","H5Tset_size","Import","Integer8","()+196").
abi_typelocation("b","H5Tget_size","Import","Integer32","()").
abi_typelocation("b","H5Tget_size","Import","Integer8","(()+8)").
abi_typelocation("b","H5Tget_size","Import","Integer8","(()+16)").
abi_typelocation("b","H5Tget_size","Import","Integer8","(()+24)").
abi_typelocation("b","H5Tget_size","Import","Integer8","(()+32)").
abi_typelocation("b","H5Tget_size","Import","Integer8","(()+40)").
abi_typelocation("b","H5Tget_size","Import","Integer8","(()+48)").
abi_typelocation("b","H5Tget_size","Import","Integer8","(()+56)").
abi_typelocation("b","H5Tget_size","Import","Integer8","(()+64)").
abi_typelocation("b","H5Tget_size","Import","Integer8","(()+72)").
abi_typelocation("b","H5Tget_size","Import","Integer8","(()+80)").
abi_typelocation("b","H5Tget_size","Import","Integer8","(()+88)").
abi_typelocation("b","H5Tget_size","Import","Empty","(()+96)").
abi_typelocation("b","H5Tget_size","Import","Opaque","(()+104)").
abi_typelocation("b","H5Tget_size","Import","Integer32","()+112").
abi_typelocation("b","H5Tget_size","Import","Integer32","()+116").
abi_typelocation("b","H5Tget_size","Import","Integer64","()+120").
abi_typelocation("b","H5Tget_size","Import","Integer16","()+128").
abi_typelocation("b","H5Tget_size","Import","Integer8","()+130").
abi_typelocation("b","H5Tget_size","Import","Array[1:1]","()+131").
abi_typelocation("b","H5Tget_size","Import","Integer8","()+131").
abi_typelocation("b","H5Tget_size","Import","Integer64","()+144").
abi_typelocation("b","H5Tget_size","Import","Empty","(()+152)").
abi_typelocation("b","H5Tget_size","Import","Empty","(()+160)").
abi_typelocation("b","H5Tget_size","Import","Opaque","(()+168)").
abi_typelocation("b","H5Tget_size","Import","Void","(()+176)").
abi_typelocation("b","H5Tget_size","Import","Integer64","()+184").
abi_typelocation("b","H5Tget_size","Import","Integer32","()+192").
abi_typelocation("b","H5Tget_size","Import","Array[20:20]","()+196").
abi_typelocation("b","H5Tget_size","Import","Integer8","()+196").
abi_typelocation("b","H5Tis_variable_str","Import","Integer32","()").
abi_typelocation("b","H5Tis_variable_str","Import","Integer8","(()+8)").
abi_typelocation("b","H5Tis_variable_str","Import","Integer8","(()+16)").
abi_typelocation("b","H5Tis_variable_str","Import","Integer8","(()+24)").
abi_typelocation("b","H5Tis_variable_str","Import","Integer8","(()+32)").
abi_typelocation("b","H5Tis_variable_str","Import","Integer8","(()+40)").
abi_typelocation("b","H5Tis_variable_str","Import","Integer8","(()+48)").
abi_typelocation("b","H5Tis_variable_str","Import","Integer8","(()+56)").
abi_typelocation("b","H5Tis_variable_str","Import","Integer8","(()+64)").
abi_typelocation("b","H5Tis_variable_str","Import","Integer8","(()+72)").
abi_typelocation("b","H5Tis_variable_str","Import","Integer8","(()+80)").
abi_typelocation("b","H5Tis_variable_str","Import","Integer8","(()+88)").
abi_typelocation("b","H5Tis_variable_str","Import","Empty","(()+96)").
abi_typelocation("b","H5Tis_variable_str","Import","Opaque","(()+104)").
abi_typelocation("b","H5Tis_variable_str","Import","Integer32","()+112").
abi_typelocation("b","H5Tis_variable_str","Import","Integer32","()+116").
abi_typelocation("b","H5Tis_variable_str","Import","Integer64","()+120").
abi_typelocation("b","H5Tis_variable_str","Import","Integer16","()+128").
abi_typelocation("b","H5Tis_variable_str","Import","Integer8","()+130").
abi_typelocation("b","H5Tis_variable_str","Import","Array[1:1]","()+131").
abi_typelocation("b","H5Tis_variable_str","Import","Integer8","()+131").
abi_typelocation("b","H5Tis_variable_str","Import","Integer64","()+144").
abi_typelocation("b","H5Tis_variable_str","Import","Empty","(()+152)").
abi_typelocation("b","H5Tis_variable_str","Import","Empty","(()+160)").
abi_typelocation("b","H5Tis_variable_str","Import","Opaque","(()+168)").
abi_typelocation("b","H5Tis_variable_str","Import","Void","(()+176)").
abi_typelocation("b","H5Tis_variable_str","Import","Integer64","()+184").
abi_typelocation("b","H5Tis_variable_str","Import","Integer32","()+192").
abi_typelocation("b","H5Tis_variable_str","Import","Array[20:20]","()+196").
abi_typelocation("b","H5Tis_variable_str","Import","Integer8","()+196").
abi_typelocation("b","H5Tdetect_class","Import","Integer32","()").
abi_typelocation("b","H5Tdetect_class","Import","Integer8","(()+8)").
abi_typelocation("b","H5Tdetect_class","Import","Integer8","(()+16)").
abi_typelocation("b","H5Tdetect_class","Import","Integer8","(()+24)").
abi_typelocation("b","H5Tdetect_class","Import","Integer8","(()+32)").
abi_typelocation("b","H5Tdetect_class","Import","Integer8","(()+40)").
abi_typelocation("b","H5Tdetect_class","Import","Integer8","(()+48)").
abi_typelocation("b","H5Tdetect_class","Import","Integer8","(()+56)").
abi_typelocation("b","H5Tdetect_class","Import","Integer8","(()+64)").
abi_typelocation("b","H5Tdetect_class","Import","Integer8","(()+72)").
abi_typelocation("b","H5Tdetect_class","Import","Integer8","(()+80)").
abi_typelocation("b","H5Tdetect_class","Import","Integer8","(()+88)").
abi_typelocation("b","H5Tdetect_class","Import","Empty","(()+96)").
abi_typelocation("b","H5Tdetect_class","Import","Opaque","(()+104)").
abi_typelocation("b","H5Tdetect_class","Import","Integer32","()+112").
abi_typelocation("b","H5Tdetect_class","Import","Integer32","()+116").
abi_typelocation("b","H5Tdetect_class","Import","Integer64","()+120").
abi_typelocation("b","H5Tdetect_class","Import","Integer16","()+128").
abi_typelocation("b","H5Tdetect_class","Import","Integer8","()+130").
abi_typelocation("b","H5Tdetect_class","Import","Array[1:1]","()+131").
abi_typelocation("b","H5Tdetect_class","Import","Integer8","()+131").
abi_typelocation("b","H5Tdetect_class","Import","Integer64","()+144").
abi_typelocation("b","H5Tdetect_class","Import","Empty","(()+152)").
abi_typelocation("b","H5Tdetect_class","Import","Empty","(()+160)").
abi_typelocation("b","H5Tdetect_class","Import","Opaque","(()+168)").
abi_typelocation("b","H5Tdetect_class","Import","Void","(()+176)").
abi_typelocation("b","H5Tdetect_class","Import","Integer64","()+184").
abi_typelocation("b","H5Tdetect_class","Import","Integer32","()+192").
abi_typelocation("b","H5Tdetect_class","Import","Array[20:20]","()+196").
abi_typelocation("b","H5Tdetect_class","Import","Integer8","()+196").
abi_typelocation("b","H5Tget_class","Import","Integer32","()").
abi_typelocation("b","H5Tget_class","Import","Integer8","(()+8)").
abi_typelocation("b","H5Tget_class","Import","Integer8","(()+16)").
abi_typelocation("b","H5Tget_class","Import","Integer8","(()+24)").
abi_typelocation("b","H5Tget_class","Import","Integer8","(()+32)").
abi_typelocation("b","H5Tget_class","Import","Integer8","(()+40)").
abi_typelocation("b","H5Tget_class","Import","Integer8","(()+48)").
abi_typelocation("b","H5Tget_class","Import","Integer8","(()+56)").
abi_typelocation("b","H5Tget_class","Import","Integer8","(()+64)").
abi_typelocation("b","H5Tget_class","Import","Integer8","(()+72)").
abi_typelocation("b","H5Tget_class","Import","Integer8","(()+80)").
abi_typelocation("b","H5Tget_class","Import","Integer8","(()+88)").
abi_typelocation("b","H5Tget_class","Import","Empty","(()+96)").
abi_typelocation("b","H5Tget_class","Import","Opaque","(()+104)").
abi_typelocation("b","H5Tget_class","Import","Integer32","()+112").
abi_typelocation("b","H5Tget_class","Import","Integer32","()+116").
abi_typelocation("b","H5Tget_class","Import","Integer64","()+120").
abi_typelocation("b","H5Tget_class","Import","Integer16","()+128").
abi_typelocation("b","H5Tget_class","Import","Integer8","()+130").
abi_typelocation("b","H5Tget_class","Import","Array[1:1]","()+131").
abi_typelocation("b","H5Tget_class","Import","Integer8","()+131").
abi_typelocation("b","H5Tget_class","Import","Integer64","()+144").
abi_typelocation("b","H5Tget_class","Import","Empty","(()+152)").
abi_typelocation("b","H5Tget_class","Import","Empty","(()+160)").
abi_typelocation("b","H5Tget_class","Import","Opaque","(()+168)").
abi_typelocation("b","H5Tget_class","Import","Void","(()+176)").
abi_typelocation("b","H5Tget_class","Import","Integer64","()+184").
abi_typelocation("b","H5Tget_class","Import","Integer32","()+192").
abi_typelocation("b","H5Tget_class","Import","Array[20:20]","()+196").
abi_typelocation("b","H5Tget_class","Import","Integer8","()+196").
abi_typelocation("b","H5Tequal","Import","Integer32","()").
abi_typelocation("b","H5Tequal","Import","Integer8","(()+8)").
abi_typelocation("b","H5Tequal","Import","Integer8","(()+16)").
abi_typelocation("b","H5Tequal","Import","Integer8","(()+24)").
abi_typelocation("b","H5Tequal","Import","Integer8","(()+32)").
abi_typelocation("b","H5Tequal","Import","Integer8","(()+40)").
abi_typelocation("b","H5Tequal","Import","Integer8","(()+48)").
abi_typelocation("b","H5Tequal","Import","Integer8","(()+56)").
abi_typelocation("b","H5Tequal","Import","Integer8","(()+64)").
abi_typelocation("b","H5Tequal","Import","Integer8","(()+72)").
abi_typelocation("b","H5Tequal","Import","Integer8","(()+80)").
abi_typelocation("b","H5Tequal","Import","Integer8","(()+88)").
abi_typelocation("b","H5Tequal","Import","Empty","(()+96)").
abi_typelocation("b","H5Tequal","Import","Opaque","(()+104)").
abi_typelocation("b","H5Tequal","Import","Integer32","()+112").
abi_typelocation("b","H5Tequal","Import","Integer32","()+116").
abi_typelocation("b","H5Tequal","Import","Integer64","()+120").
abi_typelocation("b","H5Tequal","Import","Integer16","()+128").
abi_typelocation("b","H5Tequal","Import","Integer8","()+130").
abi_typelocation("b","H5Tequal","Import","Array[1:1]","()+131").
abi_typelocation("b","H5Tequal","Import","Integer8","()+131").
abi_typelocation("b","H5Tequal","Import","Integer64","()+144").
abi_typelocation("b","H5Tequal","Import","Empty","(()+152)").
abi_typelocation("b","H5Tequal","Import","Empty","(()+160)").
abi_typelocation("b","H5Tequal","Import","Opaque","(()+168)").
abi_typelocation("b","H5Tequal","Import","Void","(()+176)").
abi_typelocation("b","H5Tequal","Import","Integer64","()+184").
abi_typelocation("b","H5Tequal","Import","Integer32","()+192").
abi_typelocation("b","H5Tequal","Import","Array[20:20]","()+196").
abi_typelocation("b","H5Tequal","Import","Integer8","()+196").
abi_typelocation("b","H5Tequal","Import","Integer32","()").
abi_typelocation("b","H5Tequal","Import","Integer8","(()+8)").
abi_typelocation("b","H5Tequal","Import","Integer8","(()+16)").
abi_typelocation("b","H5Tequal","Import","Integer8","(()+24)").
abi_typelocation("b","H5Tequal","Import","Integer8","(()+32)").
abi_typelocation("b","H5Tequal","Import","Integer8","(()+40)").
abi_typelocation("b","H5Tequal","Import","Integer8","(()+48)").
abi_typelocation("b","H5Tequal","Import","Integer8","(()+56)").
abi_typelocation("b","H5Tequal","Import","Integer8","(()+64)").
abi_typelocation("b","H5Tequal","Import","Integer8","(()+72)").
abi_typelocation("b","H5Tequal","Import","Integer8","(()+80)").
abi_typelocation("b","H5Tequal","Import","Integer8","(()+88)").
abi_typelocation("b","H5Tequal","Import","Empty","(()+96)").
abi_typelocation("b","H5Tequal","Import","Opaque","(()+104)").
abi_typelocation("b","H5Tequal","Import","Integer32","()+112").
abi_typelocation("b","H5Tequal","Import","Integer32","()+116").
abi_typelocation("b","H5Tequal","Import","Integer64","()+120").
abi_typelocation("b","H5Tequal","Import","Integer16","()+128").
abi_typelocation("b","H5Tequal","Import","Integer8","()+130").
abi_typelocation("b","H5Tequal","Import","Array[1:1]","()+131").
abi_typelocation("b","H5Tequal","Import","Integer8","()+131").
abi_typelocation("b","H5Tequal","Import","Integer64","()+144").
abi_typelocation("b","H5Tequal","Import","Empty","(()+152)").
abi_typelocation("b","H5Tequal","Import","Empty","(()+160)").
abi_typelocation("b","H5Tequal","Import","Opaque","(()+168)").
abi_typelocation("b","H5Tequal","Import","Void","(()+176)").
abi_typelocation("b","H5Tequal","Import","Integer64","()+184").
abi_typelocation("b","H5Tequal","Import","Integer32","()+192").
abi_typelocation("b","H5Tequal","Import","Array[20:20]","()+196").
abi_typelocation("b","H5Tequal","Import","Integer8","()+196").
abi_typelocation("b","H5Tclose","Import","Integer32","()").
abi_typelocation("b","H5Tclose","Import","Integer8","(()+8)").
abi_typelocation("b","H5Tclose","Import","Integer8","(()+16)").
abi_typelocation("b","H5Tclose","Import","Integer8","(()+24)").
abi_typelocation("b","H5Tclose","Import","Integer8","(()+32)").
abi_typelocation("b","H5Tclose","Import","Integer8","(()+40)").
abi_typelocation("b","H5Tclose","Import","Integer8","(()+48)").
abi_typelocation("b","H5Tclose","Import","Integer8","(()+56)").
abi_typelocation("b","H5Tclose","Import","Integer8","(()+64)").
abi_typelocation("b","H5Tclose","Import","Integer8","(()+72)").
abi_typelocation("b","H5Tclose","Import","Integer8","(()+80)").
abi_typelocation("b","H5Tclose","Import","Integer8","(()+88)").
abi_typelocation("b","H5Tclose","Import","Empty","(()+96)").
abi_typelocation("b","H5Tclose","Import","Opaque","(()+104)").
abi_typelocation("b","H5Tclose","Import","Integer32","()+112").
abi_typelocation("b","H5Tclose","Import","Integer32","()+116").
abi_typelocation("b","H5Tclose","Import","Integer64","()+120").
abi_typelocation("b","H5Tclose","Import","Integer16","()+128").
abi_typelocation("b","H5Tclose","Import","Integer8","()+130").
abi_typelocation("b","H5Tclose","Import","Array[1:1]","()+131").
abi_typelocation("b","H5Tclose","Import","Integer8","()+131").
abi_typelocation("b","H5Tclose","Import","Integer64","()+144").
abi_typelocation("b","H5Tclose","Import","Empty","(()+152)").
abi_typelocation("b","H5Tclose","Import","Empty","(()+160)").
abi_typelocation("b","H5Tclose","Import","Opaque","(()+168)").
abi_typelocation("b","H5Tclose","Import","Void","(()+176)").
abi_typelocation("b","H5Tclose","Import","Integer64","()+184").
abi_typelocation("b","H5Tclose","Import","Integer32","()+192").
abi_typelocation("b","H5Tclose","Import","Array[20:20]","()+196").
abi_typelocation("b","H5Tclose","Import","Integer8","()+196").
abi_typelocation("b","H5Tcopy","Import","Integer32","()").
abi_typelocation("b","H5Tcopy","Import","Integer8","(()+8)").
abi_typelocation("b","H5Tcopy","Import","Integer8","(()+16)").
abi_typelocation("b","H5Tcopy","Import","Integer8","(()+24)").
abi_typelocation("b","H5Tcopy","Import","Integer8","(()+32)").
abi_typelocation("b","H5Tcopy","Import","Integer8","(()+40)").
abi_typelocation("b","H5Tcopy","Import","Integer8","(()+48)").
abi_typelocation("b","H5Tcopy","Import","Integer8","(()+56)").
abi_typelocation("b","H5Tcopy","Import","Integer8","(()+64)").
abi_typelocation("b","H5Tcopy","Import","Integer8","(()+72)").
abi_typelocation("b","H5Tcopy","Import","Integer8","(()+80)").
abi_typelocation("b","H5Tcopy","Import","Integer8","(()+88)").
abi_typelocation("b","H5Tcopy","Import","Empty","(()+96)").
abi_typelocation("b","H5Tcopy","Import","Opaque","(()+104)").
abi_typelocation("b","H5Tcopy","Import","Integer32","()+112").
abi_typelocation("b","H5Tcopy","Import","Integer32","()+116").
abi_typelocation("b","H5Tcopy","Import","Integer64","()+120").
abi_typelocation("b","H5Tcopy","Import","Integer16","()+128").
abi_typelocation("b","H5Tcopy","Import","Integer8","()+130").
abi_typelocation("b","H5Tcopy","Import","Array[1:1]","()+131").
abi_typelocation("b","H5Tcopy","Import","Integer8","()+131").
abi_typelocation("b","H5Tcopy","Import","Integer64","()+144").
abi_typelocation("b","H5Tcopy","Import","Empty","(()+152)").
abi_typelocation("b","H5Tcopy","Import","Empty","(()+160)").
abi_typelocation("b","H5Tcopy","Import","Opaque","(()+168)").
abi_typelocation("b","H5Tcopy","Import","Void","(()+176)").
abi_typelocation("b","H5Tcopy","Import","Integer64","()+184").
abi_typelocation("b","H5Tcopy","Import","Integer32","()+192").
abi_typelocation("b","H5Tcopy","Import","Array[20:20]","()+196").
abi_typelocation("b","H5Tcopy","Import","Integer8","()+196").
abi_typelocation("b","H5Tcopy","Import","Integer32","()").
abi_typelocation("b","H5Tcopy","Import","Integer8","(()+8)").
abi_typelocation("b","H5Tcopy","Import","Integer8","(()+16)").
abi_typelocation("b","H5Tcopy","Import","Integer8","(()+24)").
abi_typelocation("b","H5Tcopy","Import","Integer8","(()+32)").
abi_typelocation("b","H5Tcopy","Import","Integer8","(()+40)").
abi_typelocation("b","H5Tcopy","Import","Integer8","(()+48)").
abi_typelocation("b","H5Tcopy","Import","Integer8","(()+56)").
abi_typelocation("b","H5Tcopy","Import","Integer8","(()+64)").
abi_typelocation("b","H5Tcopy","Import","Integer8","(()+72)").
abi_typelocation("b","H5Tcopy","Import","Integer8","(()+80)").
abi_typelocation("b","H5Tcopy","Import","Integer8","(()+88)").
abi_typelocation("b","H5Tcopy","Import","Empty","(()+96)").
abi_typelocation("b","H5Tcopy","Import","Opaque","(()+104)").
abi_typelocation("b","H5Tcopy","Import","Integer32","()+112").
abi_typelocation("b","H5Tcopy","Import","Integer32","()+116").
abi_typelocation("b","H5Tcopy","Import","Integer64","()+120").
abi_typelocation("b","H5Tcopy","Import","Integer16","()+128").
abi_typelocation("b","H5Tcopy","Import","Integer8","()+130").
abi_typelocation("b","H5Tcopy","Import","Array[1:1]","()+131").
abi_typelocation("b","H5Tcopy","Import","Integer8","()+131").
abi_typelocation("b","H5Tcopy","Import","Integer64","()+144").
abi_typelocation("b","H5Tcopy","Import","Empty","(()+152)").
abi_typelocation("b","H5Tcopy","Import","Empty","(()+160)").
abi_typelocation("b","H5Tcopy","Import","Opaque","(()+168)").
abi_typelocation("b","H5Tcopy","Import","Void","(()+176)").
abi_typelocation("b","H5Tcopy","Import","Integer64","()+184").
abi_typelocation("b","H5Tcopy","Import","Integer32","()+192").
abi_typelocation("b","H5Tcopy","Import","Array[20:20]","()+196").
abi_typelocation("b","H5Tcopy","Import","Integer8","()+196").
abi_typelocation("b","H5Tget_array_dims2","Export","Integer64","%rax").
abi_typelocation("b","H5Tget_array_ndims","Export","Integer64","%rax").
abi_typelocation("b","H5Topen2","Import","Void","()").
abi_typelocation("b","HDfprintf","Import","Integer8","%rdi").
abi_typelocation("b","H5Tget_member_value","Import","Integer8","()").
abi_typelocation("b","H5Tget_nmembers","Export","Integer64","%rax").

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-broadwell/gcc-11.2.0/openmpi-4.1.4-badmtlyk6tcxb6ff3jyiqdj6ksxod5yy/lib/libmpi.so.40.30.4
%----------------------------------------------------------------------------
