
%============================================================================
% Library Facts
%============================================================================

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-11.2.0/hdf5-1.10.7-ravvvqjepyatvml3xazhc4optmxx6mpb/lib/libhdf5_tools.so
%----------------------------------------------------------------------------
abi_typelocation("a","ompi_mpi_comm_world","Import","Empty","none").
abi_typelocation("a","ompi_mpi_char","Import","Empty","none").
abi_typelocation("a","ompi_mpi_byte","Import","Empty","none").
abi_typelocation("a","H5Gclose","Import","Integer64","%rdi").
abi_typelocation("a","H5Gclose","Export","Integer32","%rax").
abi_typelocation("a","H5Gopen2","Import","Integer64","%rdi").
abi_typelocation("a","H5Gopen2","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Gopen2","Import","Integer64","%rdx").
abi_typelocation("a","H5Gopen2","Export","Integer64","%rax").
abi_typelocation("a","H5Tclose","Import","Integer64","%rdi").
abi_typelocation("a","H5Tclose","Export","Integer32","%rax").
abi_typelocation("a","H5Tequal","Import","Integer64","%rdi").
abi_typelocation("a","H5Tequal","Import","Integer64","%rsi").
abi_typelocation("a","H5Tequal","Export","Integer32","%rax").
abi_typelocation("a","H5Topen2","Import","Integer64","%rdi").
abi_typelocation("a","H5Topen2","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Topen2","Import","Integer64","%rdx").
abi_typelocation("a","H5Topen2","Export","Integer64","%rax").
abi_typelocation("a","H5Dclose","Import","Integer64","%rdi").
abi_typelocation("a","H5Dclose","Export","Integer32","%rax").
abi_typelocation("a","H5Dopen2","Import","Integer64","%rdi").
abi_typelocation("a","H5Dopen2","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Dopen2","Import","Integer64","%rdx").
abi_typelocation("a","H5Dopen2","Export","Integer64","%rax").
abi_typelocation("a","MPI_Finalize","Export","Integer32","%rax").
abi_typelocation("a","MPI_Probe","Import","Integer32","%rdi").
abi_typelocation("a","MPI_Probe","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Probe","Import","Empty","(%rdx)").
abi_typelocation("a","MPI_Probe","Import","Integer32","(%rcx)").
abi_typelocation("a","MPI_Probe","Import","Integer32","(%rcx)+4").
abi_typelocation("a","MPI_Probe","Import","Integer32","(%rcx)+8").
abi_typelocation("a","MPI_Probe","Import","Integer32","(%rcx)+12").
abi_typelocation("a","MPI_Probe","Import","Integer64","(%rcx)+16").
abi_typelocation("a","MPI_Probe","Export","Integer32","%rax").
abi_typelocation("a","MPI_Recv","Both","Void","(%rdi)").
abi_typelocation("a","MPI_Recv","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Recv","Import","Empty","(%rdx)").
abi_typelocation("a","MPI_Recv","Import","Integer32","%rcx").
abi_typelocation("a","MPI_Recv","Import","Integer32","%r8").
abi_typelocation("a","MPI_Recv","Import","Empty","(%r9)").
abi_typelocation("a","MPI_Recv","Import","Integer32","(framebase+8)").
abi_typelocation("a","MPI_Recv","Import","Integer32","(framebase+8)+4").
abi_typelocation("a","MPI_Recv","Import","Integer32","(framebase+8)+8").
abi_typelocation("a","MPI_Recv","Import","Integer32","(framebase+8)+12").
abi_typelocation("a","MPI_Recv","Import","Integer64","(framebase+8)+16").
abi_typelocation("a","MPI_Recv","Export","Integer32","%rax").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","%rdi").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Iprobe","Import","Empty","(%rdx)").
abi_typelocation("a","MPI_Iprobe","Both","Integer32","(%rcx)").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","(%r8)").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","(%r8)+4").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","(%r8)+8").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","(%r8)+12").
abi_typelocation("a","MPI_Iprobe","Import","Integer64","(%r8)+16").
abi_typelocation("a","MPI_Iprobe","Export","Integer32","%rax").
abi_typelocation("a","H5Lunpack_elink_val","Import","Integer64","%rsi").
abi_typelocation("a","H5Lunpack_elink_val","Both","Integer32","(%rdx)").
abi_typelocation("a","H5Lunpack_elink_val","Both","Integer8","((%rcx))").
abi_typelocation("a","H5Lunpack_elink_val","Both","Integer8","((%r8))").
abi_typelocation("a","H5Lunpack_elink_val","Export","Integer32","%rax").
abi_typelocation("a","H5Fclose","Import","Integer64","%rdi").
abi_typelocation("a","H5Fclose","Export","Integer32","%rax").
abi_typelocation("a","H5Eset_auto1","Import","Void","(%rdi)").
abi_typelocation("a","H5Eset_auto1","Both","Void","(%rsi)").
abi_typelocation("a","H5Eset_auto1","Export","Integer32","%rax").
abi_typelocation("a","H5Eget_auto1","Both","Void","((%rdi))").
abi_typelocation("a","H5Eget_auto1","Both","Void","((%rsi))").
abi_typelocation("a","H5Eget_auto1","Export","Integer32","%rax").
abi_typelocation("a","H5Eset_auto2","Import","Integer64","%rdi").
abi_typelocation("a","H5Eset_auto2","Import","Void","(%rsi)").
abi_typelocation("a","H5Eset_auto2","Both","Void","(%rdx)").
abi_typelocation("a","H5Eset_auto2","Export","Integer32","%rax").
abi_typelocation("a","H5Eget_auto2","Import","Integer64","%rdi").
abi_typelocation("a","H5Eget_auto2","Both","Void","((%rsi))").
abi_typelocation("a","H5Eget_auto2","Both","Void","((%rdx))").
abi_typelocation("a","H5Eget_auto2","Export","Integer32","%rax").
abi_typelocation("a","H5Eauto_is_v2","Import","Integer64","%rdi").
abi_typelocation("a","H5Eauto_is_v2","Both","Integer32","(%rsi)").
abi_typelocation("a","H5Eauto_is_v2","Export","Integer32","%rax").
abi_typelocation("a","MPI_Abort","Import","Empty","(%rdi)").
abi_typelocation("a","MPI_Abort","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Abort","Export","Integer32","%rax").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","%rdi").
abi_typelocation("a","H5Oget_info_by_name2","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+8").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer32","(%rdx)+16").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer32","(%rdx)+20").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+24").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+32").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+40").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+48").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+56").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer32","(%rdx)+64").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer32","(%rdx)+68").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer32","(%rdx)+72").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer32","(%rdx)+76").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+80").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+88").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+96").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+104").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+112").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+120").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+128").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+136").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+144").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+152").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer32","%rcx").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","%r8").
abi_typelocation("a","H5Oget_info_by_name2","Export","Integer32","%rax").
abi_typelocation("a","H5Lget_info","Import","Integer64","%rdi").
abi_typelocation("a","H5Lget_info","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Lget_info","Import","Integer32","(%rdx)").
abi_typelocation("a","H5Lget_info","Import","Integer8","(%rdx)+4").
abi_typelocation("a","H5Lget_info","Import","Integer64","(%rdx)+8").
abi_typelocation("a","H5Lget_info","Import","Integer32","(%rdx)+16").
abi_typelocation("a","H5Lget_info","Import","Union","(%rdx)+24").
abi_typelocation("a","H5Lget_info","Import","Integer64","%rcx").
abi_typelocation("a","H5Lget_info","Export","Integer32","%rax").
abi_typelocation("a","H5Lexists","Import","Integer64","%rdi").
abi_typelocation("a","H5Lexists","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Lexists","Import","Integer64","%rdx").
abi_typelocation("a","H5Lexists","Export","Integer32","%rax").
abi_typelocation("a","HDfprintf","Import","Integer32","(%rdi)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+8)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+16)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+24)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+32)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+40)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+48)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+56)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+64)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+72)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+80)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+88)").
abi_typelocation("a","HDfprintf","Import","Empty","((%rdi)+96)").
abi_typelocation("a","HDfprintf","Import","Integer32","((%rdi)+104)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+8)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+16)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+24)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+32)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+40)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+48)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+56)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+64)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+72)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+80)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+88)").
abi_typelocation("a","HDfprintf","Import","Empty","(((%rdi)+104)+96)").
abi_typelocation("a","HDfprintf","Import","Opaque","(((%rdi)+104)+104)").
abi_typelocation("a","HDfprintf","Import","Integer32","((%rdi)+104)+112").
abi_typelocation("a","HDfprintf","Import","Integer32","((%rdi)+104)+116").
abi_typelocation("a","HDfprintf","Import","Integer64","((%rdi)+104)+120").
abi_typelocation("a","HDfprintf","Import","Integer16","((%rdi)+104)+128").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+104)+130").
abi_typelocation("a","HDfprintf","Import","Array[1:1]","((%rdi)+104)+131").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+104)+131").
abi_typelocation("a","HDfprintf","Import","Integer64","((%rdi)+104)+144").
abi_typelocation("a","HDfprintf","Import","Empty","(((%rdi)+104)+152)").
abi_typelocation("a","HDfprintf","Import","Empty","(((%rdi)+104)+160)").
abi_typelocation("a","HDfprintf","Import","Opaque","(((%rdi)+104)+168)").
abi_typelocation("a","HDfprintf","Import","Void","(((%rdi)+104)+176)").
abi_typelocation("a","HDfprintf","Import","Integer64","((%rdi)+104)+184").
abi_typelocation("a","HDfprintf","Import","Integer32","((%rdi)+104)+192").
abi_typelocation("a","HDfprintf","Import","Array[20:20]","((%rdi)+104)+196").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+104)+196").
abi_typelocation("a","HDfprintf","Import","Integer32","(%rdi)+112").
abi_typelocation("a","HDfprintf","Import","Integer32","(%rdi)+116").
abi_typelocation("a","HDfprintf","Import","Integer64","(%rdi)+120").
abi_typelocation("a","HDfprintf","Import","Integer16","(%rdi)+128").
abi_typelocation("a","HDfprintf","Import","Integer8","(%rdi)+130").
abi_typelocation("a","HDfprintf","Import","Array[1:1]","(%rdi)+131").
abi_typelocation("a","HDfprintf","Import","Integer8","(%rdi)+131").
abi_typelocation("a","HDfprintf","Import","Integer64","(%rdi)+144").
abi_typelocation("a","HDfprintf","Import","Empty","((%rdi)+152)").
abi_typelocation("a","HDfprintf","Import","Empty","((%rdi)+160)").
abi_typelocation("a","HDfprintf","Import","Opaque","((%rdi)+168)").
abi_typelocation("a","HDfprintf","Import","Void","((%rdi)+176)").
abi_typelocation("a","HDfprintf","Import","Integer64","(%rdi)+184").
abi_typelocation("a","HDfprintf","Import","Integer32","(%rdi)+192").
abi_typelocation("a","HDfprintf","Import","Array[20:20]","(%rdi)+196").
abi_typelocation("a","HDfprintf","Import","Integer8","(%rdi)+196").
abi_typelocation("a","HDfprintf","Both","Integer8","(%rsi)").
abi_typelocation("a","HDfprintf","Export","Integer32","%rax").
abi_typelocation("a","H5Epush2","Import","Integer64","%rdi").
abi_typelocation("a","H5Epush2","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Epush2","Both","Integer8","(%rdx)").
abi_typelocation("a","H5Epush2","Import","Integer32","%rcx").
abi_typelocation("a","H5Epush2","Import","Integer64","%r8").
abi_typelocation("a","H5Epush2","Import","Integer64","%r9").
abi_typelocation("a","H5Epush2","Import","Integer64","framebase+8").
abi_typelocation("a","H5Epush2","Both","Integer8","(framebase+16)").
abi_typelocation("a","H5Epush2","Export","Integer32","%rax").
abi_typelocation("a","MPI_Send","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Send","Import","Empty","(%rdx)").
abi_typelocation("a","MPI_Send","Import","Integer32","%rcx").
abi_typelocation("a","MPI_Send","Import","Integer32","%r8").
abi_typelocation("a","MPI_Send","Import","Empty","(%r9)").
abi_typelocation("a","MPI_Send","Export","Integer32","%rax").
abi_typelocation("a","H5Sget_select_elem_pointlist","Import","Empty","(%rax)").
abi_typelocation("a","H5Oget_info2","Import","Empty","(%rax)").
abi_typelocation("a","H5Sget_select_hyper_blocklist","Import","Empty","(%rax)").
abi_typelocation("a","H5Sclose","Import","Empty","(%rax)").
abi_typelocation("a","H5Oclose","Import","Empty","(%rax)").
abi_typelocation("a","H5Rget_obj_type2","Import","Array","None").
abi_typelocation("a","H5Rget_obj_type2","Import","Empty","(%rax)").
abi_typelocation("a","H5Tenum_nameof","Import","Empty","(%rax)").
abi_typelocation("a","H5Tclose","Import","Empty","(%rax)").
abi_typelocation("a","H5Pclose","Import","Empty","(%rax)").
abi_typelocation("a","H5Eset_auto1","Import","Integer64","%rdi").
abi_typelocation("a","H5Eset_auto1","Import","Empty","(%rax)").
abi_typelocation("a","H5Eget_auto1","Import","Empty","(%rax)").
abi_typelocation("a","H5Eset_auto2","Import","Integer64","%rdi").
abi_typelocation("a","H5Eset_auto2","Import","Empty","(%rax)").
abi_typelocation("a","H5Eget_auto2","Import","Empty","(%rax)").
abi_typelocation("a","H5Eauto_is_v2","Import","Empty","(%rax)").
abi_typelocation("a","H5Tconvert","Import","Integer64","%rdi").
abi_typelocation("a","H5Tconvert","Import","Integer64","%rsi").
abi_typelocation("a","H5Tconvert","Import","Empty","(%rax)").
abi_typelocation("a","HDfprintf","Import","Integer64","%rdi").
abi_typelocation("a","H5Epush2","Import","Integer64","%rdi").
abi_typelocation("a","H5Epush2","Import","Integer64","%rsi").
abi_typelocation("a","H5Epush2","Import","Integer64","%rdx").
abi_typelocation("a","H5Epush2","Import","Empty","(%rax)").
abi_typelocation("a","H5Aget_name","Import","Integer64","%rdi").
abi_typelocation("a","H5Aget_name","Export","Integer64","%rax").
abi_typelocation("a","H5Aopen_by_idx","Import","Integer64","%rdi").
abi_typelocation("a","H5Oget_info2","Import","Integer32","%rdi").
abi_typelocation("a","H5Aopen","Import","Integer64","%rdi").
abi_typelocation("a","H5Eset_auto1","Both","Void","(%rdi)").
abi_typelocation("a","H5Eset_auto2","Both","Void","(%rdi)").
abi_typelocation("a","H5Dvlen_reclaim","Both","Void","(%rdi)").
abi_typelocation("a","H5Aread","Both","Void","(%rdi)").
abi_typelocation("a","H5Sget_simple_extent_dims","Export","Integer32","%rax").
abi_typelocation("a","H5Tget_size","Export","Integer64","%rax").
abi_typelocation("a","HDfprintf","Import","Integer64","%rdi").
abi_typelocation("a","HDfprintf","Export","Integer32","%rax").
abi_typelocation("a","H5Epush2","Import","Integer64","%rdi").
abi_typelocation("a","H5Epush2","Import","Integer64","%rsi").
abi_typelocation("a","H5Epush2","Import","Integer32","%rdx").
abi_typelocation("a","H5Epush2","Import","Integer64","%rcx").
abi_typelocation("a","H5Tget_member_type","Import","Integer64","%rdi").
abi_typelocation("a","H5Tget_nmembers","Export","Integer32","%rax").
abi_typelocation("a","H5Screate_simple","Import","Integer32","%rdi").
abi_typelocation("a","H5Dvlen_reclaim","Import","Integer64","%rdi").
abi_typelocation("a","H5Dread","Import","Integer64","%rdi").
abi_typelocation("a","H5Tget_class","Import","Integer16","(%rax)").
abi_typelocation("a","H5Tget_class","Import","Integer16","(%rax)+2").
abi_typelocation("a","H5Tget_class","Import","Integer32","(%rax)+4").
abi_typelocation("a","H5Tget_class","Import","Union","(%rax)+8").
abi_typelocation("a","H5Tget_class","Import","Integer32","(%rax)+24").
abi_typelocation("a","H5Tget_size","Export","Void","(%rax)").
abi_typelocation("a","H5Sget_simple_extent_dims","Export","Integer32","%rax").
abi_typelocation("a","H5Sget_simple_extent_ndims","Export","Integer32","%rax").
abi_typelocation("a","H5Eset_auto1","Import","Integer64","%rdi").
abi_typelocation("a","H5Eset_auto2","Import","Integer64","%rdi").
abi_typelocation("a","H5Eget_auto2","Import","Integer32","%rdi").
abi_typelocation("a","HDfprintf","Export","Integer32","%rax").
abi_typelocation("a","H5Epush2","Import","Integer64","%rdi").
abi_typelocation("a","H5Epush2","Import","Integer32","%rdi").
abi_typelocation("a","HDfprintf","Export","Integer32","%rax").
abi_typelocation("a","H5Tget_class","Import","Empty","(%rax)").
abi_typelocation("a","H5Oget_comment","Export","Integer64","%rax").
abi_typelocation("a","H5Pget_virtual_dsetname","Export","Integer64","%rax").
abi_typelocation("a","H5Pget_virtual_filename","Export","Integer64","%rax").
abi_typelocation("a","H5Pget_external","Import","Integer64","%rdi").
abi_typelocation("a","H5Pget_external_count","Export","Integer32","%rax").
abi_typelocation("a","H5Pget_filter2","Import","Integer64","%rdi").
abi_typelocation("a","H5Pget_chunk","Import","Integer32","%rdi").
abi_typelocation("a","H5Pget_chunk","Export","Integer32","%rax").
abi_typelocation("a","H5Pget_nfilters","Export","Integer32","%rax").
abi_typelocation("a","H5Pget_fill_value","Both","Void","(%rdi)").
abi_typelocation("a","H5Tconvert","Both","Void","(%rdi)").
abi_typelocation("a","H5Tconvert","Both","Void","(%rsi)").
abi_typelocation("a","H5Tget_member_value","Import","Integer64","%rdi").
abi_typelocation("a","H5Tget_member_value","Both","Void","(%rsi)").
abi_typelocation("a","H5Tget_array_dims2","Export","Integer32","%rax").
abi_typelocation("a","H5Tget_array_ndims","Export","Integer32","%rax").
abi_typelocation("a","H5Tget_member_type","Import","Integer64","%rdi").
abi_typelocation("a","H5Tget_member_name","Import","Integer64","%rdi").
abi_typelocation("a","H5Tget_nmembers","Export","Integer32","%rax").
abi_typelocation("a","H5free_memory","Both","Void","(%rdi)").
abi_typelocation("a","H5Oget_info2","Import","Integer64","%rdi").
abi_typelocation("a","H5Aread","Both","Void","(%rdi)").
abi_typelocation("a","H5Dvlen_reclaim","Both","Void","(%rdi)").
abi_typelocation("a","H5Sget_simple_extent_dims","Export","Integer32","%rax").
abi_typelocation("a","H5Dread","Both","Void","(%rdi)").
abi_typelocation("a","H5Screate_simple","Import","Integer32","%rdi").
abi_typelocation("a","H5Sget_simple_extent_ndims","Export","Integer32","%rax").
abi_typelocation("a","H5Epush2","Import","Integer64","%rdi").
abi_typelocation("a","HDfprintf","Export","Integer32","%rax").
abi_typelocation("a","H5Pget_filter2","Import","Integer32","%rdi").
abi_typelocation("a","HDfprintf","Export","Integer32","%rax").
abi_typelocation("a","H5Epush2","Import","Integer32","%rdi").
abi_typelocation("a","H5Pget_nfilters","Export","Integer32","%rax").
abi_typelocation("a","H5SL_search","Export","Integer64","%rax").
abi_typelocation("a","H5SL_insert","Import","Integer64","%rdi").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer32","%rdi").
abi_typelocation("a","H5SL_destroy","Import","Integer64","%rdi").
abi_typelocation("a","H5Dclose","Export","Integer16","%rdi").
abi_typelocation("a","H5Dclose","Export","Integer16","%rdi").
abi_typelocation("a","H5Dclose","Export","Integer32","%rdi").
abi_typelocation("a","H5Dclose","Export","Integer32","%rsi").
abi_typelocation("a","H5Sclose","Export","Integer16","%rdi").
abi_typelocation("a","H5Sclose","Export","Integer16","%rdi").
abi_typelocation("a","H5Sclose","Export","Integer32","%rdi").
abi_typelocation("a","H5Sclose","Export","Integer32","%rsi").
abi_typelocation("a","H5Rget_name","Export","Integer16","%rdi").
abi_typelocation("a","H5Rget_name","Export","Integer16","%rdi").
abi_typelocation("a","H5Rget_name","Export","Integer32","%rdi").
abi_typelocation("a","H5Rget_name","Export","Integer32","%rsi").
abi_typelocation("a","H5Rget_region","Export","Integer16","%rdi").
abi_typelocation("a","H5Rget_region","Export","Integer16","%rdi").
abi_typelocation("a","H5Rget_region","Export","Integer32","%rdi").
abi_typelocation("a","H5Rget_region","Export","Integer32","%rsi").
abi_typelocation("a","H5Rget_region","Import","Integer16","%rax").
abi_typelocation("a","H5Rget_region","Import","Integer16","%rax+2").
abi_typelocation("a","H5Rget_region","Import","Integer32","%rax+4").
abi_typelocation("a","H5Rget_region","Import","Union","%rax+8").
abi_typelocation("a","H5Rget_region","Import","Integer32","%rax+24").
abi_typelocation("a","H5Tget_array_dims2","Export","Integer16","%rdi").
abi_typelocation("a","H5Tget_array_dims2","Export","Integer16","%rdi").
abi_typelocation("a","H5Tget_array_dims2","Export","Integer32","%rdi").
abi_typelocation("a","H5Tget_array_dims2","Export","Integer32","%rsi").
abi_typelocation("a","H5Tget_array_ndims","Export","Integer16","%rdi").
abi_typelocation("a","H5Tget_array_ndims","Export","Integer16","%rdi").
abi_typelocation("a","H5Tget_array_ndims","Export","Integer32","%rdi").
abi_typelocation("a","H5Tget_array_ndims","Export","Integer32","%rsi").
abi_typelocation("a","H5Tget_super","Export","Integer16","%rdi").
abi_typelocation("a","H5Tget_super","Export","Integer16","%rdi").
abi_typelocation("a","H5Tget_super","Export","Integer32","%rdi").
abi_typelocation("a","H5Tget_super","Export","Integer32","%rsi").
abi_typelocation("a","H5Tget_super","Import","Integer16","%rax").
abi_typelocation("a","H5Tget_super","Import","Integer16","%rax+2").
abi_typelocation("a","H5Tget_super","Import","Integer32","%rax+4").
abi_typelocation("a","H5Tget_super","Import","Union","%rax+8").
abi_typelocation("a","H5Tget_super","Import","Integer32","%rax+24").
abi_typelocation("a","H5Oclose","Export","Integer16","%rdi").
abi_typelocation("a","H5Oclose","Export","Integer16","%rdi").
abi_typelocation("a","H5Oclose","Export","Integer32","%rdi").
abi_typelocation("a","H5Oclose","Export","Integer32","%rsi").
abi_typelocation("a","H5Oget_info2","Export","Integer16","%rdi").
abi_typelocation("a","H5Oget_info2","Export","Integer16","%rdi").
abi_typelocation("a","H5Oget_info2","Export","Integer32","%rdi").
abi_typelocation("a","H5Oget_info2","Export","Integer32","%rsi").
abi_typelocation("a","H5Rdereference2","Export","Integer16","%rdi").
abi_typelocation("a","H5Rdereference2","Export","Integer16","%rdi").
abi_typelocation("a","H5Rdereference2","Export","Integer32","%rdi").
abi_typelocation("a","H5Rdereference2","Export","Integer32","%rsi").
abi_typelocation("a","H5Rdereference2","Export","Integer16","%rdx").
abi_typelocation("a","H5Rdereference2","Export","Integer16","%rdx").
abi_typelocation("a","H5Rdereference2","Export","Integer32","%rdx").
abi_typelocation("a","H5Rdereference2","Export","Integer32","%rcx").
abi_typelocation("a","H5Rdereference2","Import","Integer16","%rax").
abi_typelocation("a","H5Rdereference2","Import","Integer16","%rax+2").
abi_typelocation("a","H5Rdereference2","Import","Integer32","%rax+4").
abi_typelocation("a","H5Rdereference2","Import","Union","%rax+8").
abi_typelocation("a","H5Rdereference2","Import","Integer32","%rax+24").
abi_typelocation("a","H5Tenum_nameof","Export","Integer16","%rdi").
abi_typelocation("a","H5Tenum_nameof","Export","Integer16","%rdi").
abi_typelocation("a","H5Tenum_nameof","Export","Integer32","%rdi").
abi_typelocation("a","H5Tenum_nameof","Export","Integer32","%rsi").
abi_typelocation("a","H5Tclose","Export","Integer16","%rdi").
abi_typelocation("a","H5Tclose","Export","Integer16","%rdi").
abi_typelocation("a","H5Tclose","Export","Integer32","%rdi").
abi_typelocation("a","H5Tclose","Export","Integer32","%rsi").
abi_typelocation("a","H5Tget_member_type","Export","Integer16","%rdi").
abi_typelocation("a","H5Tget_member_type","Export","Integer16","%rdi").
abi_typelocation("a","H5Tget_member_type","Export","Integer32","%rdi").
abi_typelocation("a","H5Tget_member_type","Export","Integer32","%rsi").
abi_typelocation("a","H5Tget_member_type","Import","Integer16","%rax").
abi_typelocation("a","H5Tget_member_type","Import","Integer16","%rax+2").
abi_typelocation("a","H5Tget_member_type","Import","Integer32","%rax+4").
abi_typelocation("a","H5Tget_member_type","Import","Union","%rax+8").
abi_typelocation("a","H5Tget_member_type","Import","Integer32","%rax+24").
abi_typelocation("a","H5Tget_member_offset","Export","Integer16","%rdi").
abi_typelocation("a","H5Tget_member_offset","Export","Integer16","%rdi").
abi_typelocation("a","H5Tget_member_offset","Export","Integer32","%rdi").
abi_typelocation("a","H5Tget_member_offset","Export","Integer32","%rsi").
abi_typelocation("a","H5Tget_member_name","Export","Integer16","%rdi").
abi_typelocation("a","H5Tget_member_name","Export","Integer16","%rdi").
abi_typelocation("a","H5Tget_member_name","Export","Integer32","%rdi").
abi_typelocation("a","H5Tget_member_name","Export","Integer32","%rsi").
abi_typelocation("a","H5Tget_nmembers","Export","Integer16","%rdi").
abi_typelocation("a","H5Tget_nmembers","Export","Integer16","%rdi").
abi_typelocation("a","H5Tget_nmembers","Export","Integer32","%rdi").
abi_typelocation("a","H5Tget_nmembers","Export","Integer32","%rsi").
abi_typelocation("a","H5Tget_strpad","Export","Integer16","%rdi").
abi_typelocation("a","H5Tget_strpad","Export","Integer16","%rdi").
abi_typelocation("a","H5Tget_strpad","Export","Integer32","%rdi").
abi_typelocation("a","H5Tget_strpad","Export","Integer32","%rsi").
abi_typelocation("a","H5Tget_strpad","Import","Empty","none").
abi_typelocation("a","H5Tis_variable_str","Export","Integer16","%rdi").
abi_typelocation("a","H5Tis_variable_str","Export","Integer16","%rdi").
abi_typelocation("a","H5Tis_variable_str","Export","Integer32","%rdi").
abi_typelocation("a","H5Tis_variable_str","Export","Integer32","%rsi").
abi_typelocation("a","H5Tget_class","Export","Integer16","%rdi").
abi_typelocation("a","H5Tget_class","Export","Integer16","%rdi").
abi_typelocation("a","H5Tget_class","Export","Integer32","%rdi").
abi_typelocation("a","H5Tget_class","Export","Integer32","%rsi").
abi_typelocation("a","H5Tget_class","Import","Empty","none").
abi_typelocation("a","H5Tget_sign","Export","Integer16","%rdi").
abi_typelocation("a","H5Tget_sign","Export","Integer16","%rdi").
abi_typelocation("a","H5Tget_sign","Export","Integer32","%rdi").
abi_typelocation("a","H5Tget_sign","Export","Integer32","%rsi").
abi_typelocation("a","H5Tget_size","Export","Integer16","%rdi").
abi_typelocation("a","H5Tget_size","Export","Integer16","%rdi").
abi_typelocation("a","H5Tget_size","Export","Integer32","%rdi").
abi_typelocation("a","H5Tget_size","Export","Integer32","%rsi").
abi_typelocation("a","H5Sget_select_elem_pointlist","Export","Integer16","%rdi").
abi_typelocation("a","H5Sget_select_elem_pointlist","Export","Integer16","%rdi").
abi_typelocation("a","H5Sget_select_elem_pointlist","Export","Integer32","%rdi").
abi_typelocation("a","H5Sget_select_elem_pointlist","Export","Integer32","%rsi").
abi_typelocation("a","H5Sget_select_elem_npoints","Export","Integer16","%rdi").
abi_typelocation("a","H5Sget_select_elem_npoints","Export","Integer16","%rdi").
abi_typelocation("a","H5Sget_select_elem_npoints","Export","Integer32","%rdi").
abi_typelocation("a","H5Sget_select_elem_npoints","Export","Integer32","%rsi").
abi_typelocation("a","H5Sget_select_elem_npoints","Import","Empty","%rax").
abi_typelocation("a","H5Sget_select_hyper_blocklist","Export","Integer16","%rdi").
abi_typelocation("a","H5Sget_select_hyper_blocklist","Export","Integer16","%rdi").
abi_typelocation("a","H5Sget_select_hyper_blocklist","Export","Integer32","%rdi").
abi_typelocation("a","H5Sget_select_hyper_blocklist","Export","Integer32","%rsi").
abi_typelocation("a","H5Sget_select_hyper_nblocks","Export","Integer16","%rdi").
abi_typelocation("a","H5Sget_select_hyper_nblocks","Export","Integer16","%rdi").
abi_typelocation("a","H5Sget_select_hyper_nblocks","Export","Integer32","%rdi").
abi_typelocation("a","H5Sget_select_hyper_nblocks","Export","Integer32","%rsi").
abi_typelocation("a","H5Sget_select_hyper_nblocks","Import","Empty","%rax").
abi_typelocation("a","H5Eget_auto1","Import","Array","%rdi").
abi_typelocation("a","H5Eget_auto1","Import","Integer64","((%rdi))").
abi_typelocation("a","H5Eget_auto1","Import","Integer32","(%rdi)+8").
abi_typelocation("a","H5Eget_auto1","Import","Integer64","((%rdi)+16)").
abi_typelocation("a","H5Eget_auto1","Import","Integer32","(%rdi)+24").
abi_typelocation("a","H5Eget_auto1","Import","Integer64","((%rdi)+32)").
abi_typelocation("a","H5Eget_auto1","Import","Integer32","(%rdi)+40").
abi_typelocation("a","H5Eget_auto1","Import","Integer64","((%rdi)+48)").
abi_typelocation("a","H5Eget_auto1","Import","Integer32","(%rdi)+56").
abi_typelocation("a","H5Eset_auto2","Export","Integer16","%rdi").
abi_typelocation("a","H5Eset_auto2","Export","Integer16","%rdi").
abi_typelocation("a","H5Eset_auto2","Export","Integer32","%rdi").
abi_typelocation("a","H5Eset_auto2","Export","Integer32","%rsi").
abi_typelocation("a","H5Eget_auto2","Export","Integer16","%rdi").
abi_typelocation("a","H5Eget_auto2","Export","Integer16","%rdi").
abi_typelocation("a","H5Eget_auto2","Export","Integer32","%rdi").
abi_typelocation("a","H5Eget_auto2","Export","Integer32","%rsi").
abi_typelocation("a","H5Eauto_is_v2","Export","Integer16","%rdi").
abi_typelocation("a","H5Eauto_is_v2","Export","Integer16","%rdi").
abi_typelocation("a","H5Eauto_is_v2","Export","Integer32","%rdi").
abi_typelocation("a","H5Eauto_is_v2","Export","Integer32","%rsi").
abi_typelocation("a","H5Sget_regular_hyperslab","Export","Integer16","%rdi").
abi_typelocation("a","H5Sget_regular_hyperslab","Export","Integer16","%rdi").
abi_typelocation("a","H5Sget_regular_hyperslab","Export","Integer32","%rdi").
abi_typelocation("a","H5Sget_regular_hyperslab","Export","Integer32","%rsi").
abi_typelocation("a","H5Sget_simple_extent_ndims","Export","Integer16","%rdi").
abi_typelocation("a","H5Sget_simple_extent_ndims","Export","Integer16","%rdi").
abi_typelocation("a","H5Sget_simple_extent_ndims","Export","Integer32","%rdi").
abi_typelocation("a","H5Sget_simple_extent_ndims","Export","Integer32","%rsi").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer32","%rdi").
abi_typelocation("a","H5Lget_val","Both","Void","(%rdi)").
abi_typelocation("a","H5Lget_val","Import","Integer64","%rsi").
abi_typelocation("a","H5Oget_info2","Import","Integer32","%rdi").
abi_typelocation("a","H5Epush2","Import","Integer32","%rdi").
abi_typelocation("a","HDfprintf","Export","Integer32","%rax").
abi_typelocation("a","H5Aiterate_by_name","Both","Void","(%rdi)").
abi_typelocation("a","H5Lunpack_elink_val","Import","Integer64","%rdi").
abi_typelocation("a","H5Lget_val","Both","Void","(%rdi)").
abi_typelocation("a","H5Lget_val","Import","Integer64","%rsi").
abi_typelocation("a","H5Literate_by_name","Both","Void","(%rdi)").
abi_typelocation("a","H5Lvisit_by_name","Both","Void","(%rdi)").
abi_typelocation("a","HDfprintf","Export","Integer32","%rax").
abi_typelocation("a","H5Epush2","Import","Integer32","%rdi").
abi_typelocation("a","H5Oget_info2","Import","Integer32","%rdi").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer32","%rdi").
abi_typelocation("a","HDfprintf","Export","Integer32","%rax").

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-11.2.0/hdf5-1.10.7-y75xt4oelugzqhc3lpe3ufbznhyicd4f/lib/libhdf5.so.103.3.0
%----------------------------------------------------------------------------
abi_typelocation("b","H5Eget_auto2","Import","Integer64","%rdi").
abi_typelocation("b","H5Eget_auto2","Both","Void","((%rsi))").
abi_typelocation("b","H5Eget_auto2","Both","Void","((%rdx))").
abi_typelocation("b","H5Eget_auto2","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Import","Integer32","(%rdi)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+8)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+16)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+24)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+32)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+40)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+48)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+56)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+64)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+72)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+80)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+88)").
abi_typelocation("b","HDfprintf","Import","Empty","((%rdi)+96)").
abi_typelocation("b","HDfprintf","Import","Integer32","((%rdi)+104)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+8)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+16)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+24)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+32)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+40)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+48)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+56)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+64)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+72)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+80)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+88)").
abi_typelocation("b","HDfprintf","Import","Empty","(((%rdi)+104)+96)").
abi_typelocation("b","HDfprintf","Import","Opaque","(((%rdi)+104)+104)").
abi_typelocation("b","HDfprintf","Import","Integer32","((%rdi)+104)+112").
abi_typelocation("b","HDfprintf","Import","Integer32","((%rdi)+104)+116").
abi_typelocation("b","HDfprintf","Import","Integer64","((%rdi)+104)+120").
abi_typelocation("b","HDfprintf","Import","Integer16","((%rdi)+104)+128").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+104)+130").
abi_typelocation("b","HDfprintf","Import","Array[1:1]","((%rdi)+104)+131").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+104)+131").
abi_typelocation("b","HDfprintf","Import","Integer64","((%rdi)+104)+144").
abi_typelocation("b","HDfprintf","Import","Empty","(((%rdi)+104)+152)").
abi_typelocation("b","HDfprintf","Import","Empty","(((%rdi)+104)+160)").
abi_typelocation("b","HDfprintf","Import","Opaque","(((%rdi)+104)+168)").
abi_typelocation("b","HDfprintf","Import","Void","(((%rdi)+104)+176)").
abi_typelocation("b","HDfprintf","Import","Integer64","((%rdi)+104)+184").
abi_typelocation("b","HDfprintf","Import","Integer32","((%rdi)+104)+192").
abi_typelocation("b","HDfprintf","Import","Array[20:20]","((%rdi)+104)+196").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+104)+196").
abi_typelocation("b","HDfprintf","Import","Integer32","(%rdi)+112").
abi_typelocation("b","HDfprintf","Import","Integer32","(%rdi)+116").
abi_typelocation("b","HDfprintf","Import","Integer64","(%rdi)+120").
abi_typelocation("b","HDfprintf","Import","Integer16","(%rdi)+128").
abi_typelocation("b","HDfprintf","Import","Integer8","(%rdi)+130").
abi_typelocation("b","HDfprintf","Import","Array[1:1]","(%rdi)+131").
abi_typelocation("b","HDfprintf","Import","Integer8","(%rdi)+131").
abi_typelocation("b","HDfprintf","Import","Integer64","(%rdi)+144").
abi_typelocation("b","HDfprintf","Import","Empty","((%rdi)+152)").
abi_typelocation("b","HDfprintf","Import","Empty","((%rdi)+160)").
abi_typelocation("b","HDfprintf","Import","Opaque","((%rdi)+168)").
abi_typelocation("b","HDfprintf","Import","Void","((%rdi)+176)").
abi_typelocation("b","HDfprintf","Import","Integer64","(%rdi)+184").
abi_typelocation("b","HDfprintf","Import","Integer32","(%rdi)+192").
abi_typelocation("b","HDfprintf","Import","Array[20:20]","(%rdi)+196").
abi_typelocation("b","HDfprintf","Import","Integer8","(%rdi)+196").
abi_typelocation("b","HDfprintf","Both","Integer8","(%rsi)").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","H5free_memory","Both","Void","(%rdi)").
abi_typelocation("b","H5free_memory","Export","Integer32","%rax").
abi_typelocation("b","H5close","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","H5SL_create","Import","Function","%rdi").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","H5Dvlen_reclaim","Import","Integer8","()").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","H5Dread","Import","Integer8","()").
abi_typelocation("b","H5SL_search","Export","Integer8","%rax").
abi_typelocation("b","H5Eset_auto1","Export","Integer32","%rax").
abi_typelocation("b","H5Eget_auto1","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Import","Empty","none").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","H5Pset_fapl_mpio","Import","Empty","none").
abi_typelocation("b","H5Tconvert","Import","Integer8","%rdi").
abi_typelocation("b","H5Tconvert","Import","Integer64","%rsi").
abi_typelocation("b","H5Tconvert","Import","Integer64","%rdx").
abi_typelocation("b","H5Eset_auto1","Import","Float32","%xmm0").
abi_typelocation("b","H5Eset_auto1","Import","Integer64","%rdi").
abi_typelocation("b","H5Eset_auto2","Import","Integer64","%rdi").
abi_typelocation("b","H5Epush2","Import","Integer8","%rdi").
abi_typelocation("b","H5Epush2","Import","Empty","(%rax)").
abi_typelocation("b","H5open","Import","Empty","(%rax)").
abi_typelocation("b","H5Pset_fapl_stdio","Import","Empty","(%rax)").
abi_typelocation("b","H5SL_create","Import","Array","%rdi").
abi_typelocation("b","H5SL_create","Import","Integer8","%rdi").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","H5SL_create","Import","Function","%rdi").
abi_typelocation("b","H5Gclose","Import","Empty","none").
abi_typelocation("b","H5Gopen2","Import","Empty","none").
abi_typelocation("b","H5Gopen2","Import","Empty","none").
abi_typelocation("b","H5Gopen2","Import","Empty","none").
abi_typelocation("b","H5Gopen2","Import","Empty","none").
abi_typelocation("b","HDfprintf","Import","Integer8","()").
abi_typelocation("b","H5Eget_auto1","Import","Empty","none").
abi_typelocation("b","H5Eget_auto2","Import","Empty","none").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","H5SL_search","Export","Integer8","()").
abi_typelocation("b","H5SL_insert","Import","Integer8","()").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","()").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","()").
abi_typelocation("b","H5SL_create","Import","Function","%rdi").
abi_typelocation("b","HDfprintf","Import","Integer32","(%rdi)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+8)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+16)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+24)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+32)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+40)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+48)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+56)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+64)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+72)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+80)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+88)").
abi_typelocation("b","HDfprintf","Import","Empty","((%rdi)+96)").
abi_typelocation("b","HDfprintf","Import","Integer32","((%rdi)+104)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+8)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+16)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+24)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+32)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+40)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+48)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+56)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+64)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+72)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+80)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+88)").
abi_typelocation("b","HDfprintf","Import","Empty","(((%rdi)+104)+96)").
abi_typelocation("b","HDfprintf","Import","Opaque","(((%rdi)+104)+104)").
abi_typelocation("b","HDfprintf","Import","Integer32","((%rdi)+104)+112").
abi_typelocation("b","HDfprintf","Import","Integer32","((%rdi)+104)+116").
abi_typelocation("b","HDfprintf","Import","Integer64","((%rdi)+104)+120").
abi_typelocation("b","HDfprintf","Import","Integer16","((%rdi)+104)+128").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+104)+130").
abi_typelocation("b","HDfprintf","Import","Array[1:1]","((%rdi)+104)+131").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+104)+131").
abi_typelocation("b","HDfprintf","Import","Integer64","((%rdi)+104)+144").
abi_typelocation("b","HDfprintf","Import","Empty","(((%rdi)+104)+152)").
abi_typelocation("b","HDfprintf","Import","Empty","(((%rdi)+104)+160)").
abi_typelocation("b","HDfprintf","Import","Opaque","(((%rdi)+104)+168)").
abi_typelocation("b","HDfprintf","Import","Void","(((%rdi)+104)+176)").
abi_typelocation("b","HDfprintf","Import","Integer64","((%rdi)+104)+184").
abi_typelocation("b","HDfprintf","Import","Integer32","((%rdi)+104)+192").
abi_typelocation("b","HDfprintf","Import","Array[20:20]","((%rdi)+104)+196").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+104)+196").
abi_typelocation("b","HDfprintf","Import","Integer32","(%rdi)+112").
abi_typelocation("b","HDfprintf","Import","Integer32","(%rdi)+116").
abi_typelocation("b","HDfprintf","Import","Integer64","(%rdi)+120").
abi_typelocation("b","HDfprintf","Import","Integer16","(%rdi)+128").
abi_typelocation("b","HDfprintf","Import","Integer8","(%rdi)+130").
abi_typelocation("b","HDfprintf","Import","Array[1:1]","(%rdi)+131").
abi_typelocation("b","HDfprintf","Import","Integer8","(%rdi)+131").
abi_typelocation("b","HDfprintf","Import","Integer64","(%rdi)+144").
abi_typelocation("b","HDfprintf","Import","Empty","((%rdi)+152)").
abi_typelocation("b","HDfprintf","Import","Empty","((%rdi)+160)").
abi_typelocation("b","HDfprintf","Import","Opaque","((%rdi)+168)").
abi_typelocation("b","HDfprintf","Import","Void","((%rdi)+176)").
abi_typelocation("b","HDfprintf","Import","Integer64","(%rdi)+184").
abi_typelocation("b","HDfprintf","Import","Integer32","(%rdi)+192").
abi_typelocation("b","HDfprintf","Import","Array[20:20]","(%rdi)+196").
abi_typelocation("b","HDfprintf","Import","Integer8","(%rdi)+196").
abi_typelocation("b","HDfprintf","Both","Integer8","(%rsi)").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","H5Lunpack_elink_val","Import","Empty","(%rdi)").
abi_typelocation("b","HDfprintf","Import","Empty","none").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Import","Integer32","()").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+8)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+16)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+24)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+32)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+40)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+48)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+56)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+64)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+72)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+80)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+88)").
abi_typelocation("b","HDfprintf","Import","Empty","(()+96)").
abi_typelocation("b","HDfprintf","Import","Opaque","(()+104)").
abi_typelocation("b","HDfprintf","Import","Integer32","()+112").
abi_typelocation("b","HDfprintf","Import","Integer32","()+116").
abi_typelocation("b","HDfprintf","Import","Integer64","()+120").
abi_typelocation("b","HDfprintf","Import","Integer16","()+128").
abi_typelocation("b","HDfprintf","Import","Integer8","()+130").
abi_typelocation("b","HDfprintf","Import","Array[1:1]","()+131").
abi_typelocation("b","HDfprintf","Import","Integer8","()+131").
abi_typelocation("b","HDfprintf","Import","Integer64","()+144").
abi_typelocation("b","HDfprintf","Import","Empty","(()+152)").
abi_typelocation("b","HDfprintf","Import","Empty","(()+160)").
abi_typelocation("b","HDfprintf","Import","Opaque","(()+168)").
abi_typelocation("b","HDfprintf","Import","Void","(()+176)").
abi_typelocation("b","HDfprintf","Import","Integer64","()+184").
abi_typelocation("b","HDfprintf","Import","Integer32","()+192").
abi_typelocation("b","HDfprintf","Import","Array[20:20]","()+196").
abi_typelocation("b","HDfprintf","Import","Integer8","()+196").
abi_typelocation("b","HDfprintf","Import","Void","()").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Import","Integer32","()").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+8)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+16)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+24)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+32)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+40)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+48)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+56)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+64)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+72)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+80)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+88)").
abi_typelocation("b","HDfprintf","Import","Empty","(()+96)").
abi_typelocation("b","HDfprintf","Import","Opaque","(()+104)").
abi_typelocation("b","HDfprintf","Import","Integer32","()+112").
abi_typelocation("b","HDfprintf","Import","Integer32","()+116").
abi_typelocation("b","HDfprintf","Import","Integer64","()+120").
abi_typelocation("b","HDfprintf","Import","Integer16","()+128").
abi_typelocation("b","HDfprintf","Import","Integer8","()+130").
abi_typelocation("b","HDfprintf","Import","Array[1:1]","()+131").
abi_typelocation("b","HDfprintf","Import","Integer8","()+131").
abi_typelocation("b","HDfprintf","Import","Integer64","()+144").
abi_typelocation("b","HDfprintf","Import","Empty","(()+152)").
abi_typelocation("b","HDfprintf","Import","Empty","(()+160)").
abi_typelocation("b","HDfprintf","Import","Opaque","(()+168)").
abi_typelocation("b","HDfprintf","Import","Void","(()+176)").
abi_typelocation("b","HDfprintf","Import","Integer64","()+184").
abi_typelocation("b","HDfprintf","Import","Integer32","()+192").
abi_typelocation("b","HDfprintf","Import","Array[20:20]","()+196").
abi_typelocation("b","HDfprintf","Import","Integer8","()+196").
abi_typelocation("b","HDfprintf","Import","Void","()").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Import","Integer32","()").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+8)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+16)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+24)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+32)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+40)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+48)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+56)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+64)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+72)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+80)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+88)").
abi_typelocation("b","HDfprintf","Import","Empty","(()+96)").
abi_typelocation("b","HDfprintf","Import","Opaque","(()+104)").
abi_typelocation("b","HDfprintf","Import","Integer32","()+112").
abi_typelocation("b","HDfprintf","Import","Integer32","()+116").
abi_typelocation("b","HDfprintf","Import","Integer64","()+120").
abi_typelocation("b","HDfprintf","Import","Integer16","()+128").
abi_typelocation("b","HDfprintf","Import","Integer8","()+130").
abi_typelocation("b","HDfprintf","Import","Array[1:1]","()+131").
abi_typelocation("b","HDfprintf","Import","Integer8","()+131").
abi_typelocation("b","HDfprintf","Import","Integer64","()+144").
abi_typelocation("b","HDfprintf","Import","Empty","(()+152)").
abi_typelocation("b","HDfprintf","Import","Empty","(()+160)").
abi_typelocation("b","HDfprintf","Import","Opaque","(()+168)").
abi_typelocation("b","HDfprintf","Import","Void","(()+176)").
abi_typelocation("b","HDfprintf","Import","Integer64","()+184").
abi_typelocation("b","HDfprintf","Import","Integer32","()+192").
abi_typelocation("b","HDfprintf","Import","Array[20:20]","()+196").
abi_typelocation("b","HDfprintf","Import","Integer8","()+196").
abi_typelocation("b","HDfprintf","Import","Void","()").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Import","Integer32","()").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+8)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+16)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+24)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+32)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+40)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+48)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+56)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+64)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+72)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+80)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+88)").
abi_typelocation("b","HDfprintf","Import","Empty","(()+96)").
abi_typelocation("b","HDfprintf","Import","Opaque","(()+104)").
abi_typelocation("b","HDfprintf","Import","Integer32","()+112").
abi_typelocation("b","HDfprintf","Import","Integer32","()+116").
abi_typelocation("b","HDfprintf","Import","Integer64","()+120").
abi_typelocation("b","HDfprintf","Import","Integer16","()+128").
abi_typelocation("b","HDfprintf","Import","Integer8","()+130").
abi_typelocation("b","HDfprintf","Import","Array[1:1]","()+131").
abi_typelocation("b","HDfprintf","Import","Integer8","()+131").
abi_typelocation("b","HDfprintf","Import","Integer64","()+144").
abi_typelocation("b","HDfprintf","Import","Empty","(()+152)").
abi_typelocation("b","HDfprintf","Import","Empty","(()+160)").
abi_typelocation("b","HDfprintf","Import","Opaque","(()+168)").
abi_typelocation("b","HDfprintf","Import","Void","(()+176)").
abi_typelocation("b","HDfprintf","Import","Integer64","()+184").
abi_typelocation("b","HDfprintf","Import","Integer32","()+192").
abi_typelocation("b","HDfprintf","Import","Array[20:20]","()+196").
abi_typelocation("b","HDfprintf","Import","Integer8","()+196").
abi_typelocation("b","HDfprintf","Import","Void","()").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Import","Integer32","%rdi").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Import","Integer32","()").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+8)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+16)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+24)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+32)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+40)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+48)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+56)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+64)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+72)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+80)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+88)").
abi_typelocation("b","HDfprintf","Import","Empty","(()+96)").
abi_typelocation("b","HDfprintf","Import","Opaque","(()+104)").
abi_typelocation("b","HDfprintf","Import","Integer32","()+112").
abi_typelocation("b","HDfprintf","Import","Integer32","()+116").
abi_typelocation("b","HDfprintf","Import","Integer64","()+120").
abi_typelocation("b","HDfprintf","Import","Integer16","()+128").
abi_typelocation("b","HDfprintf","Import","Integer8","()+130").
abi_typelocation("b","HDfprintf","Import","Array[1:1]","()+131").
abi_typelocation("b","HDfprintf","Import","Integer8","()+131").
abi_typelocation("b","HDfprintf","Import","Integer64","()+144").
abi_typelocation("b","HDfprintf","Import","Empty","(()+152)").
abi_typelocation("b","HDfprintf","Import","Empty","(()+160)").
abi_typelocation("b","HDfprintf","Import","Opaque","(()+168)").
abi_typelocation("b","HDfprintf","Import","Void","(()+176)").
abi_typelocation("b","HDfprintf","Import","Integer64","()+184").
abi_typelocation("b","HDfprintf","Import","Integer32","()+192").
abi_typelocation("b","HDfprintf","Import","Array[20:20]","()+196").
abi_typelocation("b","HDfprintf","Import","Integer8","()+196").
abi_typelocation("b","HDfprintf","Import","Void","()").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Import","Integer32","%rdi").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Import","Integer32","()").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+8)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+16)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+24)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+32)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+40)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+48)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+56)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+64)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+72)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+80)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+88)").
abi_typelocation("b","HDfprintf","Import","Empty","(()+96)").
abi_typelocation("b","HDfprintf","Import","Opaque","(()+104)").
abi_typelocation("b","HDfprintf","Import","Integer32","()+112").
abi_typelocation("b","HDfprintf","Import","Integer32","()+116").
abi_typelocation("b","HDfprintf","Import","Integer64","()+120").
abi_typelocation("b","HDfprintf","Import","Integer16","()+128").
abi_typelocation("b","HDfprintf","Import","Integer8","()+130").
abi_typelocation("b","HDfprintf","Import","Array[1:1]","()+131").
abi_typelocation("b","HDfprintf","Import","Integer8","()+131").
abi_typelocation("b","HDfprintf","Import","Integer64","()+144").
abi_typelocation("b","HDfprintf","Import","Empty","(()+152)").
abi_typelocation("b","HDfprintf","Import","Empty","(()+160)").
abi_typelocation("b","HDfprintf","Import","Opaque","(()+168)").
abi_typelocation("b","HDfprintf","Import","Void","(()+176)").
abi_typelocation("b","HDfprintf","Import","Integer64","()+184").
abi_typelocation("b","HDfprintf","Import","Integer32","()+192").
abi_typelocation("b","HDfprintf","Import","Array[20:20]","()+196").
abi_typelocation("b","HDfprintf","Import","Integer8","()+196").
abi_typelocation("b","HDfprintf","Import","Void","()").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Import","Integer32","()").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+8)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+16)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+24)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+32)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+40)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+48)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+56)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+64)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+72)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+80)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+88)").
abi_typelocation("b","HDfprintf","Import","Empty","(()+96)").
abi_typelocation("b","HDfprintf","Import","Opaque","(()+104)").
abi_typelocation("b","HDfprintf","Import","Integer32","()+112").
abi_typelocation("b","HDfprintf","Import","Integer32","()+116").
abi_typelocation("b","HDfprintf","Import","Integer64","()+120").
abi_typelocation("b","HDfprintf","Import","Integer16","()+128").
abi_typelocation("b","HDfprintf","Import","Integer8","()+130").
abi_typelocation("b","HDfprintf","Import","Array[1:1]","()+131").
abi_typelocation("b","HDfprintf","Import","Integer8","()+131").
abi_typelocation("b","HDfprintf","Import","Integer64","()+144").
abi_typelocation("b","HDfprintf","Import","Empty","(()+152)").
abi_typelocation("b","HDfprintf","Import","Empty","(()+160)").
abi_typelocation("b","HDfprintf","Import","Opaque","(()+168)").
abi_typelocation("b","HDfprintf","Import","Void","(()+176)").
abi_typelocation("b","HDfprintf","Import","Integer64","()+184").
abi_typelocation("b","HDfprintf","Import","Integer32","()+192").
abi_typelocation("b","HDfprintf","Import","Array[20:20]","()+196").
abi_typelocation("b","HDfprintf","Import","Integer8","()+196").
abi_typelocation("b","HDfprintf","Import","Void","()").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Import","Integer32","()").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+8)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+16)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+24)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+32)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+40)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+48)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+56)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+64)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+72)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+80)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+88)").
abi_typelocation("b","HDfprintf","Import","Empty","(()+96)").
abi_typelocation("b","HDfprintf","Import","Opaque","(()+104)").
abi_typelocation("b","HDfprintf","Import","Integer32","()+112").
abi_typelocation("b","HDfprintf","Import","Integer32","()+116").
abi_typelocation("b","HDfprintf","Import","Integer64","()+120").
abi_typelocation("b","HDfprintf","Import","Integer16","()+128").
abi_typelocation("b","HDfprintf","Import","Integer8","()+130").
abi_typelocation("b","HDfprintf","Import","Array[1:1]","()+131").
abi_typelocation("b","HDfprintf","Import","Integer8","()+131").
abi_typelocation("b","HDfprintf","Import","Integer64","()+144").
abi_typelocation("b","HDfprintf","Import","Empty","(()+152)").
abi_typelocation("b","HDfprintf","Import","Empty","(()+160)").
abi_typelocation("b","HDfprintf","Import","Opaque","(()+168)").
abi_typelocation("b","HDfprintf","Import","Void","(()+176)").
abi_typelocation("b","HDfprintf","Import","Integer64","()+184").
abi_typelocation("b","HDfprintf","Import","Integer32","()+192").
abi_typelocation("b","HDfprintf","Import","Array[20:20]","()+196").
abi_typelocation("b","HDfprintf","Import","Integer8","()+196").
abi_typelocation("b","HDfprintf","Import","Void","()").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Import","Integer32","()").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+8)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+16)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+24)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+32)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+40)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+48)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+56)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+64)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+72)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+80)").
abi_typelocation("b","HDfprintf","Import","Integer8","(()+88)").
abi_typelocation("b","HDfprintf","Import","Empty","(()+96)").
abi_typelocation("b","HDfprintf","Import","Opaque","(()+104)").
abi_typelocation("b","HDfprintf","Import","Integer32","()+112").
abi_typelocation("b","HDfprintf","Import","Integer32","()+116").
abi_typelocation("b","HDfprintf","Import","Integer64","()+120").
abi_typelocation("b","HDfprintf","Import","Integer16","()+128").
abi_typelocation("b","HDfprintf","Import","Integer8","()+130").
abi_typelocation("b","HDfprintf","Import","Array[1:1]","()+131").
abi_typelocation("b","HDfprintf","Import","Integer8","()+131").
abi_typelocation("b","HDfprintf","Import","Integer64","()+144").
abi_typelocation("b","HDfprintf","Import","Empty","(()+152)").
abi_typelocation("b","HDfprintf","Import","Empty","(()+160)").
abi_typelocation("b","HDfprintf","Import","Opaque","(()+168)").
abi_typelocation("b","HDfprintf","Import","Void","(()+176)").
abi_typelocation("b","HDfprintf","Import","Integer64","()+184").
abi_typelocation("b","HDfprintf","Import","Integer32","()+192").
abi_typelocation("b","HDfprintf","Import","Array[20:20]","()+196").
abi_typelocation("b","HDfprintf","Import","Integer8","()+196").
abi_typelocation("b","HDfprintf","Import","Void","()").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","H5Pget_fill_value","Import","Integer8","()").
abi_typelocation("b","H5Pget_virtual_dsetname","Export","Integer64","%rax").
abi_typelocation("b","H5Pget_virtual_filename","Export","Integer64","%rax").
abi_typelocation("b","H5Pset_elink_fapl","Import","Empty","%rax").
abi_typelocation("b","H5Pget_filter2","Import","Empty","none").
abi_typelocation("b","H5Pget_filter2","Import","Empty","none").
abi_typelocation("b","H5Pget_filter2","Import","Empty","none").
abi_typelocation("b","H5Pget_nfilters","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Import","Empty","none").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","H5Rget_name","Export","Integer8","(%rax)").
abi_typelocation("b","H5Sget_simple_extent_type","Import","Empty","none").
abi_typelocation("b","H5Screate_simple","Import","Empty","%rax").
abi_typelocation("b","H5Sis_simple","Import","Empty","none").
abi_typelocation("b","H5Sget_simple_extent_dims","Import","Empty","none").
abi_typelocation("b","H5Sget_simple_extent_ndims","Import","Empty","none").
abi_typelocation("b","H5Sget_simple_extent_npoints","Import","Empty","none").
abi_typelocation("b","H5Sclose","Import","Empty","none").
abi_typelocation("b","H5Sget_select_elem_pointlist","Import","Empty","none").
abi_typelocation("b","H5Sget_select_elem_npoints","Import","Empty","none").
abi_typelocation("b","H5Sget_select_type","Import","Empty","none").
abi_typelocation("b","H5Sget_select_bounds","Import","Empty","none").
abi_typelocation("b","H5Sget_select_npoints","Import","Empty","none").
abi_typelocation("b","H5SL_destroy","Import","Integer64","%rdi").
abi_typelocation("b","H5SL_search","Export","Integer64","%rax").
abi_typelocation("b","H5SL_insert","Import","Integer64","%rdi").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","H5Topen2","Import","Void","()").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","(framebase+8)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((framebase+8)+8)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((framebase+8)+16)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((framebase+8)+24)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((framebase+8)+32)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((framebase+8)+40)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((framebase+8)+48)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((framebase+8)+56)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((framebase+8)+64)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((framebase+8)+72)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((framebase+8)+80)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((framebase+8)+88)").
abi_typelocation("b","H5Tget_native_type","Import","Empty","((framebase+8)+96)").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","((framebase+8)+104)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((framebase+8)+104)+8)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((framebase+8)+104)+16)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((framebase+8)+104)+24)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((framebase+8)+104)+32)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((framebase+8)+104)+40)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((framebase+8)+104)+48)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((framebase+8)+104)+56)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((framebase+8)+104)+64)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((framebase+8)+104)+72)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((framebase+8)+104)+80)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((framebase+8)+104)+88)").
abi_typelocation("b","H5Tget_native_type","Import","Empty","(((framebase+8)+104)+96)").
abi_typelocation("b","H5Tget_native_type","Import","Opaque","(((framebase+8)+104)+104)").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","((framebase+8)+104)+112").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","((framebase+8)+104)+116").
abi_typelocation("b","H5Tget_native_type","Import","Integer64","((framebase+8)+104)+120").
abi_typelocation("b","H5Tget_native_type","Import","Integer16","((framebase+8)+104)+128").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((framebase+8)+104)+130").
abi_typelocation("b","H5Tget_native_type","Import","Array[1:1]","((framebase+8)+104)+131").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((framebase+8)+104)+131").
abi_typelocation("b","H5Tget_native_type","Import","Integer64","((framebase+8)+104)+144").
abi_typelocation("b","H5Tget_native_type","Import","Empty","(((framebase+8)+104)+152)").
abi_typelocation("b","H5Tget_native_type","Import","Empty","(((framebase+8)+104)+160)").
abi_typelocation("b","H5Tget_native_type","Import","Opaque","(((framebase+8)+104)+168)").
abi_typelocation("b","H5Tget_native_type","Import","Void","(((framebase+8)+104)+176)").
abi_typelocation("b","H5Tget_native_type","Import","Integer64","((framebase+8)+104)+184").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","((framebase+8)+104)+192").
abi_typelocation("b","H5Tget_native_type","Import","Array[20:20]","((framebase+8)+104)+196").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((framebase+8)+104)+196").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","(framebase+8)+112").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","(framebase+8)+116").
abi_typelocation("b","H5Tget_native_type","Import","Integer64","(framebase+8)+120").
abi_typelocation("b","H5Tget_native_type","Import","Integer16","(framebase+8)+128").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(framebase+8)+130").
abi_typelocation("b","H5Tget_native_type","Import","Array[1:1]","(framebase+8)+131").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(framebase+8)+131").
abi_typelocation("b","H5Tget_native_type","Import","Integer64","(framebase+8)+144").
abi_typelocation("b","H5Tget_native_type","Import","Empty","((framebase+8)+152)").
abi_typelocation("b","H5Tget_native_type","Import","Empty","((framebase+8)+160)").
abi_typelocation("b","H5Tget_native_type","Import","Opaque","((framebase+8)+168)").
abi_typelocation("b","H5Tget_native_type","Import","Void","((framebase+8)+176)").
abi_typelocation("b","H5Tget_native_type","Import","Integer64","(framebase+8)+184").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","(framebase+8)+192").
abi_typelocation("b","H5Tget_native_type","Import","Array[20:20]","(framebase+8)+196").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(framebase+8)+196").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","framebase+16").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","framebase+17").
abi_typelocation("b","H5Tget_native_type","Import","Array[288:18]","framebase+24").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","()").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","(+8)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((+8)+8)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((+8)+16)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((+8)+24)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((+8)+32)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((+8)+40)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((+8)+48)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((+8)+56)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((+8)+64)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((+8)+72)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((+8)+80)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((+8)+88)").
abi_typelocation("b","H5Tget_native_type","Import","Empty","((+8)+96)").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","((+8)+104)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((+8)+104)+8)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((+8)+104)+16)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((+8)+104)+24)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((+8)+104)+32)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((+8)+104)+40)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((+8)+104)+48)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((+8)+104)+56)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((+8)+104)+64)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((+8)+104)+72)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((+8)+104)+80)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((+8)+104)+88)").
abi_typelocation("b","H5Tget_native_type","Import","Empty","(((+8)+104)+96)").
abi_typelocation("b","H5Tget_native_type","Import","Opaque","(((+8)+104)+104)").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","((+8)+104)+112").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","((+8)+104)+116").
abi_typelocation("b","H5Tget_native_type","Import","Integer64","((+8)+104)+120").
abi_typelocation("b","H5Tget_native_type","Import","Integer16","((+8)+104)+128").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((+8)+104)+130").
abi_typelocation("b","H5Tget_native_type","Import","Array[1:1]","((+8)+104)+131").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((+8)+104)+131").
abi_typelocation("b","H5Tget_native_type","Import","Integer64","((+8)+104)+144").
abi_typelocation("b","H5Tget_native_type","Import","Empty","(((+8)+104)+152)").
abi_typelocation("b","H5Tget_native_type","Import","Empty","(((+8)+104)+160)").
abi_typelocation("b","H5Tget_native_type","Import","Opaque","(((+8)+104)+168)").
abi_typelocation("b","H5Tget_native_type","Import","Void","(((+8)+104)+176)").
abi_typelocation("b","H5Tget_native_type","Import","Integer64","((+8)+104)+184").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","((+8)+104)+192").
abi_typelocation("b","H5Tget_native_type","Import","Array[20:20]","((+8)+104)+196").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((+8)+104)+196").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","(+8)+112").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","(+8)+116").
abi_typelocation("b","H5Tget_native_type","Import","Integer64","(+8)+120").
abi_typelocation("b","H5Tget_native_type","Import","Integer16","(+8)+128").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(+8)+130").
abi_typelocation("b","H5Tget_native_type","Import","Array[1:1]","(+8)+131").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(+8)+131").
abi_typelocation("b","H5Tget_native_type","Import","Integer64","(+8)+144").
abi_typelocation("b","H5Tget_native_type","Import","Empty","((+8)+152)").
abi_typelocation("b","H5Tget_native_type","Import","Empty","((+8)+160)").
abi_typelocation("b","H5Tget_native_type","Import","Opaque","((+8)+168)").
abi_typelocation("b","H5Tget_native_type","Import","Void","((+8)+176)").
abi_typelocation("b","H5Tget_native_type","Import","Integer64","(+8)+184").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","(+8)+192").
abi_typelocation("b","H5Tget_native_type","Import","Array[20:20]","(+8)+196").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(+8)+196").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","((framebase+312))").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((framebase+312))+8)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((framebase+312))+16)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((framebase+312))+24)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((framebase+312))+32)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((framebase+312))+40)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((framebase+312))+48)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((framebase+312))+56)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((framebase+312))+64)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((framebase+312))+72)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((framebase+312))+80)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((framebase+312))+88)").
abi_typelocation("b","H5Tget_native_type","Import","Empty","(((framebase+312))+96)").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","(((framebase+312))+104)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((((framebase+312))+104)+8)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((((framebase+312))+104)+16)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((((framebase+312))+104)+24)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((((framebase+312))+104)+32)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((((framebase+312))+104)+40)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((((framebase+312))+104)+48)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((((framebase+312))+104)+56)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((((framebase+312))+104)+64)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((((framebase+312))+104)+72)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((((framebase+312))+104)+80)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((((framebase+312))+104)+88)").
abi_typelocation("b","H5Tget_native_type","Import","Empty","((((framebase+312))+104)+96)").
abi_typelocation("b","H5Tget_native_type","Import","Opaque","((((framebase+312))+104)+104)").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","(((framebase+312))+104)+112").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","(((framebase+312))+104)+116").
abi_typelocation("b","H5Tget_native_type","Import","Integer64","(((framebase+312))+104)+120").
abi_typelocation("b","H5Tget_native_type","Import","Integer16","(((framebase+312))+104)+128").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((framebase+312))+104)+130").
abi_typelocation("b","H5Tget_native_type","Import","Array[1:1]","(((framebase+312))+104)+131").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((framebase+312))+104)+131").
abi_typelocation("b","H5Tget_native_type","Import","Integer64","(((framebase+312))+104)+144").
abi_typelocation("b","H5Tget_native_type","Import","Empty","((((framebase+312))+104)+152)").
abi_typelocation("b","H5Tget_native_type","Import","Empty","((((framebase+312))+104)+160)").
abi_typelocation("b","H5Tget_native_type","Import","Opaque","((((framebase+312))+104)+168)").
abi_typelocation("b","H5Tget_native_type","Import","Void","((((framebase+312))+104)+176)").
abi_typelocation("b","H5Tget_native_type","Import","Integer64","(((framebase+312))+104)+184").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","(((framebase+312))+104)+192").
abi_typelocation("b","H5Tget_native_type","Import","Array[20:20]","(((framebase+312))+104)+196").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((framebase+312))+104)+196").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","((framebase+312))+112").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","((framebase+312))+116").
abi_typelocation("b","H5Tget_native_type","Import","Integer64","((framebase+312))+120").
abi_typelocation("b","H5Tget_native_type","Import","Integer16","((framebase+312))+128").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((framebase+312))+130").
abi_typelocation("b","H5Tget_native_type","Import","Array[1:1]","((framebase+312))+131").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((framebase+312))+131").
abi_typelocation("b","H5Tget_native_type","Import","Integer64","((framebase+312))+144").
abi_typelocation("b","H5Tget_native_type","Import","Empty","(((framebase+312))+152)").
abi_typelocation("b","H5Tget_native_type","Import","Empty","(((framebase+312))+160)").
abi_typelocation("b","H5Tget_native_type","Import","Opaque","(((framebase+312))+168)").
abi_typelocation("b","H5Tget_native_type","Import","Void","(((framebase+312))+176)").
abi_typelocation("b","H5Tget_native_type","Import","Integer64","((framebase+312))+184").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","((framebase+312))+192").
abi_typelocation("b","H5Tget_native_type","Import","Array[20:20]","((framebase+312))+196").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((framebase+312))+196").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","(((framebase+312)+8))").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((((framebase+312)+8))+8)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((((framebase+312)+8))+16)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((((framebase+312)+8))+24)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((((framebase+312)+8))+32)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((((framebase+312)+8))+40)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((((framebase+312)+8))+48)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((((framebase+312)+8))+56)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((((framebase+312)+8))+64)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((((framebase+312)+8))+72)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((((framebase+312)+8))+80)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((((framebase+312)+8))+88)").
abi_typelocation("b","H5Tget_native_type","Import","Empty","((((framebase+312)+8))+96)").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","((((framebase+312)+8))+104)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((((framebase+312)+8))+104)+8)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((((framebase+312)+8))+104)+16)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((((framebase+312)+8))+104)+24)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((((framebase+312)+8))+104)+32)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((((framebase+312)+8))+104)+40)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((((framebase+312)+8))+104)+48)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((((framebase+312)+8))+104)+56)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((((framebase+312)+8))+104)+64)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((((framebase+312)+8))+104)+72)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((((framebase+312)+8))+104)+80)").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((((framebase+312)+8))+104)+88)").
abi_typelocation("b","H5Tget_native_type","Import","Empty","(((((framebase+312)+8))+104)+96)").
abi_typelocation("b","H5Tget_native_type","Import","Opaque","(((((framebase+312)+8))+104)+104)").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","((((framebase+312)+8))+104)+112").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","((((framebase+312)+8))+104)+116").
abi_typelocation("b","H5Tget_native_type","Import","Integer64","((((framebase+312)+8))+104)+120").
abi_typelocation("b","H5Tget_native_type","Import","Integer16","((((framebase+312)+8))+104)+128").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((((framebase+312)+8))+104)+130").
abi_typelocation("b","H5Tget_native_type","Import","Array[1:1]","((((framebase+312)+8))+104)+131").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((((framebase+312)+8))+104)+131").
abi_typelocation("b","H5Tget_native_type","Import","Integer64","((((framebase+312)+8))+104)+144").
abi_typelocation("b","H5Tget_native_type","Import","Empty","(((((framebase+312)+8))+104)+152)").
abi_typelocation("b","H5Tget_native_type","Import","Empty","(((((framebase+312)+8))+104)+160)").
abi_typelocation("b","H5Tget_native_type","Import","Opaque","(((((framebase+312)+8))+104)+168)").
abi_typelocation("b","H5Tget_native_type","Import","Void","(((((framebase+312)+8))+104)+176)").
abi_typelocation("b","H5Tget_native_type","Import","Integer64","((((framebase+312)+8))+104)+184").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","((((framebase+312)+8))+104)+192").
abi_typelocation("b","H5Tget_native_type","Import","Array[20:20]","((((framebase+312)+8))+104)+196").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","((((framebase+312)+8))+104)+196").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","(((framebase+312)+8))+112").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","(((framebase+312)+8))+116").
abi_typelocation("b","H5Tget_native_type","Import","Integer64","(((framebase+312)+8))+120").
abi_typelocation("b","H5Tget_native_type","Import","Integer16","(((framebase+312)+8))+128").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((framebase+312)+8))+130").
abi_typelocation("b","H5Tget_native_type","Import","Array[1:1]","(((framebase+312)+8))+131").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((framebase+312)+8))+131").
abi_typelocation("b","H5Tget_native_type","Import","Integer64","(((framebase+312)+8))+144").
abi_typelocation("b","H5Tget_native_type","Import","Empty","((((framebase+312)+8))+152)").
abi_typelocation("b","H5Tget_native_type","Import","Empty","((((framebase+312)+8))+160)").
abi_typelocation("b","H5Tget_native_type","Import","Opaque","((((framebase+312)+8))+168)").
abi_typelocation("b","H5Tget_native_type","Import","Void","((((framebase+312)+8))+176)").
abi_typelocation("b","H5Tget_native_type","Import","Integer64","(((framebase+312)+8))+184").
abi_typelocation("b","H5Tget_native_type","Import","Integer32","(((framebase+312)+8))+192").
abi_typelocation("b","H5Tget_native_type","Import","Array[20:20]","(((framebase+312)+8))+196").
abi_typelocation("b","H5Tget_native_type","Import","Integer8","(((framebase+312)+8))+196").
abi_typelocation("b","H5Tget_native_type","Import","Opaque","(((framebase+312)+8)+8)").

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-11.2.0/openmpi-4.1.4-axm3au7q4x7g5kxocoyoq4tkxobmyio4/lib/libmpi.so.40.30.4
%----------------------------------------------------------------------------
