
%============================================================================
% Library Facts
%============================================================================

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-broadwell/gcc-11.2.0/hdf5-develop-1.10-tjwkmmotpw5klozeyj7gwuhzcjkz5omw/lib/libhdf5_tools.so
%----------------------------------------------------------------------------
abi_typelocation("a","ompi_mpi_comm_world","Import","Empty","none").
abi_typelocation("a","ompi_mpi_char","Import","Empty","none").
abi_typelocation("a","ompi_mpi_byte","Import","Empty","none").
abi_typelocation("a","H5T_IEEE_F32BE_g","Import","Empty","none").
abi_typelocation("a","H5T_IEEE_F32LE_g","Import","Empty","none").
abi_typelocation("a","H5T_IEEE_F64BE_g","Import","Empty","none").
abi_typelocation("a","H5T_IEEE_F64LE_g","Import","Empty","none").
abi_typelocation("a","H5T_STD_I8BE_g","Import","Empty","none").
abi_typelocation("a","H5T_STD_I8LE_g","Import","Empty","none").
abi_typelocation("a","H5T_STD_I16BE_g","Import","Empty","none").
abi_typelocation("a","H5T_STD_I16LE_g","Import","Empty","none").
abi_typelocation("a","H5T_STD_I32BE_g","Import","Empty","none").
abi_typelocation("a","H5T_STD_I32LE_g","Import","Empty","none").
abi_typelocation("a","H5T_STD_I64BE_g","Import","Empty","none").
abi_typelocation("a","H5T_STD_I64LE_g","Import","Empty","none").
abi_typelocation("a","H5T_STD_U8BE_g","Import","Empty","none").
abi_typelocation("a","H5T_STD_U8LE_g","Import","Empty","none").
abi_typelocation("a","H5T_STD_U16BE_g","Import","Empty","none").
abi_typelocation("a","H5T_STD_U16LE_g","Import","Empty","none").
abi_typelocation("a","H5T_STD_U32BE_g","Import","Empty","none").
abi_typelocation("a","H5T_STD_U32LE_g","Import","Empty","none").
abi_typelocation("a","H5T_STD_U64BE_g","Import","Empty","none").
abi_typelocation("a","H5T_STD_U64LE_g","Import","Empty","none").
abi_typelocation("a","H5T_STD_B8BE_g","Import","Empty","none").
abi_typelocation("a","H5T_STD_B8LE_g","Import","Empty","none").
abi_typelocation("a","H5T_STD_B16BE_g","Import","Empty","none").
abi_typelocation("a","H5T_STD_B16LE_g","Import","Empty","none").
abi_typelocation("a","H5T_STD_B32BE_g","Import","Empty","none").
abi_typelocation("a","H5T_STD_B32LE_g","Import","Empty","none").
abi_typelocation("a","H5T_STD_B64BE_g","Import","Empty","none").
abi_typelocation("a","H5T_STD_B64LE_g","Import","Empty","none").
abi_typelocation("a","H5Gclose","Import","Integer64","%rdi").
abi_typelocation("a","H5Gclose","Export","Integer32","%rax").
abi_typelocation("a","H5Gopen2","Import","Integer64","%rdi").
abi_typelocation("a","H5Gopen2","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Gopen2","Import","Integer64","%rdx").
abi_typelocation("a","H5Gopen2","Export","Integer64","%rax").
abi_typelocation("a","H5Tclose","Import","Integer64","%rdi").
abi_typelocation("a","H5Tclose","Export","Integer32","%rax").
abi_typelocation("a","H5Tequal","Import","Integer64","%rdi").
abi_typelocation("a","H5Tequal","Import","Integer64","%rsi").
abi_typelocation("a","H5Tequal","Export","Integer32","%rax").
abi_typelocation("a","H5Topen2","Import","Integer64","%rdi").
abi_typelocation("a","H5Topen2","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Topen2","Import","Integer64","%rdx").
abi_typelocation("a","H5Topen2","Export","Integer64","%rax").
abi_typelocation("a","H5Dclose","Import","Integer64","%rdi").
abi_typelocation("a","H5Dclose","Export","Integer32","%rax").
abi_typelocation("a","H5Dopen2","Import","Integer64","%rdi").
abi_typelocation("a","H5Dopen2","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Dopen2","Import","Integer64","%rdx").
abi_typelocation("a","H5Dopen2","Export","Integer64","%rax").
abi_typelocation("a","MPI_Finalize","Export","Integer32","%rax").
abi_typelocation("a","MPI_Probe","Import","Integer32","%rdi").
abi_typelocation("a","MPI_Probe","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Probe","Import","Empty","(%rdx)").
abi_typelocation("a","MPI_Probe","Import","Integer32","(%rcx)").
abi_typelocation("a","MPI_Probe","Import","Integer32","(%rcx)+4").
abi_typelocation("a","MPI_Probe","Import","Integer32","(%rcx)+8").
abi_typelocation("a","MPI_Probe","Import","Integer32","(%rcx)+12").
abi_typelocation("a","MPI_Probe","Import","Integer64","(%rcx)+16").
abi_typelocation("a","MPI_Probe","Export","Integer32","%rax").
abi_typelocation("a","MPI_Recv","Both","Void","(%rdi)").
abi_typelocation("a","MPI_Recv","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Recv","Import","Empty","(%rdx)").
abi_typelocation("a","MPI_Recv","Import","Integer32","%rcx").
abi_typelocation("a","MPI_Recv","Import","Integer32","%r8").
abi_typelocation("a","MPI_Recv","Import","Empty","(%r9)").
abi_typelocation("a","MPI_Recv","Import","Integer32","(framebase+8)").
abi_typelocation("a","MPI_Recv","Import","Integer32","(framebase+8)+4").
abi_typelocation("a","MPI_Recv","Import","Integer32","(framebase+8)+8").
abi_typelocation("a","MPI_Recv","Import","Integer32","(framebase+8)+12").
abi_typelocation("a","MPI_Recv","Import","Integer64","(framebase+8)+16").
abi_typelocation("a","MPI_Recv","Export","Integer32","%rax").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","%rdi").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Iprobe","Import","Empty","(%rdx)").
abi_typelocation("a","MPI_Iprobe","Both","Integer32","(%rcx)").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","(%r8)").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","(%r8)+4").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","(%r8)+8").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","(%r8)+12").
abi_typelocation("a","MPI_Iprobe","Import","Integer64","(%r8)+16").
abi_typelocation("a","MPI_Iprobe","Export","Integer32","%rax").
abi_typelocation("a","H5Lunpack_elink_val","Import","Integer64","%rsi").
abi_typelocation("a","H5Lunpack_elink_val","Both","Integer32","(%rdx)").
abi_typelocation("a","H5Lunpack_elink_val","Both","Integer8","((%rcx))").
abi_typelocation("a","H5Lunpack_elink_val","Both","Integer8","((%r8))").
abi_typelocation("a","H5Lunpack_elink_val","Export","Integer32","%rax").
abi_typelocation("a","H5Fclose","Import","Integer64","%rdi").
abi_typelocation("a","H5Fclose","Export","Integer32","%rax").
abi_typelocation("a","H5Eset_auto1","Import","Void","(%rdi)").
abi_typelocation("a","H5Eset_auto1","Both","Void","(%rsi)").
abi_typelocation("a","H5Eset_auto1","Export","Integer32","%rax").
abi_typelocation("a","H5Eget_auto1","Both","Void","((%rdi))").
abi_typelocation("a","H5Eget_auto1","Both","Void","((%rsi))").
abi_typelocation("a","H5Eget_auto1","Export","Integer32","%rax").
abi_typelocation("a","H5Eset_auto2","Import","Integer64","%rdi").
abi_typelocation("a","H5Eset_auto2","Import","Void","(%rsi)").
abi_typelocation("a","H5Eset_auto2","Both","Void","(%rdx)").
abi_typelocation("a","H5Eset_auto2","Export","Integer32","%rax").
abi_typelocation("a","H5Eget_auto2","Import","Integer64","%rdi").
abi_typelocation("a","H5Eget_auto2","Both","Void","((%rsi))").
abi_typelocation("a","H5Eget_auto2","Both","Void","((%rdx))").
abi_typelocation("a","H5Eget_auto2","Export","Integer32","%rax").
abi_typelocation("a","H5Eauto_is_v2","Import","Integer64","%rdi").
abi_typelocation("a","H5Eauto_is_v2","Both","Integer32","(%rsi)").
abi_typelocation("a","H5Eauto_is_v2","Export","Integer32","%rax").
abi_typelocation("a","MPI_Abort","Import","Empty","(%rdi)").
abi_typelocation("a","MPI_Abort","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Abort","Export","Integer32","%rax").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","%rdi").
abi_typelocation("a","H5Oget_info_by_name2","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+8").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer32","(%rdx)+16").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer32","(%rdx)+20").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+24").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+32").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+40").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+48").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+56").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer32","(%rdx)+64").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer32","(%rdx)+68").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer32","(%rdx)+72").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer32","(%rdx)+76").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+80").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+88").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+96").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+104").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+112").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+120").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+128").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+136").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+144").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","(%rdx)+152").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer32","%rcx").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer64","%r8").
abi_typelocation("a","H5Oget_info_by_name2","Export","Integer32","%rax").
abi_typelocation("a","H5Lget_info","Import","Integer64","%rdi").
abi_typelocation("a","H5Lget_info","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Lget_info","Import","Integer32","(%rdx)").
abi_typelocation("a","H5Lget_info","Import","Integer8","(%rdx)+4").
abi_typelocation("a","H5Lget_info","Import","Integer64","(%rdx)+8").
abi_typelocation("a","H5Lget_info","Import","Integer32","(%rdx)+16").
abi_typelocation("a","H5Lget_info","Import","Union","(%rdx)+24").
abi_typelocation("a","H5Lget_info","Import","Integer64","%rcx").
abi_typelocation("a","H5Lget_info","Export","Integer32","%rax").
abi_typelocation("a","H5Lexists","Import","Integer64","%rdi").
abi_typelocation("a","H5Lexists","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Lexists","Import","Integer64","%rdx").
abi_typelocation("a","H5Lexists","Export","Integer32","%rax").
abi_typelocation("a","H5Epush2","Import","Integer64","%rdi").
abi_typelocation("a","H5Epush2","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Epush2","Both","Integer8","(%rdx)").
abi_typelocation("a","H5Epush2","Import","Integer32","%rcx").
abi_typelocation("a","H5Epush2","Import","Integer64","%r8").
abi_typelocation("a","H5Epush2","Import","Integer64","%r9").
abi_typelocation("a","H5Epush2","Import","Integer64","framebase+8").
abi_typelocation("a","H5Epush2","Both","Integer8","(framebase+16)").
abi_typelocation("a","H5Epush2","Export","Integer32","%rax").
abi_typelocation("a","MPI_Send","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Send","Import","Empty","(%rdx)").
abi_typelocation("a","MPI_Send","Import","Integer32","%rcx").
abi_typelocation("a","MPI_Send","Import","Integer32","%r8").
abi_typelocation("a","MPI_Send","Import","Empty","(%r9)").
abi_typelocation("a","MPI_Send","Export","Integer32","%rax").
abi_typelocation("a","H5Tenum_nameof","Import","Integer64","%rdi").
abi_typelocation("a","H5Tget_member_offset","Export","Integer64","%rax").
abi_typelocation("a","H5Tconvert","Import","Integer64","%rdi").
abi_typelocation("a","H5Tget_size","Export","Integer64","%rax").
abi_typelocation("a","H5Aget_name","Import","Integer64","%rdi").
abi_typelocation("a","H5Aget_name","Export","Integer64","%rax").
abi_typelocation("a","H5Oget_info2","Import","Integer32","%rdi").
abi_typelocation("a","H5Eset_auto1","Both","Void","(%rdi)").
abi_typelocation("a","H5Eset_auto2","Both","Void","(%rdi)").
abi_typelocation("a","H5Dvlen_reclaim","Both","Void","(%rdi)").
abi_typelocation("a","H5Aread","Both","Void","(%rdi)").
abi_typelocation("a","H5Sget_simple_extent_dims","Export","Integer32","%rax").
abi_typelocation("a","H5Tget_size","Export","Integer64","%rax").
abi_typelocation("a","H5Epush2","Import","Integer32","%rdi").
abi_typelocation("a","H5Tget_size","Import","Empty","none").
abi_typelocation("a","H5Epush2","Import","Empty","none").
abi_typelocation("a","H5Epush2","Import","Integer32","%rdi").
abi_typelocation("a","H5Epush2","Import","Empty","none").
abi_typelocation("a","H5Epush2","Import","Empty","none").
abi_typelocation("a","H5Epush2","Import","Empty","none").
abi_typelocation("a","H5Tget_native_type","Import","Empty","none").
abi_typelocation("a","H5Tget_native_type","Import","Empty","none").
abi_typelocation("a","H5Tclose","Import","Empty","none").
abi_typelocation("a","H5Tequal","Import","Empty","none").
abi_typelocation("a","H5Tequal","Import","Empty","none").
abi_typelocation("a","H5Tequal","Export","Integer64","%rax").
abi_typelocation("a","H5Tget_class","Import","Empty","none").
abi_typelocation("a","H5Sget_simple_extent_ndims","Export","Integer32","%rax").
abi_typelocation("a","H5Sget_simple_extent_dims","Export","Integer32","%rax").
abi_typelocation("a","H5Dread","Both","Void","(%rdi)").
abi_typelocation("a","H5Screate_simple","Import","Integer32","%rdi").
abi_typelocation("a","H5Tget_array_dims2","Export","Integer32","%rax").
abi_typelocation("a","H5Tget_array_ndims","Export","Integer32","%rax").
abi_typelocation("a","H5Tget_nmembers","Export","Integer32","%rax").
abi_typelocation("a","H5Eset_auto1","Both","Void","(%rdi)").
abi_typelocation("a","MPI_Finalized","Export","Integer32","%rax").
abi_typelocation("a","MPI_Initialized","Export","Integer32","%rax").
abi_typelocation("a","H5Eset_auto2","Both","Void","(%rdi)").
abi_typelocation("a","H5Oget_comment","Import","Array","%rdi").
abi_typelocation("a","H5Oget_comment","Import","Integer32","%rdi").
abi_typelocation("a","H5Sis_regular_hyperslab","Import","Integer32","%rax").
abi_typelocation("a","H5Sis_regular_hyperslab","Import","Integer32","%rax+4").
abi_typelocation("a","H5Sis_regular_hyperslab","Import","Integer32","%rax+8").
abi_typelocation("a","H5Sis_regular_hyperslab","Import","Integer32","%rax+12").
abi_typelocation("a","H5Sis_regular_hyperslab","Import","Integer64","%rax+16").
abi_typelocation("a","H5Pget_virtual_dsetname","Import","Array","%rdi").
abi_typelocation("a","H5Pget_virtual_dsetname","Import","Integer32","%rdi").
abi_typelocation("a","H5Pget_virtual_dsetname","Import","Array","%rsi").
abi_typelocation("a","H5Pget_virtual_dsetname","Import","Integer32","%rsi").
abi_typelocation("a","H5Pget_virtual_filename","Import","Array","%rdi").
abi_typelocation("a","H5Pget_virtual_filename","Import","Integer32","%rdi").
abi_typelocation("a","H5Pget_virtual_filename","Import","Array","%rsi").
abi_typelocation("a","H5Pget_virtual_filename","Import","Integer32","%rsi").
abi_typelocation("a","H5Pget_virtual_srcspace","Import","Array","%rdi").
abi_typelocation("a","H5Pget_virtual_srcspace","Import","Integer32","%rdi").
abi_typelocation("a","H5Pget_virtual_vspace","Import","Array","%rdi").
abi_typelocation("a","H5Pget_virtual_vspace","Import","Integer32","%rdi").
abi_typelocation("a","H5Pget_external","Import","Array","%rdi").
abi_typelocation("a","H5Pget_external","Import","Integer32","%rdi").
abi_typelocation("a","H5Pget_filter2","Import","Array","%rdi").
abi_typelocation("a","H5Pget_filter2","Import","Integer32","%rdi").
abi_typelocation("a","H5Tconvert","Import","Array","%rdi").
abi_typelocation("a","H5Tconvert","Import","Integer32","%rdi").
abi_typelocation("a","H5Tset_order","Both","Integer8","(%rdi)").
abi_typelocation("a","H5Tset_size","Import","Array","%rdi").
abi_typelocation("a","H5Tset_size","Import","Integer32","%rdi").
abi_typelocation("a","H5Tis_variable_str","Import","Integer32","%rax").
abi_typelocation("a","H5Tis_variable_str","Import","Integer32","%rax+4").
abi_typelocation("a","H5Tis_variable_str","Import","Integer32","%rax+8").
abi_typelocation("a","H5Tis_variable_str","Import","Integer32","%rax+12").
abi_typelocation("a","H5Tis_variable_str","Import","Integer64","%rax+16").
abi_typelocation("a","H5Tget_precision","Import","Array","%rax").
abi_typelocation("a","H5Tget_precision","Import","Integer32","%rax").
abi_typelocation("a","H5Tget_order","Export","Integer8","(%rax)").
abi_typelocation("a","H5Tequal","Import","Integer32","%rax").
abi_typelocation("a","H5Tequal","Import","Integer32","%rax+4").
abi_typelocation("a","H5Tequal","Import","Integer32","%rax+8").
abi_typelocation("a","H5Tequal","Import","Integer32","%rax+12").
abi_typelocation("a","H5Tequal","Import","Integer64","%rax+16").
abi_typelocation("a","H5Tcommitted","Import","Integer32","%rax").
abi_typelocation("a","H5Tcommitted","Import","Integer32","%rax+4").
abi_typelocation("a","H5Tcommitted","Import","Integer32","%rax+8").
abi_typelocation("a","H5Tcommitted","Import","Integer32","%rax+12").
abi_typelocation("a","H5Tcommitted","Import","Integer64","%rax+16").
abi_typelocation("a","H5Sis_simple","Import","Integer32","%rax").
abi_typelocation("a","H5Sis_simple","Import","Integer32","%rax+4").
abi_typelocation("a","H5Sis_simple","Import","Integer32","%rax+8").
abi_typelocation("a","H5Sis_simple","Import","Integer32","%rax+12").
abi_typelocation("a","H5Sis_simple","Import","Integer64","%rax+16").
abi_typelocation("a","H5Sselect_hyperslab","Import","Integer64","()").
abi_typelocation("a","H5Sselect_hyperslab","Import","Integer32","+8").
abi_typelocation("a","H5Tget_native_type","Import","Opaque","(unknown)").
abi_typelocation("a","H5Tget_size","Import","Array","%rax").
abi_typelocation("a","H5Tget_size","Import","Integer32","%rax").
abi_typelocation("a","H5Zfilter_avail","Export","Integer64","%rax").
abi_typelocation("a","H5Pget_filter2","Import","Integer16","(%rdi)").
abi_typelocation("a","H5Pget_filter2","Import","Integer16","(%rdi)+2").
abi_typelocation("a","H5Pget_filter2","Import","Integer32","(%rdi)+4").
abi_typelocation("a","H5Pget_filter2","Import","Union","(%rdi)+8").
abi_typelocation("a","H5Pget_filter2","Import","Integer32","(%rdi)+24").
abi_typelocation("a","H5Pget_filter2","Import","Integer32","%rsi").
abi_typelocation("a","H5Epush2","Import","Integer16","(%rdi)").
abi_typelocation("a","H5Epush2","Import","Integer16","(%rdi)+2").
abi_typelocation("a","H5Epush2","Import","Integer32","(%rdi)+4").
abi_typelocation("a","H5Epush2","Import","Union","(%rdi)+8").
abi_typelocation("a","H5Epush2","Import","Integer32","(%rdi)+24").
abi_typelocation("a","H5Epush2","Import","Integer32","%rsi").
abi_typelocation("a","H5Epush2","Import","Integer16","(%rdx)").
abi_typelocation("a","H5Epush2","Import","Integer16","(%rdx)+2").
abi_typelocation("a","H5Epush2","Import","Integer32","(%rdx)+4").
abi_typelocation("a","H5Epush2","Import","Union","(%rdx)+8").
abi_typelocation("a","H5Epush2","Import","Integer32","(%rdx)+24").
abi_typelocation("a","H5Epush2","Import","Integer16","(%rcx)").
abi_typelocation("a","H5Epush2","Import","Integer16","(%rcx)+2").
abi_typelocation("a","H5Epush2","Import","Integer32","(%rcx)+4").
abi_typelocation("a","H5Epush2","Import","Union","(%rcx)+8").
abi_typelocation("a","H5Epush2","Import","Integer32","(%rcx)+24").
abi_typelocation("a","H5Epush2","Import","Integer16","(%r8)").
abi_typelocation("a","H5Epush2","Import","Integer16","(%r8)+2").
abi_typelocation("a","H5Epush2","Import","Integer32","(%r8)+4").
abi_typelocation("a","H5Epush2","Import","Union","(%r8)+8").
abi_typelocation("a","H5Epush2","Import","Integer32","(%r8)+24").
abi_typelocation("a","H5Pget_nfilters","Import","Integer16","(%rdi)").
abi_typelocation("a","H5Pget_nfilters","Import","Integer16","(%rdi)+2").
abi_typelocation("a","H5Pget_nfilters","Import","Integer32","(%rdi)+4").
abi_typelocation("a","H5Pget_nfilters","Import","Union","(%rdi)+8").
abi_typelocation("a","H5Pget_nfilters","Import","Integer32","(%rdi)+24").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer32","%rdi").
abi_typelocation("a","H5Rget_name","Both","Void","(%rdi)").
abi_typelocation("a","H5Tenum_nameof","Both","Void","(%rdi)").
abi_typelocation("a","H5Tget_member_name","Export","Void","(%rax)").
abi_typelocation("a","H5Eget_auto1","Import","Array","None").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer32","%rdi").
abi_typelocation("a","H5Oget_info2","Import","Integer32","%rdi").
abi_typelocation("a","H5Epush2","Import","Integer32","%rdi").
abi_typelocation("a","H5Aiterate_by_name","Both","Void","(%rdi)").
abi_typelocation("a","H5Lunpack_elink_val","Import","Integer64","%rdi").
abi_typelocation("a","H5Lget_val","Both","Void","(%rdi)").
abi_typelocation("a","H5Lget_val","Import","Integer64","%rsi").
abi_typelocation("a","H5Literate_by_name","Both","Void","(%rdi)").
abi_typelocation("a","H5Lvisit_by_name","Both","Void","(%rdi)").
abi_typelocation("a","H5Epush2","Import","Integer32","%rdi").
abi_typelocation("a","H5Oget_info2","Import","Integer32","%rdi").
abi_typelocation("a","H5Oget_info_by_name2","Import","Integer32","%rdi").

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-broadwell/gcc-11.2.0/hdf5-develop-1.10-ggcrc3uzecorkr3xptu6h6vrlq42qhzc/lib/libhdf5.so.103.3.2
%----------------------------------------------------------------------------
abi_typelocation("b","H5P_CLS_LINK_ACCESS_ID_g","Import","Integer16","var").
abi_typelocation("b","H5Eget_auto2","Import","Integer64","%rdi").
abi_typelocation("b","H5Eget_auto2","Both","Void","((%rsi))").
abi_typelocation("b","H5Eget_auto2","Both","Void","((%rdx))").
abi_typelocation("b","H5Eget_auto2","Export","Integer32","%rax").
abi_typelocation("b","H5free_memory","Both","Void","(%rdi)").
abi_typelocation("b","H5free_memory","Export","Integer32","%rax").
abi_typelocation("b","H5close","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5Aiterate_by_name","Export","Integer64","framebase+8").
abi_typelocation("b","H5Aiterate_by_name","Export","Integer64","framebase+16").
abi_typelocation("b","H5Aiterate_by_name","Export","Integer64","framebase+24").
abi_typelocation("b","H5Aiterate_by_name","Export","Integer64","framebase+32").
abi_typelocation("b","H5Aiterate_by_name","Export","Integer64","framebase+40").
abi_typelocation("b","H5Aiterate_by_name","Export","Integer64","framebase+48").
abi_typelocation("b","H5Aiterate_by_name","Export","Integer64","framebase+56").
abi_typelocation("b","H5Aiterate_by_name","Import","Void","()").
abi_typelocation("b","H5Aiterate_by_name","Import","Empty","(%rdi)").
abi_typelocation("b","H5Aopen_by_idx","Export","Integer64","framebase+8").
abi_typelocation("b","H5Aopen_by_idx","Export","Integer64","framebase+16").
abi_typelocation("b","H5Aopen_by_idx","Export","Integer64","framebase+24").
abi_typelocation("b","H5Aopen_by_idx","Export","Integer64","framebase+32").
abi_typelocation("b","H5Aopen_by_idx","Export","Integer64","framebase+40").
abi_typelocation("b","H5Aopen_by_idx","Export","Integer64","framebase+48").
abi_typelocation("b","H5Aopen_by_idx","Export","Integer64","framebase+56").
abi_typelocation("b","H5Aopen_by_idx","Import","Void","()").
abi_typelocation("b","H5SL_insert","Import","Void","()").
abi_typelocation("b","H5SL_search","Import","Void","()").
abi_typelocation("b","H5Dvlen_reclaim","Import","Integer8","()").
abi_typelocation("b","H5Dread","Import","Integer8","()").
abi_typelocation("b","H5Eset_auto1","Export","Integer32","%rax").
abi_typelocation("b","H5Eget_auto1","Export","Integer32","%rax").
abi_typelocation("b","H5Eauto_is_v2","Import","Function","%rdi").
abi_typelocation("b","H5Pset_fapl_mpio","Import","Empty","none").
abi_typelocation("b","H5Tconvert","Import","Integer8","%rdi").
abi_typelocation("b","H5Tconvert","Import","Integer64","%rsi").
abi_typelocation("b","H5Tconvert","Import","Integer64","%rdx").
abi_typelocation("b","H5Eset_auto1","Import","Integer64","%rdi").
abi_typelocation("b","H5Eset_auto2","Import","Integer64","%rdi").
abi_typelocation("b","H5Epush2","Import","Integer8","%rdi").
abi_typelocation("b","H5Epush2","Import","Empty","(%rax)").
abi_typelocation("b","H5open","Import","Empty","(%rax)").
abi_typelocation("b","H5Pset_fapl_stdio","Import","Empty","(%rax)").
abi_typelocation("b","H5Eauto_is_v2","Import","Empty","(%rdi)").
abi_typelocation("b","H5Pget_fill_value","Import","Integer8","()").
abi_typelocation("b","H5Pget_external","Import","Function","%rdi").
abi_typelocation("b","H5Pget_virtual_dsetname","Export","Integer64","%rax").
abi_typelocation("b","H5Pget_virtual_filename","Export","Integer64","%rax").
abi_typelocation("b","H5Pset_elink_fapl","Import","Empty","%rax").
abi_typelocation("b","H5Pget_filter2","Export","Integer16","%rdi").
abi_typelocation("b","H5Pget_filter2","Export","Integer16","%rdi").
abi_typelocation("b","H5Pget_filter2","Export","Integer32","%rdi").
abi_typelocation("b","H5Pget_filter2","Import","Array[8:8]","%rsi").
abi_typelocation("b","H5Pget_filter2","Import","Integer8","%rsi").
abi_typelocation("b","H5Pget_nfilters","Export","Integer16","%rdi").
abi_typelocation("b","H5Pget_nfilters","Export","Integer16","%rdi").
abi_typelocation("b","H5Pget_nfilters","Export","Integer32","%rdi").
abi_typelocation("b","H5Pget_nfilters","Import","Array[8:8]","%rsi").
abi_typelocation("b","H5Pget_nfilters","Import","Integer8","%rsi").
abi_typelocation("b","H5Pget_nfilters","Export","Integer32","%rax").
abi_typelocation("b","H5SL_destroy","Import","Function","%rdi").
abi_typelocation("b","H5Rget_name","Export","Integer8","(%rax)").
abi_typelocation("b","H5Sget_select_type","Import","Empty","none").
abi_typelocation("b","H5Sget_select_bounds","Import","Empty","none").
abi_typelocation("b","H5Sget_select_npoints","Import","Empty","none").
abi_typelocation("b","H5Sget_select_npoints","Export","Void","()").
abi_typelocation("b","H5SL_destroy","Import","Integer64","%rsi").
abi_typelocation("b","H5SL_search","Export","Integer64","%rax").
abi_typelocation("b","H5SL_insert","Import","Integer64","%rdi").
abi_typelocation("b","H5Tget_array_dims2","Import","Empty","none").
abi_typelocation("b","H5Tget_array_ndims","Import","Empty","none").
abi_typelocation("b","H5Tget_member_type","Import","Empty","(%rdi)").
abi_typelocation("b","H5Tget_member_type","Import","Empty","(%rax)").
abi_typelocation("b","H5Tget_member_offset","Import","Empty","(%rdi)").

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-broadwell/gcc-11.2.0/openmpi-4.1.4-badmtlyk6tcxb6ff3jyiqdj6ksxod5yy/lib/libmpi.so.40.30.4
%----------------------------------------------------------------------------
