
%============================================================================
% Library Facts
%============================================================================

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-11.2.0/hdf5-1.8.22-hz7dlfrtyuzt35xwumavpy2jdh7mpxv6/lib/libhdf5.so.10
%----------------------------------------------------------------------------
abi_typelocation("a","ompi_mpi_comm_self","Import","Empty","none").
abi_typelocation("a","MPI_Comm_free_keyval","Both","Integer32","(%rdi)").
abi_typelocation("a","MPI_Comm_free_keyval","Export","Integer32","%rax").
abi_typelocation("a","MPI_Comm_set_attr","Import","Empty","(%rdi)").
abi_typelocation("a","MPI_Comm_set_attr","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Comm_set_attr","Both","Void","(%rdx)").
abi_typelocation("a","MPI_Comm_set_attr","Export","Integer32","%rax").
abi_typelocation("a","MPI_Error_string","Import","Integer32","%rdi").
abi_typelocation("a","MPI_Error_string","Both","Integer8","(%rsi)").
abi_typelocation("a","MPI_Error_string","Both","Integer32","(%rdx)").
abi_typelocation("a","MPI_Error_string","Export","Integer32","%rax").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Import","Empty","(%rdi)").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Import","Integer32","%rsi").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Both","Void","(%rdx)").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Both","Void","(%rcx)").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Both","Void","(%r8)").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Both","Integer32","(%r9)").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Export","Integer32","%rax").
abi_typelocation("a","MPI_Comm_create_keyval","Both","Integer32","(%rdx)").
abi_typelocation("a","MPI_Comm_create_keyval","Both","Void","(%rcx)").
abi_typelocation("a","MPI_Comm_create_keyval","Export","Integer32","%rax").
abi_typelocation("a","MPI_Finalized","Both","Integer32","(%rdi)").
abi_typelocation("a","MPI_Finalized","Export","Integer32","%rax").
abi_typelocation("a","MPI_Initialized","Both","Integer32","(%rdi)").
abi_typelocation("a","MPI_Initialized","Export","Integer32","%rax").
abi_typelocation("a","MPI_Info_free","Export","Integer32","%rax").
abi_typelocation("a","MPI_Comm_free","Export","Integer32","%rax").
abi_typelocation("a","MPI_Info_dup","Export","Integer32","%rax").
abi_typelocation("a","MPI_Error_string","Import","Integer32","%rdi").
abi_typelocation("a","MPI_Error_string","Both","Integer8","(%rsi)").
abi_typelocation("a","MPI_Error_string","Export","Integer32","%rax").
abi_typelocation("a","MPI_Comm_dup","Export","Integer32","%rax").
abi_typelocation("a","MPI_File_read_at","Import","Empty","(%rdi)").
abi_typelocation("a","MPI_File_read_at_all","Import","Empty","(%rdi)").
abi_typelocation("a","MPI_File_write_at","Import","Empty","(%rdi)").
abi_typelocation("a","MPI_File_write_at_all","Import","Empty","(%rdi)").
abi_typelocation("a","MPI_File_set_view","Import","Empty","(%rdi)").
abi_typelocation("a","MPI_Error_string","Import","Integer8","%rdi").
abi_typelocation("a","MPI_File_set_size","Import","Empty","(%rdi)").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Import","Empty","(%rdi)").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Import","Integer32","%rsi").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Both","Void","(%rdx)").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Both","Void","(%rcx)").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Both","Void","(%r8)").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Both","Integer32","(%r9)").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Export","Integer32","%rax").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Import","Empty","(%rdi)").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Import","Integer32","%rsi").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Both","Void","(%rdx)").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Both","Void","(%rcx)").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Both","Void","(%r8)").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Both","Integer32","(%r9)").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Export","Integer32","%rax").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Import","Empty","(%rdi)").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Import","Integer32","%rsi").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Both","Void","(%rdx)").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Both","Void","(%rcx)").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Both","Void","(%r8)").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Both","Integer32","(%r9)").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Export","Integer32","%rax").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Import","Empty","(%rdi)").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Import","Integer32","%rsi").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Both","Void","(%rdx)").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Both","Void","(%rcx)").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Both","Void","(%r8)").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Both","Integer32","(%r9)").
abi_typelocation("a","OMPI_C_MPI_COMM_NULL_COPY_FN","Export","Integer32","%rax").
abi_typelocation("a","MPI_Error_string","Import","Integer64","%rdi").
abi_typelocation("a","compress2","Import","Integer32","%rdi").
abi_typelocation("a","compress2","Export","Integer32","%rax").
abi_typelocation("a","inflateEnd","Export","Integer32","%rax").
abi_typelocation("a","inflate","Import","Integer32","%rdi").
abi_typelocation("a","inflate","Export","Integer32","%rax").
abi_typelocation("a","inflateInit_","Import","Integer32","%rdi").
abi_typelocation("a","inflateInit_","Export","Integer32","%rax").

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-11.2.0/zlib-1.2.12-luwgiwun44dt7hmxv4ki6xjnxyucze7f/lib/libz.so.1.2.12
%----------------------------------------------------------------------------
abi_typelocation("b","compress2","Import","Integer8","%rdi").
abi_typelocation("b","compress2","Import","Integer64","%rsi").
abi_typelocation("b","compress2","Export","Integer64","%rax").
abi_typelocation("b","inflateEnd","Export","Integer64","%rax").
abi_typelocation("b","inflate","Import","Integer64","%rdi").
abi_typelocation("b","inflate","Export","Integer64","%rax").
abi_typelocation("b","inflateInit_","Import","Integer64","%rdi").
abi_typelocation("b","inflateInit_","Export","Integer64","%rax").
abi_typelocation("b","inflateEnd","Export","Integer8","%rax").
abi_typelocation("b","inflate","Import","Integer8","%rdi").
abi_typelocation("b","inflate","Export","Integer8","%rax").

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-11.2.0/openmpi-4.1.4-axm3au7q4x7g5kxocoyoq4tkxobmyio4/lib/libmpi.so.40.30.4
%----------------------------------------------------------------------------
