
%============================================================================
% Library Facts
%============================================================================

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-haswell/gcc-11.2.0/hdf5-1.10.1-twpl2txfqxh5mhjmpcwq4buir5wz7iip/lib/libhdf5_tools.so.1.10.1
%----------------------------------------------------------------------------
abi_typelocation("a","ompi_mpi_comm_world","Import","Empty","none").
abi_typelocation("a","ompi_mpi_char","Import","Empty","none").
abi_typelocation("a","ompi_mpi_byte","Import","Empty","none").
abi_typelocation("a","H5Gclose","Import","Integer64","%rdi").
abi_typelocation("a","H5Gclose","Export","Integer32","%rax").
abi_typelocation("a","H5Gopen2","Import","Integer64","%rdi").
abi_typelocation("a","H5Gopen2","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Gopen2","Import","Integer64","%rdx").
abi_typelocation("a","H5Gopen2","Export","Integer64","%rax").
abi_typelocation("a","H5Tclose","Import","Integer64","%rdi").
abi_typelocation("a","H5Tclose","Export","Integer32","%rax").
abi_typelocation("a","H5Tequal","Import","Integer64","%rdi").
abi_typelocation("a","H5Tequal","Import","Integer64","%rsi").
abi_typelocation("a","H5Tequal","Export","Integer32","%rax").
abi_typelocation("a","H5Topen2","Import","Integer64","%rdi").
abi_typelocation("a","H5Topen2","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Topen2","Import","Integer64","%rdx").
abi_typelocation("a","H5Topen2","Export","Integer64","%rax").
abi_typelocation("a","H5Dclose","Import","Integer64","%rdi").
abi_typelocation("a","H5Dclose","Export","Integer32","%rax").
abi_typelocation("a","H5Dopen2","Import","Integer64","%rdi").
abi_typelocation("a","H5Dopen2","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Dopen2","Import","Integer64","%rdx").
abi_typelocation("a","H5Dopen2","Export","Integer64","%rax").
abi_typelocation("a","MPI_Finalize","Export","Integer32","%rax").
abi_typelocation("a","MPI_Probe","Import","Integer32","%rdi").
abi_typelocation("a","MPI_Probe","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Probe","Import","Empty","(%rdx)").
abi_typelocation("a","MPI_Probe","Import","Integer32","(%rcx)").
abi_typelocation("a","MPI_Probe","Import","Integer32","(%rcx)+4").
abi_typelocation("a","MPI_Probe","Import","Integer32","(%rcx)+8").
abi_typelocation("a","MPI_Probe","Import","Integer32","(%rcx)+12").
abi_typelocation("a","MPI_Probe","Import","Integer64","(%rcx)+16").
abi_typelocation("a","MPI_Probe","Export","Integer32","%rax").
abi_typelocation("a","MPI_Recv","Both","Void","(%rdi)").
abi_typelocation("a","MPI_Recv","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Recv","Import","Empty","(%rdx)").
abi_typelocation("a","MPI_Recv","Import","Integer32","%rcx").
abi_typelocation("a","MPI_Recv","Import","Integer32","%r8").
abi_typelocation("a","MPI_Recv","Import","Empty","(%r9)").
abi_typelocation("a","MPI_Recv","Import","Integer32","(framebase+8)").
abi_typelocation("a","MPI_Recv","Import","Integer32","(framebase+8)+4").
abi_typelocation("a","MPI_Recv","Import","Integer32","(framebase+8)+8").
abi_typelocation("a","MPI_Recv","Import","Integer32","(framebase+8)+12").
abi_typelocation("a","MPI_Recv","Import","Integer64","(framebase+8)+16").
abi_typelocation("a","MPI_Recv","Export","Integer32","%rax").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","%rdi").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Iprobe","Import","Empty","(%rdx)").
abi_typelocation("a","MPI_Iprobe","Both","Integer32","(%rcx)").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","(%r8)").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","(%r8)+4").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","(%r8)+8").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","(%r8)+12").
abi_typelocation("a","MPI_Iprobe","Import","Integer64","(%r8)+16").
abi_typelocation("a","MPI_Iprobe","Export","Integer32","%rax").
abi_typelocation("a","H5Lunpack_elink_val","Import","Integer64","%rsi").
abi_typelocation("a","H5Lunpack_elink_val","Both","Integer32","(%rdx)").
abi_typelocation("a","H5Lunpack_elink_val","Both","Integer8","((%rcx))").
abi_typelocation("a","H5Lunpack_elink_val","Both","Integer8","((%r8))").
abi_typelocation("a","H5Lunpack_elink_val","Export","Integer32","%rax").
abi_typelocation("a","H5Fclose","Import","Integer64","%rdi").
abi_typelocation("a","H5Fclose","Export","Integer32","%rax").
abi_typelocation("a","MPI_Abort","Import","Empty","(%rdi)").
abi_typelocation("a","MPI_Abort","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Abort","Export","Integer32","%rax").
abi_typelocation("a","HDfprintf","Import","Integer32","(%rdi)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+8)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+16)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+24)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+32)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+40)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+48)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+56)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+64)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+72)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+80)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+88)").
abi_typelocation("a","HDfprintf","Import","Empty","((%rdi)+96)").
abi_typelocation("a","HDfprintf","Import","Integer32","((%rdi)+104)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+8)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+16)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+24)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+32)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+40)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+48)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+56)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+64)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+72)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+80)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+88)").
abi_typelocation("a","HDfprintf","Import","Empty","(((%rdi)+104)+96)").
abi_typelocation("a","HDfprintf","Import","Opaque","(((%rdi)+104)+104)").
abi_typelocation("a","HDfprintf","Import","Integer32","((%rdi)+104)+112").
abi_typelocation("a","HDfprintf","Import","Integer32","((%rdi)+104)+116").
abi_typelocation("a","HDfprintf","Import","Integer64","((%rdi)+104)+120").
abi_typelocation("a","HDfprintf","Import","Integer16","((%rdi)+104)+128").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+104)+130").
abi_typelocation("a","HDfprintf","Import","Array[1:1]","((%rdi)+104)+131").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+104)+131").
abi_typelocation("a","HDfprintf","Import","Integer64","((%rdi)+104)+144").
abi_typelocation("a","HDfprintf","Import","Empty","(((%rdi)+104)+152)").
abi_typelocation("a","HDfprintf","Import","Empty","(((%rdi)+104)+160)").
abi_typelocation("a","HDfprintf","Import","Opaque","(((%rdi)+104)+168)").
abi_typelocation("a","HDfprintf","Import","Void","(((%rdi)+104)+176)").
abi_typelocation("a","HDfprintf","Import","Integer64","((%rdi)+104)+184").
abi_typelocation("a","HDfprintf","Import","Integer32","((%rdi)+104)+192").
abi_typelocation("a","HDfprintf","Import","Array[20:20]","((%rdi)+104)+196").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+104)+196").
abi_typelocation("a","HDfprintf","Import","Integer32","(%rdi)+112").
abi_typelocation("a","HDfprintf","Import","Integer32","(%rdi)+116").
abi_typelocation("a","HDfprintf","Import","Integer64","(%rdi)+120").
abi_typelocation("a","HDfprintf","Import","Integer16","(%rdi)+128").
abi_typelocation("a","HDfprintf","Import","Integer8","(%rdi)+130").
abi_typelocation("a","HDfprintf","Import","Array[1:1]","(%rdi)+131").
abi_typelocation("a","HDfprintf","Import","Integer8","(%rdi)+131").
abi_typelocation("a","HDfprintf","Import","Integer64","(%rdi)+144").
abi_typelocation("a","HDfprintf","Import","Empty","((%rdi)+152)").
abi_typelocation("a","HDfprintf","Import","Empty","((%rdi)+160)").
abi_typelocation("a","HDfprintf","Import","Opaque","((%rdi)+168)").
abi_typelocation("a","HDfprintf","Import","Void","((%rdi)+176)").
abi_typelocation("a","HDfprintf","Import","Integer64","(%rdi)+184").
abi_typelocation("a","HDfprintf","Import","Integer32","(%rdi)+192").
abi_typelocation("a","HDfprintf","Import","Array[20:20]","(%rdi)+196").
abi_typelocation("a","HDfprintf","Import","Integer8","(%rdi)+196").
abi_typelocation("a","HDfprintf","Both","Integer8","(%rsi)").
abi_typelocation("a","HDfprintf","Export","Integer32","%rax").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","%rdi").
abi_typelocation("a","H5Oget_info_by_name","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+8").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer32","(%rdx)+16").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer32","(%rdx)+20").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+24").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+32").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+40").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+48").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+56").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer32","(%rdx)+64").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer32","(%rdx)+68").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer32","(%rdx)+72").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer32","(%rdx)+76").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+80").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+88").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+96").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+104").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+112").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+120").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+128").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+136").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+144").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+152").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","%rcx").
abi_typelocation("a","H5Oget_info_by_name","Export","Integer32","%rax").
abi_typelocation("a","H5Lget_info","Import","Integer64","%rdi").
abi_typelocation("a","H5Lget_info","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Lget_info","Import","Integer32","(%rdx)").
abi_typelocation("a","H5Lget_info","Import","Integer8","(%rdx)+4").
abi_typelocation("a","H5Lget_info","Import","Integer64","(%rdx)+8").
abi_typelocation("a","H5Lget_info","Import","Integer32","(%rdx)+16").
abi_typelocation("a","H5Lget_info","Import","Union","(%rdx)+24").
abi_typelocation("a","H5Lget_info","Import","Integer64","%rcx").
abi_typelocation("a","H5Lget_info","Export","Integer32","%rax").
abi_typelocation("a","H5Lexists","Import","Integer64","%rdi").
abi_typelocation("a","H5Lexists","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Lexists","Import","Integer64","%rdx").
abi_typelocation("a","H5Lexists","Export","Integer32","%rax").
abi_typelocation("a","H5Eset_auto1","Import","Void","(%rdi)").
abi_typelocation("a","H5Eset_auto1","Both","Void","(%rsi)").
abi_typelocation("a","H5Eset_auto1","Export","Integer32","%rax").
abi_typelocation("a","H5Eget_auto1","Both","Void","((%rdi))").
abi_typelocation("a","H5Eget_auto1","Both","Void","((%rsi))").
abi_typelocation("a","H5Eget_auto1","Export","Integer32","%rax").
abi_typelocation("a","H5Eset_auto2","Import","Integer64","%rdi").
abi_typelocation("a","H5Eset_auto2","Import","Void","(%rsi)").
abi_typelocation("a","H5Eset_auto2","Both","Void","(%rdx)").
abi_typelocation("a","H5Eset_auto2","Export","Integer32","%rax").
abi_typelocation("a","H5Eget_auto2","Import","Integer64","%rdi").
abi_typelocation("a","H5Eget_auto2","Both","Void","((%rsi))").
abi_typelocation("a","H5Eget_auto2","Both","Void","((%rdx))").
abi_typelocation("a","H5Eget_auto2","Export","Integer32","%rax").
abi_typelocation("a","H5Eauto_is_v2","Import","Integer64","%rdi").
abi_typelocation("a","H5Eauto_is_v2","Both","Integer32","(%rsi)").
abi_typelocation("a","H5Eauto_is_v2","Export","Integer32","%rax").
abi_typelocation("a","MPI_Send","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Send","Import","Empty","(%rdx)").
abi_typelocation("a","MPI_Send","Import","Integer32","%rcx").
abi_typelocation("a","MPI_Send","Import","Integer32","%r8").
abi_typelocation("a","MPI_Send","Import","Empty","(%r9)").
abi_typelocation("a","MPI_Send","Export","Integer32","%rax").
abi_typelocation("a","H5Rget_obj_type2","Import","Integer8","%rdi").
abi_typelocation("a","H5Rget_region","Import","Integer8","%rdi").
abi_typelocation("a","H5Rdereference2","Import","Integer8","%rdi").
abi_typelocation("a","H5Tenum_nameof","Import","Integer8","%rdi").
abi_typelocation("a","H5Tenum_nameof","Import","Integer8","()").
abi_typelocation("a","H5Tget_member_offset","Export","Integer8","()").
abi_typelocation("a","H5Tconvert","Import","Integer8","()").
abi_typelocation("a","H5Tget_size","Export","Integer8","()").
abi_typelocation("a","H5Eauto_is_v2","Export","Integer64","%rdi").
abi_typelocation("a","H5Eauto_is_v2","Export","Integer64","%rsi").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer32","framebase+8").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","(framebase+16)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","(framebase+24)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","(framebase+32)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","(framebase+40)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","(framebase+48)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","(framebase+56)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","(framebase+64)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","(framebase+72)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","(framebase+80)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","(framebase+88)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","(framebase+96)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Empty","(framebase+104)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer32","(framebase+112)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","((framebase+112)+8)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","((framebase+112)+16)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","((framebase+112)+24)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","((framebase+112)+32)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","((framebase+112)+40)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","((framebase+112)+48)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","((framebase+112)+56)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","((framebase+112)+64)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","((framebase+112)+72)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","((framebase+112)+80)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","((framebase+112)+88)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Empty","((framebase+112)+96)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Opaque","((framebase+112)+104)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer32","(framebase+112)+112").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer32","(framebase+112)+116").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer64","(framebase+112)+120").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer16","(framebase+112)+128").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","(framebase+112)+130").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Array[1:1]","(framebase+112)+131").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","(framebase+112)+131").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer64","(framebase+112)+144").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Empty","((framebase+112)+152)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Empty","((framebase+112)+160)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Opaque","((framebase+112)+168)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Void","((framebase+112)+176)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer64","(framebase+112)+184").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer32","(framebase+112)+192").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Array[20:20]","(framebase+112)+196").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","(framebase+112)+196").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer32","framebase+120").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer32","framebase+124").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer64","framebase+128").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer16","framebase+136").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","framebase+138").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Array[1:1]","framebase+139").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","framebase+139").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer64","framebase+152").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Empty","(framebase+160)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Empty","(framebase+168)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Opaque","(framebase+176)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Void","(framebase+184)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer64","framebase+192").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer32","framebase+200").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Array[20:20]","framebase+204").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","framebase+204").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer32","framebase+224").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","(framebase+232)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","(framebase+240)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","(framebase+248)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","(framebase+256)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","(framebase+264)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","(framebase+272)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","(framebase+280)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","(framebase+288)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","(framebase+296)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","(framebase+304)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","(framebase+312)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Empty","(framebase+320)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer32","(framebase+328)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","((framebase+328)+8)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","((framebase+328)+16)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","((framebase+328)+24)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","((framebase+328)+32)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","((framebase+328)+40)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","((framebase+328)+48)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","((framebase+328)+56)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","((framebase+328)+64)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","((framebase+328)+72)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","((framebase+328)+80)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","((framebase+328)+88)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Empty","((framebase+328)+96)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Opaque","((framebase+328)+104)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer32","(framebase+328)+112").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer32","(framebase+328)+116").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer64","(framebase+328)+120").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer16","(framebase+328)+128").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","(framebase+328)+130").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Array[1:1]","(framebase+328)+131").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","(framebase+328)+131").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer64","(framebase+328)+144").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Empty","((framebase+328)+152)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Empty","((framebase+328)+160)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Opaque","((framebase+328)+168)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Void","((framebase+328)+176)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer64","(framebase+328)+184").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer32","(framebase+328)+192").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Array[20:20]","(framebase+328)+196").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","(framebase+328)+196").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer32","framebase+336").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer32","framebase+340").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer64","framebase+344").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer16","framebase+352").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","framebase+354").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Array[1:1]","framebase+355").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","framebase+355").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer64","framebase+368").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Empty","(framebase+376)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Empty","(framebase+384)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Opaque","(framebase+392)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Void","(framebase+400)").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer64","framebase+408").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer32","framebase+416").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Array[20:20]","framebase+420").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","framebase+420").
abi_typelocation("a","H5Sselect_hyperslab","Import","Integer32","%rdi").
abi_typelocation("a","H5Sselect_hyperslab","Import","Integer32","%rsi").
abi_typelocation("a","H5Sselect_hyperslab","Import","Integer32","%rdx").
abi_typelocation("a","H5Sselect_hyperslab","Import","Integer32","%rcx").
abi_typelocation("a","H5Screate_simple","Import","Integer32","%rdi").
abi_typelocation("a","H5Screate_simple","Import","Integer32","%rsi").
abi_typelocation("a","H5Dread","Import","Integer64","%rdi").
abi_typelocation("a","H5Tget_member_offset","Import","Integer32","%rdi").
abi_typelocation("a","H5Tget_member_offset","Export","Integer64","%rax").
abi_typelocation("a","H5Epush2","Import","Integer32","%rdi").
abi_typelocation("a","H5Tget_size","Export","Integer64","%rax").
abi_typelocation("a","H5Tget_member_type","Import","Integer32","%rdi").
abi_typelocation("a","H5Fopen","Import","Integer32","%rdi").
abi_typelocation("a","H5Eset_auto1","Import","Integer64","%rdi").
abi_typelocation("a","H5Eset_auto2","Import","Integer64","%rdi").
abi_typelocation("a","H5Eprint2","Import","Integer8","()").
abi_typelocation("a","HDfprintf","Import","Integer8","()").
abi_typelocation("a","H5Ecreate_msg","Import","Integer64","+8").
abi_typelocation("a","H5Ecreate_msg","Import","Integer64","+16").
abi_typelocation("a","H5Ecreate_msg","Import","Integer64","+24").
abi_typelocation("a","H5Aread","Import","Integer64","%rdi").
abi_typelocation("a","H5Pget_external","Import","Integer32","%rdi").
abi_typelocation("a","H5Pget_external","Import","Integer8","()").
abi_typelocation("a","H5Pget_filter2","Import","Integer32","%rdi").
abi_typelocation("a","H5Pget_filter2","Import","Integer8","(())").
abi_typelocation("a","H5Pget_chunk","Import","Integer8","()").
abi_typelocation("a","H5Pget_fill_value","Import","Integer64","%rdi").
abi_typelocation("a","H5Tconvert","Import","Integer64","%rdi").
abi_typelocation("a","H5Tconvert","Import","Integer64","%rsi").
abi_typelocation("a","H5Tget_member_value","Import","Integer32","%rdi").
abi_typelocation("a","H5Tget_member_value","Import","Integer64","%rsi").
abi_typelocation("a","H5Tget_array_dims2","Import","Integer8","()").
abi_typelocation("a","H5Tget_member_type","Import","Integer32","%rdi").
abi_typelocation("a","H5Tget_member_name","Import","Integer32","%rdi").
abi_typelocation("a","H5free_memory","Import","Integer64","%rdi").
abi_typelocation("a","H5Sget_select_bounds","Import","Integer8","()").
abi_typelocation("a","H5Sget_select_bounds","Import","Integer8","()").
abi_typelocation("a","H5Dvlen_reclaim","Import","Integer64","%rdi").
abi_typelocation("a","H5Sget_select_elem_pointlist","Import","Integer8","()").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","()").
abi_typelocation("a","H5Sget_simple_extent_dims","Import","Integer8","()").
abi_typelocation("a","H5Dread","Import","Integer64","%rdi").
abi_typelocation("a","H5Sget_select_hyper_blocklist","Import","Integer8","()").
abi_typelocation("a","H5Epush2","Import","Integer32","%rdi").
abi_typelocation("a","H5Rget_name","Import","Integer8","()").
abi_typelocation("a","H5Rget_region","Import","Integer8","()").
abi_typelocation("a","H5Rdereference2","Import","Integer8","()").
abi_typelocation("a","H5Pget_filter2","Import","Integer8","()").
abi_typelocation("a","H5SL_search","Export","Integer64","%rax").
abi_typelocation("a","H5SL_insert","Import","Integer64","%rdi").
abi_typelocation("a","H5SL_destroy","Import","Integer64","%rdi").
abi_typelocation("a","H5Tget_array_dims2","Both","Integer32","(%rdi)").
abi_typelocation("a","H5Tget_member_type","Import","Integer64","%rdi").
abi_typelocation("a","H5Tget_member_offset","Import","Integer64","%rdi").
abi_typelocation("a","H5Tget_member_name","Import","Integer64","%rdi").
abi_typelocation("a","H5Sget_select_elem_pointlist","Both","Integer32","(%rdi)").
abi_typelocation("a","H5Sget_select_hyper_blocklist","Both","Integer32","(%rdi)").
abi_typelocation("a","H5Eset_auto2","Import","Integer32","%rdi").
abi_typelocation("a","H5Sget_regular_hyperslab","Both","Integer32","(%rdi)").
abi_typelocation("a","H5Sget_regular_hyperslab","Both","Integer32","(%rsi)").
abi_typelocation("a","H5Sget_regular_hyperslab","Both","Integer32","(%rdx)").
abi_typelocation("a","H5Sget_regular_hyperslab","Both","Integer32","(%rcx)").
abi_typelocation("a","H5Eset_auto1","Import","Void","(%rdi)").
abi_typelocation("a","H5Eset_auto1","Both","Void","(%rsi)").
abi_typelocation("a","H5Eset_auto1","Export","Integer32","%rax").
abi_typelocation("a","H5Lget_val","Import","Empty","none").
abi_typelocation("a","H5Lunpack_elink_val","Import","Integer8","()").
abi_typelocation("a","H5Lget_val","Import","Integer8","()").
abi_typelocation("a","MPI_Wtime","Export","Integer8","()").

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-haswell/gcc-11.2.0/hdf5-1.10.1-twpl2txfqxh5mhjmpcwq4buir5wz7iip/lib/libhdf5.so.100.1.0
%----------------------------------------------------------------------------
abi_typelocation("b","HDfprintf","Import","Integer32","(%rdi)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+8)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+16)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+24)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+32)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+40)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+48)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+56)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+64)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+72)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+80)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+88)").
abi_typelocation("b","HDfprintf","Import","Empty","((%rdi)+96)").
abi_typelocation("b","HDfprintf","Import","Integer32","((%rdi)+104)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+8)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+16)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+24)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+32)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+40)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+48)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+56)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+64)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+72)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+80)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+88)").
abi_typelocation("b","HDfprintf","Import","Empty","(((%rdi)+104)+96)").
abi_typelocation("b","HDfprintf","Import","Opaque","(((%rdi)+104)+104)").
abi_typelocation("b","HDfprintf","Import","Integer32","((%rdi)+104)+112").
abi_typelocation("b","HDfprintf","Import","Integer32","((%rdi)+104)+116").
abi_typelocation("b","HDfprintf","Import","Integer64","((%rdi)+104)+120").
abi_typelocation("b","HDfprintf","Import","Integer16","((%rdi)+104)+128").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+104)+130").
abi_typelocation("b","HDfprintf","Import","Array[1:1]","((%rdi)+104)+131").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+104)+131").
abi_typelocation("b","HDfprintf","Import","Integer64","((%rdi)+104)+144").
abi_typelocation("b","HDfprintf","Import","Empty","(((%rdi)+104)+152)").
abi_typelocation("b","HDfprintf","Import","Empty","(((%rdi)+104)+160)").
abi_typelocation("b","HDfprintf","Import","Opaque","(((%rdi)+104)+168)").
abi_typelocation("b","HDfprintf","Import","Void","(((%rdi)+104)+176)").
abi_typelocation("b","HDfprintf","Import","Integer64","((%rdi)+104)+184").
abi_typelocation("b","HDfprintf","Import","Integer32","((%rdi)+104)+192").
abi_typelocation("b","HDfprintf","Import","Array[20:20]","((%rdi)+104)+196").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+104)+196").
abi_typelocation("b","HDfprintf","Import","Integer32","(%rdi)+112").
abi_typelocation("b","HDfprintf","Import","Integer32","(%rdi)+116").
abi_typelocation("b","HDfprintf","Import","Integer64","(%rdi)+120").
abi_typelocation("b","HDfprintf","Import","Integer16","(%rdi)+128").
abi_typelocation("b","HDfprintf","Import","Integer8","(%rdi)+130").
abi_typelocation("b","HDfprintf","Import","Array[1:1]","(%rdi)+131").
abi_typelocation("b","HDfprintf","Import","Integer8","(%rdi)+131").
abi_typelocation("b","HDfprintf","Import","Integer64","(%rdi)+144").
abi_typelocation("b","HDfprintf","Import","Empty","((%rdi)+152)").
abi_typelocation("b","HDfprintf","Import","Empty","((%rdi)+160)").
abi_typelocation("b","HDfprintf","Import","Opaque","((%rdi)+168)").
abi_typelocation("b","HDfprintf","Import","Void","((%rdi)+176)").
abi_typelocation("b","HDfprintf","Import","Integer64","(%rdi)+184").
abi_typelocation("b","HDfprintf","Import","Integer32","(%rdi)+192").
abi_typelocation("b","HDfprintf","Import","Array[20:20]","(%rdi)+196").
abi_typelocation("b","HDfprintf","Import","Integer8","(%rdi)+196").
abi_typelocation("b","HDfprintf","Both","Integer8","(%rsi)").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","H5Eget_auto2","Import","Integer64","%rdi").
abi_typelocation("b","H5Eget_auto2","Both","Void","((%rsi))").
abi_typelocation("b","H5Eget_auto2","Both","Void","((%rdx))").
abi_typelocation("b","H5Eget_auto2","Export","Integer32","%rax").
abi_typelocation("b","H5free_memory","Both","Void","(%rdi)").
abi_typelocation("b","H5free_memory","Export","Integer32","%rax").
abi_typelocation("b","H5close","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","H5Aiterate_by_name","Import","Integer8","()").
abi_typelocation("b","H5Aget_name","Import","Integer64","%rdi").
abi_typelocation("b","H5Aread","Import","Integer8","()").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","H5SL_insert","Import","Integer8","()").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","H5SL_insert","Import","Integer64","%rdi").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","H5close","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Import","Integer32","%rdi").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","H5SL_insert","Import","Integer32","%rdi").
abi_typelocation("b","H5SL_search","Import","Integer32","%rdi").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","H5Eset_auto1","Import","Integer32","%rdi").
abi_typelocation("b","H5Pset_fapl_family","Import","Integer32","()").
abi_typelocation("b","H5Tconvert","Import","Integer8","%rdi").
abi_typelocation("b","H5Tconvert","Import","Integer8","%rsi").
abi_typelocation("b","H5Tconvert","Import","Integer8","%rdx").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","()").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","%rdi").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","%rdi").
abi_typelocation("b","H5Epush2","Import","Integer8","%rdi").
abi_typelocation("b","H5SL_destroy","Import","Integer8","()").
abi_typelocation("b","H5SL_destroy","Import","Integer64","%rdi").
abi_typelocation("b","HDfprintf","Import","Integer8","%rdi").
abi_typelocation("b","H5SL_insert","Import","Integer64","%rdi").
abi_typelocation("b","H5SL_search","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","H5Eset_auto1","Export","Integer32","()").
abi_typelocation("b","H5Eget_auto1","Export","Integer32","()").
abi_typelocation("b","H5Eset_auto2","Export","Integer32","()").
abi_typelocation("b","H5Eget_auto2","Export","Integer32","()").
abi_typelocation("b","H5Eauto_is_v2","Export","Integer32","()").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","H5free_memory","Both","Void","(%rdi)").
abi_typelocation("b","H5free_memory","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","H5Eset_auto1","Import","Integer32","framebase+8").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","(framebase+16)").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","(framebase+24)").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","(framebase+32)").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","(framebase+40)").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","(framebase+48)").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","(framebase+56)").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","(framebase+64)").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","(framebase+72)").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","(framebase+80)").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","(framebase+88)").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","(framebase+96)").
abi_typelocation("b","H5Eset_auto1","Import","Empty","(framebase+104)").
abi_typelocation("b","H5Eset_auto1","Import","Integer32","(framebase+112)").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","((framebase+112)+8)").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","((framebase+112)+16)").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","((framebase+112)+24)").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","((framebase+112)+32)").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","((framebase+112)+40)").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","((framebase+112)+48)").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","((framebase+112)+56)").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","((framebase+112)+64)").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","((framebase+112)+72)").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","((framebase+112)+80)").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","((framebase+112)+88)").
abi_typelocation("b","H5Eset_auto1","Import","Empty","((framebase+112)+96)").
abi_typelocation("b","H5Eset_auto1","Import","Opaque","((framebase+112)+104)").
abi_typelocation("b","H5Eset_auto1","Import","Integer32","(framebase+112)+112").
abi_typelocation("b","H5Eset_auto1","Import","Integer32","(framebase+112)+116").
abi_typelocation("b","H5Eset_auto1","Import","Integer64","(framebase+112)+120").
abi_typelocation("b","H5Eset_auto1","Import","Integer16","(framebase+112)+128").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","(framebase+112)+130").
abi_typelocation("b","H5Eset_auto1","Import","Array[1:1]","(framebase+112)+131").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","(framebase+112)+131").
abi_typelocation("b","H5Eset_auto1","Import","Integer64","(framebase+112)+144").
abi_typelocation("b","H5Eset_auto1","Import","Empty","((framebase+112)+152)").
abi_typelocation("b","H5Eset_auto1","Import","Empty","((framebase+112)+160)").
abi_typelocation("b","H5Eset_auto1","Import","Opaque","((framebase+112)+168)").
abi_typelocation("b","H5Eset_auto1","Import","Void","((framebase+112)+176)").
abi_typelocation("b","H5Eset_auto1","Import","Integer64","(framebase+112)+184").
abi_typelocation("b","H5Eset_auto1","Import","Integer32","(framebase+112)+192").
abi_typelocation("b","H5Eset_auto1","Import","Array[20:20]","(framebase+112)+196").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","(framebase+112)+196").
abi_typelocation("b","H5Eset_auto1","Import","Integer32","framebase+120").
abi_typelocation("b","H5Eset_auto1","Import","Integer32","framebase+124").
abi_typelocation("b","H5Eset_auto1","Import","Integer64","framebase+128").
abi_typelocation("b","H5Eset_auto1","Import","Integer16","framebase+136").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","framebase+138").
abi_typelocation("b","H5Eset_auto1","Import","Array[1:1]","framebase+139").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","framebase+139").
abi_typelocation("b","H5Eset_auto1","Import","Integer64","framebase+152").
abi_typelocation("b","H5Eset_auto1","Import","Empty","(framebase+160)").
abi_typelocation("b","H5Eset_auto1","Import","Empty","(framebase+168)").
abi_typelocation("b","H5Eset_auto1","Import","Opaque","(framebase+176)").
abi_typelocation("b","H5Eset_auto1","Import","Void","(framebase+184)").
abi_typelocation("b","H5Eset_auto1","Import","Integer64","framebase+192").
abi_typelocation("b","H5Eset_auto1","Import","Integer32","framebase+200").
abi_typelocation("b","H5Eset_auto1","Import","Array[20:20]","framebase+204").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","framebase+204").
abi_typelocation("b","H5Lvisit_by_name","Import","Array","%rax").
abi_typelocation("b","H5Lvisit_by_name","Import","Integer8","%rax").
abi_typelocation("b","H5Literate_by_name","Import","Array","%rax").
abi_typelocation("b","H5Literate_by_name","Import","Integer8","%rax").
abi_typelocation("b","H5Lget_info","Import","Array","%rax").
abi_typelocation("b","H5Lget_info","Import","Integer8","%rax").
abi_typelocation("b","H5Lget_val","Import","Integer64","%rdi").
abi_typelocation("b","H5Lget_val","Import","Array","%rax").
abi_typelocation("b","H5Lget_val","Import","Integer8","%rax").
abi_typelocation("b","H5Lunpack_elink_val","Import","Integer64","%rdi").
abi_typelocation("b","H5Lunpack_elink_val","Import","Empty","(%rax)").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","H5SL_search","Export","Integer64","%rax").
abi_typelocation("b","H5SL_destroy","Import","Integer64","%rdi").
abi_typelocation("b","H5SL_insert","Import","Integer64","%rdi").
abi_typelocation("b","H5Oget_comment","Import","Empty","(%rax)").
abi_typelocation("b","H5Oget_info_by_name","Import","Integer8","()").
abi_typelocation("b","H5Oexists_by_name","Import","Integer8","()").
abi_typelocation("b","H5SL_search","Export","Integer64","%rax").
abi_typelocation("b","H5SL_insert","Import","Integer64","%rdi").
abi_typelocation("b","H5SL_destroy","Import","Integer64","%rdi").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Import","Integer8","()").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Import","Integer8","%rdi").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Import","Integer8","%rdi").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Import","Integer8","%rdi").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","H5Pget_external","Import","Empty","none").
abi_typelocation("b","H5Pget_external_count","Export","Integer64","%rax").
abi_typelocation("b","H5Pget_virtual_dsetname","Import","Empty","none").
abi_typelocation("b","H5Pget_virtual_dsetname","Import","Empty","none").
abi_typelocation("b","H5Pget_virtual_filename","Import","Empty","none").
abi_typelocation("b","H5Pget_virtual_filename","Import","Empty","none").
abi_typelocation("b","H5Pget_virtual_srcspace","Import","Empty","none").
abi_typelocation("b","H5Pget_virtual_vspace","Import","Empty","none").
abi_typelocation("b","H5Pget_chunk","Import","Integer64","%rdi").
abi_typelocation("b","H5Pget_chunk","Export","Integer64","%rax").
abi_typelocation("b","H5SL_destroy","Import","Integer8","()").
abi_typelocation("b","H5SL_search","Import","Empty","none").
abi_typelocation("b","H5SL_insert","Import","Empty","none").
abi_typelocation("b","H5Pget_filter2","Import","Integer8","()").
abi_typelocation("b","H5Pget_filter2","Import","Integer64","%rdi").
abi_typelocation("b","H5Pget_nfilters","Import","Integer8","()").
abi_typelocation("b","H5Pget_nfilters","Export","Integer64","%rax").
abi_typelocation("b","H5Screate_simple","Import","Integer64","%rdi").
abi_typelocation("b","H5Sget_simple_extent_dims","Export","Integer64","%rax").
abi_typelocation("b","H5Sget_simple_extent_ndims","Export","Integer64","%rax").
abi_typelocation("b","H5Sget_regular_hyperslab","Export","Integer32","(%rax)").
abi_typelocation("b","H5Sselect_hyperslab","Export","Integer32","(%rax)").
abi_typelocation("b","H5Sget_select_hyper_blocklist","Export","Integer32","(%rax)").
abi_typelocation("b","H5Sget_select_elem_pointlist","Import","Void","()").
abi_typelocation("b","H5Sget_select_elem_pointlist","Import","Void","()").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5SL_destroy","Import","Integer64","%rdi").
abi_typelocation("b","H5SL_search","Export","Integer64","%rax").
abi_typelocation("b","H5SL_insert","Import","Integer64","%rdi").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","H5Tconvert","Import","Integer8","()").
abi_typelocation("b","H5Tconvert","Import","Integer8","()").
abi_typelocation("b","H5Tget_array_dims2","Export","Integer64","%rax").
abi_typelocation("b","H5Tget_array_ndims","Export","Integer64","%rax").
abi_typelocation("b","H5Topen2","Import","Void","()").
abi_typelocation("b","H5Tget_member_value","Import","Integer8","()").
abi_typelocation("b","H5Tget_nmembers","Export","Integer64","%rax").

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-haswell/gcc-11.2.0/openmpi-4.1.4-qndlygdkqfm2fu66n3dro5dggzlpvdxs/lib/libmpi.so.40
%----------------------------------------------------------------------------
