
%============================================================================
% Library Facts
%============================================================================

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-11.2.0/binutils-2.34-4ntqc6nanisshfjjdtpsks4gqzpplkvz/lib/libctf.so
%----------------------------------------------------------------------------
abi_typelocation("a","compress","Import","Integer8","(())").
abi_typelocation("a","compress","Import","Integer32","()+8").
abi_typelocation("a","compress","Import","Integer64","()+16").
abi_typelocation("a","compress","Import","Integer64","()+24").
abi_typelocation("a","compress","Import","Integer64","()+32").
abi_typelocation("a","compress","Import","Integer64","()+40").
abi_typelocation("a","compress","Import","Integer64","()+48").
abi_typelocation("a","compressBound","Import","Integer8","(())").
abi_typelocation("a","compressBound","Import","Integer32","()+8").
abi_typelocation("a","compressBound","Import","Integer64","()+16").
abi_typelocation("a","compressBound","Import","Integer64","()+24").
abi_typelocation("a","compressBound","Import","Integer64","()+32").
abi_typelocation("a","compressBound","Import","Integer64","()+40").
abi_typelocation("a","compressBound","Import","Integer64","()+48").
abi_typelocation("a","compressBound","Import","Integer8","(())").
abi_typelocation("a","compressBound","Import","Integer32","()+8").
abi_typelocation("a","compressBound","Import","Integer64","()+16").
abi_typelocation("a","compressBound","Import","Integer64","()+24").
abi_typelocation("a","compressBound","Import","Integer64","()+32").
abi_typelocation("a","compressBound","Import","Integer64","()+40").
abi_typelocation("a","compressBound","Import","Integer64","()+48").
abi_typelocation("a","gzwrite","Import","Integer64","%rdi").
abi_typelocation("a","bfd_malloc_and_get_section","Import","Opaque","((((%rdi))))").
abi_typelocation("a","bfd_malloc_and_get_section","Import","Integer8","((((%rdi)))+8)").
abi_typelocation("a","bfd_malloc_and_get_section","Import","Integer64","(((%rdi)))+16").
abi_typelocation("a","bfd_malloc_and_get_section","Import","Integer32","(((%rdi)))+24").
abi_typelocation("a","bfd_malloc_and_get_section","Import","Opaque","((((%rdi)))+32)").
abi_typelocation("a","bfd_malloc_and_get_section","Import","Union","(((%rdi)))+40").
abi_typelocation("a","bfd_malloc_and_get_section","Import","Integer64","(%rdi)+8").
abi_typelocation("a","bfd_malloc_and_get_section","Import","Integer64","(%rdi)+16").
abi_typelocation("a","bfd_malloc_and_get_section","Import","Integer32","((%rdi)+24)").
abi_typelocation("a","bfd_malloc_and_get_section","Import","Integer32","((%rdi)+24)").
abi_typelocation("a","bfd_malloc_and_get_section","Import","Integer32","((%rdi)+24)").
abi_typelocation("a","bfd_malloc_and_get_section","Import","Integer32","((%rdi)+24)").
abi_typelocation("a","bfd_malloc_and_get_section","Import","Integer32","((%rdi)+24)").
abi_typelocation("a","bfd_malloc_and_get_section","Import","Integer32","((%rdi)+24)").
abi_typelocation("a","bfd_malloc_and_get_section","Import","Integer32","((%rdi)+24)").
abi_typelocation("a","bfd_malloc_and_get_section","Import","Integer32","((%rdi)+24)").
abi_typelocation("a","bfd_malloc_and_get_section","Import","Integer32","((%rdi)+24)").
abi_typelocation("a","bfd_malloc_and_get_section","Import","Integer32","((%rdi)+24)").
abi_typelocation("a","bfd_malloc_and_get_section","Import","Integer64","((%rdi)+24)+8").
abi_typelocation("a","bfd_malloc_and_get_section","Import","Integer64","((%rdi)+24)+16").
abi_typelocation("a","bfd_malloc_and_get_section","Import","Void","(((%rdi)+24)+24)").
abi_typelocation("a","bfd_malloc_and_get_section","Import","Integer8","(((%rdi)+24)+32)").
abi_typelocation("a","bfd_get_section_by_name","Import","Opaque","((((%rax))))").
abi_typelocation("a","bfd_get_section_by_name","Import","Integer8","((((%rax)))+8)").
abi_typelocation("a","bfd_get_section_by_name","Import","Integer64","(((%rax)))+16").
abi_typelocation("a","bfd_get_section_by_name","Import","Integer32","(((%rax)))+24").
abi_typelocation("a","bfd_get_section_by_name","Import","Opaque","((((%rax)))+32)").
abi_typelocation("a","bfd_get_section_by_name","Import","Union","(((%rax)))+40").
abi_typelocation("a","bfd_get_section_by_name","Import","Integer64","(%rax)+8").
abi_typelocation("a","bfd_get_section_by_name","Import","Integer64","(%rax)+16").
abi_typelocation("a","bfd_get_section_by_name","Import","Integer32","((%rax)+24)").
abi_typelocation("a","bfd_get_section_by_name","Import","Integer32","((%rax)+24)").
abi_typelocation("a","bfd_get_section_by_name","Import","Integer32","((%rax)+24)").
abi_typelocation("a","bfd_get_section_by_name","Import","Integer32","((%rax)+24)").
abi_typelocation("a","bfd_get_section_by_name","Import","Integer32","((%rax)+24)").
abi_typelocation("a","bfd_get_section_by_name","Import","Integer32","((%rax)+24)").
abi_typelocation("a","bfd_get_section_by_name","Import","Integer32","((%rax)+24)").
abi_typelocation("a","bfd_get_section_by_name","Import","Integer32","((%rax)+24)").
abi_typelocation("a","bfd_get_section_by_name","Import","Integer32","((%rax)+24)").
abi_typelocation("a","bfd_get_section_by_name","Import","Integer32","((%rax)+24)").
abi_typelocation("a","bfd_get_section_by_name","Import","Integer64","((%rax)+24)+8").
abi_typelocation("a","bfd_get_section_by_name","Import","Integer64","((%rax)+24)+16").
abi_typelocation("a","bfd_get_section_by_name","Import","Void","(((%rax)+24)+24)").
abi_typelocation("a","bfd_get_section_by_name","Import","Integer8","(((%rax)+24)+32)").

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-11.2.0/zlib-1.2.12-luwgiwun44dt7hmxv4ki6xjnxyucze7f/lib/libz.so.1.2.12
%----------------------------------------------------------------------------
abi_typelocation("b","compressBound","Import","Integer8","%rdi").
abi_typelocation("b","compressBound","Export","Integer8","%rax").
abi_typelocation("b","compress","Import","Integer8","%rdi").
abi_typelocation("b","compress","Export","Integer64","%rax").
abi_typelocation("b","uncompress","Import","Integer8","%rdi").
abi_typelocation("b","uncompress","Export","Integer64","%rax").

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-11.2.0/binutils-2.34-vfycufdr74637fig76t4zbuvkhi3qgfh/lib/libbfd-2.34.so
%----------------------------------------------------------------------------
abi_typelocation("b","bfd_close_all_done","Import","Integer8","((%rdi))").
abi_typelocation("b","bfd_close_all_done","Import","Integer8","(((%rdi)+8))").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","((%rdi)+8)+8").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","((%rdi)+8)+12").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","((%rdi)+8)+16").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","((%rdi)+8)+20").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","((%rdi)+8)+24").
abi_typelocation("b","bfd_close_all_done","Import","Integer8","((%rdi)+8)+28").
abi_typelocation("b","bfd_close_all_done","Import","Integer8","((%rdi)+8)+29").
abi_typelocation("b","bfd_close_all_done","Import","Integer8","((%rdi)+8)+30").
abi_typelocation("b","bfd_close_all_done","Import","Integer8","((%rdi)+8)+31").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+32)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+40)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+48)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+56)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+64)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+72)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+80)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+88)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+96)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+104)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+112)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+120)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+128)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+136)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+144)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+152)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+160)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+168)").
abi_typelocation("b","bfd_close_all_done","Import","Array[32:4]","((%rdi)+8)+176").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+176)").
abi_typelocation("b","bfd_close_all_done","Import","Array[32:4]","((%rdi)+8)+208").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+208)").
abi_typelocation("b","bfd_close_all_done","Import","Array","((%rdi)+8)+240").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+240)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+272)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+280)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+288)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+296)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+304)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+312)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+320)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+328)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+336)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+344)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+352)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+360)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+368)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+376)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+384)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+392)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+400)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+408)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+416)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+424)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+432)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+440)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+448)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+456)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+464)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+472)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+480)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+488)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+496)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+504)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+512)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+520)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+528)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+536)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+544)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+552)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+560)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+568)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+576)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+584)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+592)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+600)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+608)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+616)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+624)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+632)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+640)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+648)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+656)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+664)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+672)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+680)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+688)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+696)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+704)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+712)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+720)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+728)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+736)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+744)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+752)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+760)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+768)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+776)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+784)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+792)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+800)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+808)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+816)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+824)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+832)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+840)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+848)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+856)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+8)+864)").
abi_typelocation("b","bfd_close_all_done","Import","Opaque","(((%rdi)+8)+872)").
abi_typelocation("b","bfd_close_all_done","Import","Void","((%rdi)+16)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+24))").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+24)+8)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+24)+16)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+24)+24)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+24)+32)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+24)+40)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+24)+48)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+24)+56)").
abi_typelocation("b","bfd_close_all_done","Import","Opaque","((%rdi)+32)").
abi_typelocation("b","bfd_close_all_done","Import","Opaque","((%rdi)+40)").
abi_typelocation("b","bfd_close_all_done","Import","Integer64","(%rdi)+48").
abi_typelocation("b","bfd_close_all_done","Import","Integer64","(%rdi)+56").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","(%rdi)+64").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","(%rdi)+72").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_close_all_done","Import","Opaque","((%rdi)+80)").
abi_typelocation("b","bfd_close_all_done","Import","Integer64","(%rdi)+88").
abi_typelocation("b","bfd_close_all_done","Import","Integer64","(%rdi)+96").
abi_typelocation("b","bfd_close_all_done","Import","Opaque","((((%rdi)+104)))").
abi_typelocation("b","bfd_close_all_done","Import","Integer8","((((%rdi)+104))+8)").
abi_typelocation("b","bfd_close_all_done","Import","Integer64","(((%rdi)+104))+16").
abi_typelocation("b","bfd_close_all_done","Import","Void","((%rdi)+112)").
abi_typelocation("b","bfd_close_all_done","Import","Void","((%rdi)+120)").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","(%rdi)+128").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","(%rdi)+132").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","(%rdi)+136").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","(%rdi)+104").
abi_typelocation("b","bfd_close_all_done","Import","Opaque","((%rdi)+144)").
abi_typelocation("b","bfd_close_all_done","Import","Opaque","((%rdi)+152)").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","(%rdi)+160").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","(%rdi)+164").
abi_typelocation("b","bfd_close_all_done","Import","Integer64","(%rdi)+168").
abi_typelocation("b","bfd_close_all_done","Import","Opaque","((%rdi)+176)").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","(%rdi)+184").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","(%rdi)+188").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","((%rdi)+192)").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","((%rdi)+192)+4").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","((%rdi)+192)+8").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","((%rdi)+192)+12").
abi_typelocation("b","bfd_close_all_done","Import","Integer64","((%rdi)+192)+16").
abi_typelocation("b","bfd_close_all_done","Import","Integer8","(((%rdi)+192)+24)").
abi_typelocation("b","bfd_close_all_done","Import","Integer8","(((%rdi)+192)+32)").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","((%rdi)+192)+40").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","((%rdi)+192)+44").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+192)+48)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+192)+56)").
abi_typelocation("b","bfd_close_all_done","Import","Void","(((%rdi)+192)+64)").
abi_typelocation("b","bfd_close_all_done","Import","Opaque","(((%rdi)+192)+72)").
abi_typelocation("b","bfd_close_all_done","Import","Integer32","((%rdi)+192)+80").
abi_typelocation("b","bfd_close_all_done","Import","Void","((%rdi)+200)").
abi_typelocation("b","bfd_close_all_done","Import","Opaque","((%rdi)+208)").
abi_typelocation("b","bfd_close_all_done","Import","Opaque","((%rdi)+216)").
abi_typelocation("b","bfd_close_all_done","Import","Opaque","((%rdi)+224)").
abi_typelocation("b","bfd_close_all_done","Import","Opaque","((%rdi)+232)").
abi_typelocation("b","bfd_close_all_done","Import","Union","(%rdi)+240").
abi_typelocation("b","bfd_close_all_done","Import","Union","(%rdi)+248").
abi_typelocation("b","bfd_close_all_done","Import","Void","((%rdi)+256)").
abi_typelocation("b","bfd_close_all_done","Import","Void","((%rdi)+264)").
abi_typelocation("b","bfd_close_all_done","Import","Integer64","((%rdi)+272)").
abi_typelocation("b","bfd_close_all_done","Import","Array[1:1]","((%rdi)+272)+8").
abi_typelocation("b","bfd_close_all_done","Import","Integer8","((%rdi)+272)+8").
abi_typelocation("b","bfd_close_all_done","Export","Integer32","%rax").
abi_typelocation("b","bfd_check_format","Import","Integer8","((%rdi))").
abi_typelocation("b","bfd_check_format","Import","Integer8","(((%rdi)+8))").
abi_typelocation("b","bfd_check_format","Import","Integer32","((%rdi)+8)+8").
abi_typelocation("b","bfd_check_format","Import","Integer32","((%rdi)+8)+12").
abi_typelocation("b","bfd_check_format","Import","Integer32","((%rdi)+8)+16").
abi_typelocation("b","bfd_check_format","Import","Integer32","((%rdi)+8)+20").
abi_typelocation("b","bfd_check_format","Import","Integer32","((%rdi)+8)+24").
abi_typelocation("b","bfd_check_format","Import","Integer8","((%rdi)+8)+28").
abi_typelocation("b","bfd_check_format","Import","Integer8","((%rdi)+8)+29").
abi_typelocation("b","bfd_check_format","Import","Integer8","((%rdi)+8)+30").
abi_typelocation("b","bfd_check_format","Import","Integer8","((%rdi)+8)+31").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+32)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+40)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+48)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+56)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+64)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+72)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+80)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+88)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+96)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+104)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+112)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+120)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+128)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+136)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+144)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+152)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+160)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+168)").
abi_typelocation("b","bfd_check_format","Import","Array[32:4]","((%rdi)+8)+176").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+176)").
abi_typelocation("b","bfd_check_format","Import","Array[32:4]","((%rdi)+8)+208").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+208)").
abi_typelocation("b","bfd_check_format","Import","Array","((%rdi)+8)+240").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+240)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+272)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+280)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+288)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+296)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+304)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+312)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+320)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+328)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+336)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+344)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+352)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+360)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+368)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+376)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+384)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+392)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+400)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+408)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+416)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+424)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+432)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+440)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+448)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+456)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+464)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+472)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+480)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+488)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+496)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+504)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+512)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+520)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+528)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+536)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+544)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+552)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+560)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+568)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+576)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+584)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+592)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+600)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+608)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+616)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+624)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+632)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+640)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+648)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+656)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+664)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+672)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+680)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+688)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+696)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+704)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+712)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+720)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+728)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+736)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+744)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+752)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+760)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+768)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+776)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+784)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+792)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+800)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+808)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+816)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+824)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+832)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+840)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+848)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+856)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+8)+864)").
abi_typelocation("b","bfd_check_format","Import","Opaque","(((%rdi)+8)+872)").
abi_typelocation("b","bfd_check_format","Import","Void","((%rdi)+16)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+24))").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+24)+8)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+24)+16)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+24)+24)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+24)+32)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+24)+40)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+24)+48)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+24)+56)").
abi_typelocation("b","bfd_check_format","Import","Opaque","((%rdi)+32)").
abi_typelocation("b","bfd_check_format","Import","Opaque","((%rdi)+40)").
abi_typelocation("b","bfd_check_format","Import","Integer64","(%rdi)+48").
abi_typelocation("b","bfd_check_format","Import","Integer64","(%rdi)+56").
abi_typelocation("b","bfd_check_format","Import","Integer32","(%rdi)+64").
abi_typelocation("b","bfd_check_format","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_check_format","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_check_format","Import","Integer32","(%rdi)+72").
abi_typelocation("b","bfd_check_format","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_check_format","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_check_format","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_check_format","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_check_format","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_check_format","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_check_format","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_check_format","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_check_format","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_check_format","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_check_format","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_check_format","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_check_format","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_check_format","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_check_format","Import","Integer32","(%rdi)").
abi_typelocation("b","bfd_check_format","Import","Opaque","((%rdi)+80)").
abi_typelocation("b","bfd_check_format","Import","Integer64","(%rdi)+88").
abi_typelocation("b","bfd_check_format","Import","Integer64","(%rdi)+96").
abi_typelocation("b","bfd_check_format","Import","Opaque","((((%rdi)+104)))").
abi_typelocation("b","bfd_check_format","Import","Integer8","((((%rdi)+104))+8)").
abi_typelocation("b","bfd_check_format","Import","Integer64","(((%rdi)+104))+16").
abi_typelocation("b","bfd_check_format","Import","Void","((%rdi)+112)").
abi_typelocation("b","bfd_check_format","Import","Void","((%rdi)+120)").
abi_typelocation("b","bfd_check_format","Import","Integer32","(%rdi)+128").
abi_typelocation("b","bfd_check_format","Import","Integer32","(%rdi)+132").
abi_typelocation("b","bfd_check_format","Import","Integer32","(%rdi)+136").
abi_typelocation("b","bfd_check_format","Import","Integer32","(%rdi)+104").
abi_typelocation("b","bfd_check_format","Import","Opaque","((%rdi)+144)").
abi_typelocation("b","bfd_check_format","Import","Opaque","((%rdi)+152)").
abi_typelocation("b","bfd_check_format","Import","Integer32","(%rdi)+160").
abi_typelocation("b","bfd_check_format","Import","Integer32","(%rdi)+164").
abi_typelocation("b","bfd_check_format","Import","Integer64","(%rdi)+168").
abi_typelocation("b","bfd_check_format","Import","Opaque","((%rdi)+176)").
abi_typelocation("b","bfd_check_format","Import","Integer32","(%rdi)+184").
abi_typelocation("b","bfd_check_format","Import","Integer32","(%rdi)+188").
abi_typelocation("b","bfd_check_format","Import","Integer32","((%rdi)+192)").
abi_typelocation("b","bfd_check_format","Import","Integer32","((%rdi)+192)+4").
abi_typelocation("b","bfd_check_format","Import","Integer32","((%rdi)+192)+8").
abi_typelocation("b","bfd_check_format","Import","Integer32","((%rdi)+192)+12").
abi_typelocation("b","bfd_check_format","Import","Integer64","((%rdi)+192)+16").
abi_typelocation("b","bfd_check_format","Import","Integer8","(((%rdi)+192)+24)").
abi_typelocation("b","bfd_check_format","Import","Integer8","(((%rdi)+192)+32)").
abi_typelocation("b","bfd_check_format","Import","Integer32","((%rdi)+192)+40").
abi_typelocation("b","bfd_check_format","Import","Integer32","((%rdi)+192)+44").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+192)+48)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+192)+56)").
abi_typelocation("b","bfd_check_format","Import","Void","(((%rdi)+192)+64)").
abi_typelocation("b","bfd_check_format","Import","Opaque","(((%rdi)+192)+72)").
abi_typelocation("b","bfd_check_format","Import","Integer32","((%rdi)+192)+80").
abi_typelocation("b","bfd_check_format","Import","Void","((%rdi)+200)").
abi_typelocation("b","bfd_check_format","Import","Opaque","((%rdi)+208)").
abi_typelocation("b","bfd_check_format","Import","Opaque","((%rdi)+216)").
abi_typelocation("b","bfd_check_format","Import","Opaque","((%rdi)+224)").
abi_typelocation("b","bfd_check_format","Import","Opaque","((%rdi)+232)").
abi_typelocation("b","bfd_check_format","Import","Union","(%rdi)+240").
abi_typelocation("b","bfd_check_format","Import","Union","(%rdi)+248").
abi_typelocation("b","bfd_check_format","Import","Void","((%rdi)+256)").
abi_typelocation("b","bfd_check_format","Import","Void","((%rdi)+264)").
abi_typelocation("b","bfd_check_format","Import","Integer64","((%rdi)+272)").
abi_typelocation("b","bfd_check_format","Import","Array[1:1]","((%rdi)+272)+8").
abi_typelocation("b","bfd_check_format","Import","Integer8","((%rdi)+272)+8").
abi_typelocation("b","bfd_check_format","Import","Integer32","%rsi").
abi_typelocation("b","bfd_check_format","Export","Integer32","%rax").
abi_typelocation("b","bfd_get_error","Export","Integer32","%rax").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer64","%rdi").
abi_typelocation("b","bfd_get_error","Export","Void","()").
abi_typelocation("b","bfd_get_section_by_name","Export","Void","()").
abi_typelocation("b","bfd_malloc_and_get_section","Import","Void","()").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","(%rdi)").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer8","()").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer64","+8").
abi_typelocation("b","bfd_malloc_and_get_section","Import","Integer8","()").
abi_typelocation("b","bfd_malloc_and_get_section","Import","Integer64","+8").
abi_typelocation("b","bfd_get_section_by_name","Export","Void","()").
abi_typelocation("b","bfd_malloc_and_get_section","Import","Void","()").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","(%rdi)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","(%rdi)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","(%rdi)").
abi_typelocation("b","bfd_get_section_by_name","Both","Void","((%rdi))").
abi_typelocation("b","bfd_get_section_by_name","Both","Void","((%rdi))").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer64","%rdi").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","(%rdi)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","(%rdi)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","(%rdi)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","(%rdi)").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer8","(())").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer8","((()+8))").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","(()+8)+8").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","(()+8)+12").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","(()+8)+16").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","(()+8)+20").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","(()+8)+24").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer8","(()+8)+28").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer8","(()+8)+29").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer8","(()+8)+30").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer8","(()+8)+31").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+32)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+40)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+48)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+56)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+64)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+72)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+80)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+88)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+96)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+104)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+112)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+120)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+128)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+136)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+144)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+152)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+160)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+168)").
abi_typelocation("b","bfd_get_section_by_name","Import","Array[32:4]","(()+8)+176").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+176)").
abi_typelocation("b","bfd_get_section_by_name","Import","Array[32:4]","(()+8)+208").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+208)").
abi_typelocation("b","bfd_get_section_by_name","Import","Array","(()+8)+240").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+240)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+272)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+280)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+288)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+296)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+304)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+312)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+320)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+328)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+336)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+344)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+352)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+360)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+368)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+376)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+384)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+392)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+400)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+408)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+416)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+424)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+432)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+440)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+448)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+456)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+464)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+472)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+480)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+488)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+496)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+504)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+512)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+520)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+528)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+536)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+544)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+552)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+560)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+568)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+576)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+584)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+592)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+600)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+608)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+616)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+624)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+632)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+640)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+648)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+656)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+664)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+672)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+680)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+688)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+696)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+704)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+712)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+720)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+728)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+736)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+744)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+752)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+760)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+768)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+776)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+784)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+792)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+800)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+808)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+816)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+824)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+832)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+840)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+848)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+856)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+8)+864)").
abi_typelocation("b","bfd_get_section_by_name","Import","Opaque","((()+8)+872)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","(()+16)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+24))").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+24)+8)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+24)+16)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+24)+24)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+24)+32)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+24)+40)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+24)+48)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+24)+56)").
abi_typelocation("b","bfd_get_section_by_name","Import","Opaque","(()+32)").
abi_typelocation("b","bfd_get_section_by_name","Import","Opaque","(()+40)").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer64","()+48").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer64","()+56").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","()+64").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","()").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","()").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","()+72").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","()").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","()").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","()").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","()").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","()").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","()").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","()").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","()").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","()").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","()").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","()").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","()").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","()").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","()").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","()").
abi_typelocation("b","bfd_get_section_by_name","Import","Opaque","(()+80)").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer64","()+88").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer64","()+96").
abi_typelocation("b","bfd_get_section_by_name","Import","Opaque","(((()+104)))").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer8","(((()+104))+8)").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer64","((()+104))+16").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","(()+112)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","(()+120)").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","()+128").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","()+132").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","()+136").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","()+104").
abi_typelocation("b","bfd_get_section_by_name","Import","Opaque","(()+144)").
abi_typelocation("b","bfd_get_section_by_name","Import","Opaque","(()+152)").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","()+160").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","()+164").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer64","()+168").
abi_typelocation("b","bfd_get_section_by_name","Import","Opaque","(()+176)").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","()+184").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","()+188").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","(()+192)").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","(()+192)+4").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","(()+192)+8").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","(()+192)+12").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer64","(()+192)+16").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer8","((()+192)+24)").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer8","((()+192)+32)").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","(()+192)+40").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","(()+192)+44").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+192)+48)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+192)+56)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","((()+192)+64)").
abi_typelocation("b","bfd_get_section_by_name","Import","Opaque","((()+192)+72)").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer32","(()+192)+80").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","(()+200)").
abi_typelocation("b","bfd_get_section_by_name","Import","Opaque","(()+208)").
abi_typelocation("b","bfd_get_section_by_name","Import","Opaque","(()+216)").
abi_typelocation("b","bfd_get_section_by_name","Import","Opaque","(()+224)").
abi_typelocation("b","bfd_get_section_by_name","Import","Opaque","(()+232)").
abi_typelocation("b","bfd_get_section_by_name","Import","Union","()+240").
abi_typelocation("b","bfd_get_section_by_name","Import","Union","()+248").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","(()+256)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","(()+264)").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer64","(()+272)").
abi_typelocation("b","bfd_get_section_by_name","Import","Array[1:1]","(()+272)+8").
abi_typelocation("b","bfd_get_section_by_name","Import","Integer8","(()+272)+8").
abi_typelocation("b","bfd_get_section_by_name","Both","Void","(%rdi)").
abi_typelocation("b","bfd_get_section_by_name","Both","Void","(%rdi)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","(%rdi)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","(%rdi)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","(%rdi)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","(%rdi)").
abi_typelocation("b","bfd_get_section_by_name","Import","Void","(%rdi)").
abi_typelocation("b","bfd_get_error","Import","Opaque","((()))").
abi_typelocation("b","bfd_get_error","Import","Integer8","((())+8)").
abi_typelocation("b","bfd_get_error","Import","Integer32","(())").
abi_typelocation("b","bfd_get_error","Import","Integer32","(())").
abi_typelocation("b","bfd_get_error","Import","Integer32","(())").
abi_typelocation("b","bfd_get_error","Import","Integer32","(())").
abi_typelocation("b","bfd_get_error","Import","Void","(()+8)").
abi_typelocation("b","bfd_get_error","Import","Opaque","((()+16))").
abi_typelocation("b","bfd_get_error","Import","Integer8","((()+16)+8)").
abi_typelocation("b","bfd_get_error","Import","Integer32","(()+16)").
abi_typelocation("b","bfd_get_error","Import","Integer32","(()+16)").
abi_typelocation("b","bfd_get_error","Import","Integer32","(()+16)").
abi_typelocation("b","bfd_get_error","Import","Integer32","(()+16)").
abi_typelocation("b","bfd_get_error","Import","Integer32","()+24").
abi_typelocation("b","bfd_get_error","Import","Void","(()+32)").
abi_typelocation("b","bfd_check_format","Import","Opaque","(unknown)").
