
%============================================================================
% Library Facts
%============================================================================

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-11.2.0/hdf5-develop-1.13-46nvbppu74g535ic7ojueo3xofi4jmfm/lib/libhdf5_tools.so.1000
%----------------------------------------------------------------------------
abi_typelocation("a","ompi_mpi_comm_world","Import","Empty","none").
abi_typelocation("a","ompi_mpi_char","Import","Empty","none").
abi_typelocation("a","ompi_mpi_byte","Import","Empty","none").
abi_typelocation("a","H5T_IEEE_F32BE_g","Import","Integer16","var").
abi_typelocation("a","H5T_IEEE_F32BE_g","Import","Integer16","var+2").
abi_typelocation("a","H5T_IEEE_F32BE_g","Import","Integer32","var").
abi_typelocation("a","H5T_IEEE_F32BE_g","Import","Array[8:8]","var").
abi_typelocation("a","H5T_IEEE_F32BE_g","Import","Integer8","var").
abi_typelocation("a","H5T_IEEE_F32LE_g","Import","Integer16","var").
abi_typelocation("a","H5T_IEEE_F32LE_g","Import","Integer16","var+2").
abi_typelocation("a","H5T_IEEE_F32LE_g","Import","Integer32","var").
abi_typelocation("a","H5T_IEEE_F32LE_g","Import","Array[8:8]","var").
abi_typelocation("a","H5T_IEEE_F32LE_g","Import","Integer8","var").
abi_typelocation("a","H5T_IEEE_F64BE_g","Import","Integer16","var").
abi_typelocation("a","H5T_IEEE_F64BE_g","Import","Integer16","var+2").
abi_typelocation("a","H5T_IEEE_F64BE_g","Import","Integer32","var").
abi_typelocation("a","H5T_IEEE_F64BE_g","Import","Array[8:8]","var").
abi_typelocation("a","H5T_IEEE_F64BE_g","Import","Integer8","var").
abi_typelocation("a","H5T_IEEE_F64LE_g","Import","Integer16","var").
abi_typelocation("a","H5T_IEEE_F64LE_g","Import","Integer16","var+2").
abi_typelocation("a","H5T_IEEE_F64LE_g","Import","Integer32","var").
abi_typelocation("a","H5T_IEEE_F64LE_g","Import","Array[8:8]","var").
abi_typelocation("a","H5T_IEEE_F64LE_g","Import","Integer8","var").
abi_typelocation("a","H5T_STD_I8BE_g","Import","Integer16","var").
abi_typelocation("a","H5T_STD_I8BE_g","Import","Integer16","var+2").
abi_typelocation("a","H5T_STD_I8BE_g","Import","Integer32","var").
abi_typelocation("a","H5T_STD_I8BE_g","Import","Array[8:8]","var").
abi_typelocation("a","H5T_STD_I8BE_g","Import","Integer8","var").
abi_typelocation("a","H5T_STD_I8LE_g","Import","Integer16","var").
abi_typelocation("a","H5T_STD_I8LE_g","Import","Integer16","var+2").
abi_typelocation("a","H5T_STD_I8LE_g","Import","Integer32","var").
abi_typelocation("a","H5T_STD_I8LE_g","Import","Array[8:8]","var").
abi_typelocation("a","H5T_STD_I8LE_g","Import","Integer8","var").
abi_typelocation("a","H5T_STD_I16BE_g","Import","Integer16","var").
abi_typelocation("a","H5T_STD_I16BE_g","Import","Integer16","var+2").
abi_typelocation("a","H5T_STD_I16BE_g","Import","Integer32","var").
abi_typelocation("a","H5T_STD_I16BE_g","Import","Array[8:8]","var").
abi_typelocation("a","H5T_STD_I16BE_g","Import","Integer8","var").
abi_typelocation("a","H5T_STD_I16LE_g","Import","Integer16","var").
abi_typelocation("a","H5T_STD_I16LE_g","Import","Integer16","var+2").
abi_typelocation("a","H5T_STD_I16LE_g","Import","Integer32","var").
abi_typelocation("a","H5T_STD_I16LE_g","Import","Array[8:8]","var").
abi_typelocation("a","H5T_STD_I16LE_g","Import","Integer8","var").
abi_typelocation("a","H5T_STD_I32BE_g","Import","Integer16","var").
abi_typelocation("a","H5T_STD_I32BE_g","Import","Integer16","var+2").
abi_typelocation("a","H5T_STD_I32BE_g","Import","Integer32","var").
abi_typelocation("a","H5T_STD_I32BE_g","Import","Array[8:8]","var").
abi_typelocation("a","H5T_STD_I32BE_g","Import","Integer8","var").
abi_typelocation("a","H5T_STD_I32LE_g","Import","Integer16","var").
abi_typelocation("a","H5T_STD_I32LE_g","Import","Integer16","var+2").
abi_typelocation("a","H5T_STD_I32LE_g","Import","Integer32","var").
abi_typelocation("a","H5T_STD_I32LE_g","Import","Array[8:8]","var").
abi_typelocation("a","H5T_STD_I32LE_g","Import","Integer8","var").
abi_typelocation("a","H5T_STD_I64BE_g","Import","Integer16","var").
abi_typelocation("a","H5T_STD_I64BE_g","Import","Integer16","var+2").
abi_typelocation("a","H5T_STD_I64BE_g","Import","Integer32","var").
abi_typelocation("a","H5T_STD_I64BE_g","Import","Array[8:8]","var").
abi_typelocation("a","H5T_STD_I64BE_g","Import","Integer8","var").
abi_typelocation("a","H5T_STD_I64LE_g","Import","Integer16","var").
abi_typelocation("a","H5T_STD_I64LE_g","Import","Integer16","var+2").
abi_typelocation("a","H5T_STD_I64LE_g","Import","Integer32","var").
abi_typelocation("a","H5T_STD_I64LE_g","Import","Array[8:8]","var").
abi_typelocation("a","H5T_STD_I64LE_g","Import","Integer8","var").
abi_typelocation("a","H5T_STD_U8BE_g","Import","Integer16","var").
abi_typelocation("a","H5T_STD_U8BE_g","Import","Integer16","var+2").
abi_typelocation("a","H5T_STD_U8BE_g","Import","Integer32","var").
abi_typelocation("a","H5T_STD_U8BE_g","Import","Array[8:8]","var").
abi_typelocation("a","H5T_STD_U8BE_g","Import","Integer8","var").
abi_typelocation("a","H5T_STD_U8LE_g","Import","Integer16","var").
abi_typelocation("a","H5T_STD_U8LE_g","Import","Integer16","var+2").
abi_typelocation("a","H5T_STD_U8LE_g","Import","Integer32","var").
abi_typelocation("a","H5T_STD_U8LE_g","Import","Array[8:8]","var").
abi_typelocation("a","H5T_STD_U8LE_g","Import","Integer8","var").
abi_typelocation("a","H5T_STD_U16BE_g","Import","Integer16","var").
abi_typelocation("a","H5T_STD_U16BE_g","Import","Integer16","var+2").
abi_typelocation("a","H5T_STD_U16BE_g","Import","Integer32","var").
abi_typelocation("a","H5T_STD_U16BE_g","Import","Array[8:8]","var").
abi_typelocation("a","H5T_STD_U16BE_g","Import","Integer8","var").
abi_typelocation("a","H5T_STD_U16LE_g","Import","Integer16","var").
abi_typelocation("a","H5T_STD_U16LE_g","Import","Integer16","var+2").
abi_typelocation("a","H5T_STD_U16LE_g","Import","Integer32","var").
abi_typelocation("a","H5T_STD_U16LE_g","Import","Array[8:8]","var").
abi_typelocation("a","H5T_STD_U16LE_g","Import","Integer8","var").
abi_typelocation("a","H5T_STD_U32BE_g","Import","Integer16","var").
abi_typelocation("a","H5T_STD_U32BE_g","Import","Integer16","var+2").
abi_typelocation("a","H5T_STD_U32BE_g","Import","Integer32","var").
abi_typelocation("a","H5T_STD_U32BE_g","Import","Array[8:8]","var").
abi_typelocation("a","H5T_STD_U32BE_g","Import","Integer8","var").
abi_typelocation("a","H5T_STD_U32LE_g","Import","Integer16","var").
abi_typelocation("a","H5T_STD_U32LE_g","Import","Integer16","var+2").
abi_typelocation("a","H5T_STD_U32LE_g","Import","Integer32","var").
abi_typelocation("a","H5T_STD_U32LE_g","Import","Array[8:8]","var").
abi_typelocation("a","H5T_STD_U32LE_g","Import","Integer8","var").
abi_typelocation("a","H5T_STD_U64BE_g","Import","Integer16","var").
abi_typelocation("a","H5T_STD_U64BE_g","Import","Integer16","var+2").
abi_typelocation("a","H5T_STD_U64BE_g","Import","Integer32","var").
abi_typelocation("a","H5T_STD_U64BE_g","Import","Array[8:8]","var").
abi_typelocation("a","H5T_STD_U64BE_g","Import","Integer8","var").
abi_typelocation("a","H5T_STD_U64LE_g","Import","Integer16","var").
abi_typelocation("a","H5T_STD_U64LE_g","Import","Integer16","var+2").
abi_typelocation("a","H5T_STD_U64LE_g","Import","Integer32","var").
abi_typelocation("a","H5T_STD_U64LE_g","Import","Array[8:8]","var").
abi_typelocation("a","H5T_STD_U64LE_g","Import","Integer8","var").
abi_typelocation("a","H5T_STD_B8BE_g","Import","Integer16","var").
abi_typelocation("a","H5T_STD_B8BE_g","Import","Integer16","var+2").
abi_typelocation("a","H5T_STD_B8BE_g","Import","Integer32","var").
abi_typelocation("a","H5T_STD_B8BE_g","Import","Array[8:8]","var").
abi_typelocation("a","H5T_STD_B8BE_g","Import","Integer8","var").
abi_typelocation("a","H5T_STD_B8LE_g","Import","Integer16","var").
abi_typelocation("a","H5T_STD_B8LE_g","Import","Integer16","var+2").
abi_typelocation("a","H5T_STD_B8LE_g","Import","Integer32","var").
abi_typelocation("a","H5T_STD_B8LE_g","Import","Array[8:8]","var").
abi_typelocation("a","H5T_STD_B8LE_g","Import","Integer8","var").
abi_typelocation("a","H5T_STD_B16BE_g","Import","Integer16","var").
abi_typelocation("a","H5T_STD_B16BE_g","Import","Integer16","var+2").
abi_typelocation("a","H5T_STD_B16BE_g","Import","Integer32","var").
abi_typelocation("a","H5T_STD_B16BE_g","Import","Array[8:8]","var").
abi_typelocation("a","H5T_STD_B16BE_g","Import","Integer8","var").
abi_typelocation("a","H5T_STD_B16LE_g","Import","Integer16","var").
abi_typelocation("a","H5T_STD_B16LE_g","Import","Integer16","var+2").
abi_typelocation("a","H5T_STD_B16LE_g","Import","Integer32","var").
abi_typelocation("a","H5T_STD_B16LE_g","Import","Array[8:8]","var").
abi_typelocation("a","H5T_STD_B16LE_g","Import","Integer8","var").
abi_typelocation("a","H5T_STD_B32BE_g","Import","Integer16","var").
abi_typelocation("a","H5T_STD_B32BE_g","Import","Integer16","var+2").
abi_typelocation("a","H5T_STD_B32BE_g","Import","Integer32","var").
abi_typelocation("a","H5T_STD_B32BE_g","Import","Array[8:8]","var").
abi_typelocation("a","H5T_STD_B32BE_g","Import","Integer8","var").
abi_typelocation("a","H5T_STD_B32LE_g","Import","Integer16","var").
abi_typelocation("a","H5T_STD_B32LE_g","Import","Integer16","var+2").
abi_typelocation("a","H5T_STD_B32LE_g","Import","Integer32","var").
abi_typelocation("a","H5T_STD_B32LE_g","Import","Array[8:8]","var").
abi_typelocation("a","H5T_STD_B32LE_g","Import","Integer8","var").
abi_typelocation("a","H5T_STD_B64BE_g","Import","Integer16","var").
abi_typelocation("a","H5T_STD_B64BE_g","Import","Integer16","var+2").
abi_typelocation("a","H5T_STD_B64BE_g","Import","Integer32","var").
abi_typelocation("a","H5T_STD_B64BE_g","Import","Array[8:8]","var").
abi_typelocation("a","H5T_STD_B64BE_g","Import","Integer8","var").
abi_typelocation("a","H5T_STD_B64LE_g","Import","Integer16","var").
abi_typelocation("a","H5T_STD_B64LE_g","Import","Integer16","var+2").
abi_typelocation("a","H5T_STD_B64LE_g","Import","Integer32","var").
abi_typelocation("a","H5T_STD_B64LE_g","Import","Array[8:8]","var").
abi_typelocation("a","H5T_STD_B64LE_g","Import","Integer8","var").
abi_typelocation("a","H5P_CLS_LINK_ACCESS_ID_g","Import","Integer32","var").
abi_typelocation("a","H5Gclose","Import","Integer64","%rdi").
abi_typelocation("a","H5Gclose","Export","Integer32","%rax").
abi_typelocation("a","H5Gopen2","Import","Integer64","%rdi").
abi_typelocation("a","H5Gopen2","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Gopen2","Import","Integer64","%rdx").
abi_typelocation("a","H5Gopen2","Export","Integer64","%rax").
abi_typelocation("a","H5Tclose","Import","Integer64","%rdi").
abi_typelocation("a","H5Tclose","Export","Integer32","%rax").
abi_typelocation("a","H5Tequal","Import","Integer64","%rdi").
abi_typelocation("a","H5Tequal","Import","Integer64","%rsi").
abi_typelocation("a","H5Tequal","Export","Integer32","%rax").
abi_typelocation("a","H5Topen2","Import","Integer64","%rdi").
abi_typelocation("a","H5Topen2","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Topen2","Import","Integer64","%rdx").
abi_typelocation("a","H5Topen2","Export","Integer64","%rax").
abi_typelocation("a","H5Dclose","Import","Integer64","%rdi").
abi_typelocation("a","H5Dclose","Export","Integer32","%rax").
abi_typelocation("a","H5Dopen2","Import","Integer64","%rdi").
abi_typelocation("a","H5Dopen2","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Dopen2","Import","Integer64","%rdx").
abi_typelocation("a","H5Dopen2","Export","Integer64","%rax").
abi_typelocation("a","MPI_Finalize","Export","Integer32","%rax").
abi_typelocation("a","MPI_Probe","Import","Integer32","%rdi").
abi_typelocation("a","MPI_Probe","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Probe","Import","Empty","(%rdx)").
abi_typelocation("a","MPI_Probe","Import","Integer32","(%rcx)").
abi_typelocation("a","MPI_Probe","Import","Integer32","(%rcx)+4").
abi_typelocation("a","MPI_Probe","Import","Integer32","(%rcx)+8").
abi_typelocation("a","MPI_Probe","Import","Integer32","(%rcx)+12").
abi_typelocation("a","MPI_Probe","Import","Integer64","(%rcx)+16").
abi_typelocation("a","MPI_Probe","Export","Integer32","%rax").
abi_typelocation("a","MPI_Recv","Both","Void","(%rdi)").
abi_typelocation("a","MPI_Recv","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Recv","Import","Empty","(%rdx)").
abi_typelocation("a","MPI_Recv","Import","Integer32","%rcx").
abi_typelocation("a","MPI_Recv","Import","Integer32","%r8").
abi_typelocation("a","MPI_Recv","Import","Empty","(%r9)").
abi_typelocation("a","MPI_Recv","Import","Integer32","(framebase+8)").
abi_typelocation("a","MPI_Recv","Import","Integer32","(framebase+8)+4").
abi_typelocation("a","MPI_Recv","Import","Integer32","(framebase+8)+8").
abi_typelocation("a","MPI_Recv","Import","Integer32","(framebase+8)+12").
abi_typelocation("a","MPI_Recv","Import","Integer64","(framebase+8)+16").
abi_typelocation("a","MPI_Recv","Export","Integer32","%rax").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","%rdi").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Iprobe","Import","Empty","(%rdx)").
abi_typelocation("a","MPI_Iprobe","Both","Integer32","(%rcx)").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","(%r8)").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","(%r8)+4").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","(%r8)+8").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","(%r8)+12").
abi_typelocation("a","MPI_Iprobe","Import","Integer64","(%r8)+16").
abi_typelocation("a","MPI_Iprobe","Export","Integer32","%rax").
abi_typelocation("a","H5Otoken_cmp","Import","Integer64","%rdi").
abi_typelocation("a","H5Otoken_cmp","Import","Array[16:16]","(%rsi)").
abi_typelocation("a","H5Otoken_cmp","Import","Integer8","(%rsi)").
abi_typelocation("a","H5Otoken_cmp","Import","Array[16:16]","(%rdx)").
abi_typelocation("a","H5Otoken_cmp","Import","Integer8","(%rdx)").
abi_typelocation("a","H5Otoken_cmp","Both","Integer32","(%rcx)").
abi_typelocation("a","H5Otoken_cmp","Export","Integer32","%rax").
abi_typelocation("a","H5Lunpack_elink_val","Import","Integer64","%rsi").
abi_typelocation("a","H5Lunpack_elink_val","Both","Integer32","(%rdx)").
abi_typelocation("a","H5Lunpack_elink_val","Both","Integer8","((%rcx))").
abi_typelocation("a","H5Lunpack_elink_val","Both","Integer8","((%r8))").
abi_typelocation("a","H5Lunpack_elink_val","Export","Integer32","%rax").
abi_typelocation("a","H5Pclose","Import","Integer64","%rdi").
abi_typelocation("a","H5Pclose","Export","Integer32","%rax").
abi_typelocation("a","H5Fclose","Import","Integer64","%rdi").
abi_typelocation("a","H5Fclose","Export","Integer32","%rax").
abi_typelocation("a","H5Eset_auto1","Import","Void","(%rdi)").
abi_typelocation("a","H5Eset_auto1","Both","Void","(%rsi)").
abi_typelocation("a","H5Eset_auto1","Export","Integer32","%rax").
abi_typelocation("a","H5Eget_auto1","Both","Void","((%rdi))").
abi_typelocation("a","H5Eget_auto1","Both","Void","((%rsi))").
abi_typelocation("a","H5Eget_auto1","Export","Integer32","%rax").
abi_typelocation("a","H5Eset_auto2","Import","Integer64","%rdi").
abi_typelocation("a","H5Eset_auto2","Import","Void","(%rsi)").
abi_typelocation("a","H5Eset_auto2","Both","Void","(%rdx)").
abi_typelocation("a","H5Eset_auto2","Export","Integer32","%rax").
abi_typelocation("a","H5Eget_auto2","Import","Integer64","%rdi").
abi_typelocation("a","H5Eget_auto2","Both","Void","((%rsi))").
abi_typelocation("a","H5Eget_auto2","Both","Void","((%rdx))").
abi_typelocation("a","H5Eget_auto2","Export","Integer32","%rax").
abi_typelocation("a","H5Eauto_is_v2","Import","Integer64","%rdi").
abi_typelocation("a","H5Eauto_is_v2","Both","Integer32","(%rsi)").
abi_typelocation("a","H5Eauto_is_v2","Export","Integer32","%rax").
abi_typelocation("a","MPI_Abort","Import","Empty","(%rdi)").
abi_typelocation("a","MPI_Abort","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Abort","Export","Integer32","%rax").
abi_typelocation("a","H5Oget_info_by_name3","Import","Integer64","%rdi").
abi_typelocation("a","H5Oget_info_by_name3","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Oget_info_by_name3","Import","Integer64","(%rdx)").
abi_typelocation("a","H5Oget_info_by_name3","Import","Array[16:16]","(%rdx)+8").
abi_typelocation("a","H5Oget_info_by_name3","Import","Integer8","(%rdx)+8").
abi_typelocation("a","H5Oget_info_by_name3","Import","Integer32","(%rdx)+24").
abi_typelocation("a","H5Oget_info_by_name3","Import","Integer32","(%rdx)+28").
abi_typelocation("a","H5Oget_info_by_name3","Import","Integer64","(%rdx)+32").
abi_typelocation("a","H5Oget_info_by_name3","Import","Integer64","(%rdx)+40").
abi_typelocation("a","H5Oget_info_by_name3","Import","Integer64","(%rdx)+48").
abi_typelocation("a","H5Oget_info_by_name3","Import","Integer64","(%rdx)+56").
abi_typelocation("a","H5Oget_info_by_name3","Import","Integer64","(%rdx)+64").
abi_typelocation("a","H5Oget_info_by_name3","Import","Integer32","%rcx").
abi_typelocation("a","H5Oget_info_by_name3","Import","Integer64","%r8").
abi_typelocation("a","H5Oget_info_by_name3","Export","Integer32","%rax").
abi_typelocation("a","H5Lget_info2","Import","Integer64","%rdi").
abi_typelocation("a","H5Lget_info2","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Lget_info2","Import","Integer32","(%rdx)").
abi_typelocation("a","H5Lget_info2","Import","Integer8","(%rdx)+4").
abi_typelocation("a","H5Lget_info2","Import","Integer64","(%rdx)+8").
abi_typelocation("a","H5Lget_info2","Import","Integer32","(%rdx)+16").
abi_typelocation("a","H5Lget_info2","Import","Union","(%rdx)+24").
abi_typelocation("a","H5Lget_info2","Import","Integer64","%rcx").
abi_typelocation("a","H5Lget_info2","Export","Integer32","%rax").
abi_typelocation("a","H5Lexists","Import","Integer64","%rdi").
abi_typelocation("a","H5Lexists","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Lexists","Import","Integer64","%rdx").
abi_typelocation("a","H5Lexists","Export","Integer32","%rax").
abi_typelocation("a","H5Epush2","Import","Integer64","%rdi").
abi_typelocation("a","H5Epush2","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Epush2","Both","Integer8","(%rdx)").
abi_typelocation("a","H5Epush2","Import","Integer32","%rcx").
abi_typelocation("a","H5Epush2","Import","Integer64","%r8").
abi_typelocation("a","H5Epush2","Import","Integer64","%r9").
abi_typelocation("a","H5Epush2","Import","Integer64","framebase+8").
abi_typelocation("a","H5Epush2","Both","Integer8","(framebase+16)").
abi_typelocation("a","H5Epush2","Export","Integer32","%rax").
abi_typelocation("a","MPI_Send","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Send","Import","Empty","(%rdx)").
abi_typelocation("a","MPI_Send","Import","Integer32","%rcx").
abi_typelocation("a","MPI_Send","Import","Integer32","%r8").
abi_typelocation("a","MPI_Send","Import","Empty","(%r9)").
abi_typelocation("a","MPI_Send","Export","Integer32","%rax").
abi_typelocation("a","H5Sget_select_elem_pointlist","Import","Integer64","()").
abi_typelocation("a","H5Sget_select_elem_pointlist","Import","Integer32","+8").
abi_typelocation("a","H5Sget_select_elem_pointlist","Import","Empty","(%rax)").
abi_typelocation("a","H5free_memory","Import","Empty","(%rax)").
abi_typelocation("a","H5Otoken_to_str","Import","Empty","(%rax)").
abi_typelocation("a","H5Oget_info3","Import","Empty","(%rax)").
abi_typelocation("a","H5Sget_select_hyper_blocklist","Import","Integer64","()").
abi_typelocation("a","H5Sget_select_hyper_blocklist","Import","Integer32","+8").
abi_typelocation("a","H5Sget_select_hyper_blocklist","Import","Empty","(%rax)").
abi_typelocation("a","H5Rdestroy","Import","Empty","(%rax)").
abi_typelocation("a","H5Aclose","Import","Empty","(%rax)").
abi_typelocation("a","H5Oclose","Import","Empty","(%rax)").
abi_typelocation("a","H5Sclose","Import","Empty","(%rax)").
abi_typelocation("a","H5Dclose","Import","Empty","(%rax)").
abi_typelocation("a","H5Rget_obj_type3","Import","Empty","(%rax)").
abi_typelocation("a","H5Rget_type","Import","Integer32","(%rdi)").
abi_typelocation("a","H5Rget_type","Import","Integer32","(%rdi)+4").
abi_typelocation("a","H5Rget_type","Import","Integer32","(%rdi)+8").
abi_typelocation("a","H5Rget_type","Import","Integer32","(%rdi)+12").
abi_typelocation("a","H5Rget_type","Import","Integer32","(%rdi)+16").
abi_typelocation("a","H5Rget_type","Import","Integer32","(%rdi)+20").
abi_typelocation("a","H5Rget_type","Import","Integer32","(%rdi)+24").
abi_typelocation("a","H5Rget_type","Import","Integer32","(%rdi)+28").
abi_typelocation("a","H5Rget_type","Import","Integer32","(%rdi)+32").
abi_typelocation("a","H5Rget_type","Import","Float64","(%rdi)+40").
abi_typelocation("a","H5Rget_type","Import","Integer32","(%rdi)+48").
abi_typelocation("a","H5Rget_type","Import","Integer32","(%rdi)+52").
abi_typelocation("a","H5Rget_type","Import","Float64","(%rdi)+56").
abi_typelocation("a","H5Rget_type","Import","Integer8","(%rdi)+64").
abi_typelocation("a","H5Rget_type","Import","Integer32","(%rdi)+68").
abi_typelocation("a","H5Rget_type","Import","Integer32","(%rdi)+72").
abi_typelocation("a","H5Rget_type","Import","Integer32","(%rdi)+76").
abi_typelocation("a","H5Rget_type","Import","Integer32","(%rdi)+80").
abi_typelocation("a","H5Rget_type","Import","Integer32","(%rdi)+84").
abi_typelocation("a","H5Rget_type","Import","Integer32","(%rdi)+88").
abi_typelocation("a","H5Rget_type","Import","Integer32","(%rdi)+92").
abi_typelocation("a","H5Rget_type","Import","Integer8","(((%rdi)+96))").
abi_typelocation("a","H5Rget_type","Import","Integer32","((%rdi)+96)+8").
abi_typelocation("a","H5Rget_type","Import","Opaque","(((%rdi)+96)+16)").
abi_typelocation("a","H5Rget_type","Import","Integer8","(((%rdi)+104))").
abi_typelocation("a","H5Rget_type","Import","Integer32","((%rdi)+104)+8").
abi_typelocation("a","H5Rget_type","Import","Opaque","(((%rdi)+104)+16)").
abi_typelocation("a","H5Rget_type","Import","Integer32","(%rdi)+112").
abi_typelocation("a","H5Rget_type","Import","Integer64","(%rdi)+120").
abi_typelocation("a","H5Rget_type","Import","Integer32","(%rdi)+128").
abi_typelocation("a","H5Rget_type","Import","Integer64","(%rdi)+136").
abi_typelocation("a","H5Rget_type","Import","Integer64","(%rdi)+144").
abi_typelocation("a","H5Rget_type","Import","Integer32","(%rdi)+152").
abi_typelocation("a","H5Rget_type","Import","Integer64","(%rdi)+160").
abi_typelocation("a","H5Rget_type","Import","Integer64","(%rdi)+168").
abi_typelocation("a","H5Rget_type","Import","Array[256:32]","(%rdi)+176").
abi_typelocation("a","H5Rget_type","Import","Integer64","(%rdi)+176").
abi_typelocation("a","H5Rget_type","Import","Array","(%rdi)+432").
abi_typelocation("a","H5Rget_type","Import","Integer64","(%rdi)+432").
abi_typelocation("a","H5Rget_type","Import","Array","(%rdi)+688").
abi_typelocation("a","H5Rget_type","Import","Integer64","(%rdi)+688").
abi_typelocation("a","H5Rget_type","Import","Array","(%rdi)+944").
abi_typelocation("a","H5Rget_type","Import","Integer64","(%rdi)+944").
abi_typelocation("a","H5Rget_type","Import","Array","(%rdi)+1200").
abi_typelocation("a","H5Rget_type","Import","Integer64","(%rdi)+1200").
abi_typelocation("a","H5Rget_type","Import","Array","(%rdi)+1456").
abi_typelocation("a","H5Rget_type","Import","Integer64","(%rdi)+1456").
abi_typelocation("a","H5Rget_type","Import","Array[16:2]","(%rdi)+1712").
abi_typelocation("a","H5Rget_type","Import","Integer8","((%rdi)+1712)").
abi_typelocation("a","H5Rget_type","Import","Array[16:2]","(%rdi)+1728").
abi_typelocation("a","H5Rget_type","Import","Integer64","(((%rdi)+1728))").
abi_typelocation("a","H5Rget_type","Import","Integer32","((%rdi)+1728)+8").
abi_typelocation("a","H5Rget_type","Import","Integer64","(((%rdi)+1728)+16)").
abi_typelocation("a","H5Rget_type","Import","Integer32","((%rdi)+1728)+24").
abi_typelocation("a","H5Rget_type","Import","Integer64","(((%rdi)+1728)+32)").
abi_typelocation("a","H5Rget_type","Import","Integer32","((%rdi)+1728)+40").
abi_typelocation("a","H5Rget_type","Import","Integer64","(((%rdi)+1728)+48)").
abi_typelocation("a","H5Rget_type","Import","Integer32","((%rdi)+1728)+56").
abi_typelocation("a","H5Rget_type","Import","Array[48:2]","(%rdi)+1744").
abi_typelocation("a","H5Rget_type","Import","Integer32","(%rdi)+1744").
abi_typelocation("a","H5Rget_type","Import","Integer8","((%rdi)+1752)").
abi_typelocation("a","H5Rget_type","Import","Union","(%rdi)+1760").
abi_typelocation("a","H5Rget_type","Import","Array[48:2]","(%rdi)+1792").
abi_typelocation("a","H5Rget_type","Import","Integer32","(%rdi)+1792").
abi_typelocation("a","H5Rget_type","Import","Union","(%rdi)+1808").
abi_typelocation("a","H5Rget_type","Import","Array[2:2]","(%rdi)+1840").
abi_typelocation("a","H5Rget_type","Import","Integer8","(%rdi)+1840").
abi_typelocation("a","H5Rget_type","Import","Array","(%rdi)+1842").
abi_typelocation("a","H5Rget_type","Import","Integer8","(%rdi)+1842").
abi_typelocation("a","H5Tget_array_dims2","Import","Integer64","()").
abi_typelocation("a","H5Tget_array_dims2","Import","Integer32","+8").
abi_typelocation("a","H5Tenum_nameof","Import","Empty","(%rax)").
abi_typelocation("a","H5Tclose","Import","Empty","(%rax)").
abi_typelocation("a","H5Pclose","Import","Empty","(%rax)").
abi_typelocation("a","H5Eset_auto1","Import","Empty","(%rax)").
abi_typelocation("a","H5Eget_auto1","Import","Empty","(%rax)").
abi_typelocation("a","H5Eset_auto2","Import","Array","None").
abi_typelocation("a","H5Eset_auto2","Import","Empty","(%rax)").
abi_typelocation("a","H5Eget_auto2","Import","Empty","(%rax)").
abi_typelocation("a","H5Eauto_is_v2","Import","Empty","(%rax)").
abi_typelocation("a","H5Tconvert","Import","Empty","(%rax)").
abi_typelocation("a","H5Epush2","Import","Array[16:16]","unknown").
abi_typelocation("a","H5Epush2","Import","Integer8","unknown").
abi_typelocation("a","H5Epush2","Import","Array[16:16]","unknown").
abi_typelocation("a","H5Epush2","Import","Integer8","unknown").
abi_typelocation("a","H5Epush2","Import","Array[16:16]","unknown").
abi_typelocation("a","H5Epush2","Import","Integer8","unknown").
abi_typelocation("a","H5Epush2","Import","Empty","(%rax)").
abi_typelocation("a","H5Oget_info3","Import","Integer32","%rdi").
abi_typelocation("a","H5Eset_auto1","Import","Integer8","+4").
abi_typelocation("a","H5Eset_auto1","Import","Integer64","+8").
abi_typelocation("a","H5Eset_auto1","Import","Integer32","+16").
abi_typelocation("a","H5Eset_auto1","Import","Union","+24").
abi_typelocation("a","H5Eset_auto1","Both","Void","(%rdi)").
abi_typelocation("a","H5Eset_auto2","Import","Integer8","+4").
abi_typelocation("a","H5Eset_auto2","Import","Integer64","+8").
abi_typelocation("a","H5Eset_auto2","Import","Integer32","+16").
abi_typelocation("a","H5Eset_auto2","Import","Union","+24").
abi_typelocation("a","H5Eset_auto2","Both","Void","(%rdi)").
abi_typelocation("a","H5Treclaim","Both","Void","(%rdi)").
abi_typelocation("a","H5Aread","Both","Void","(%rdi)").
abi_typelocation("a","H5Sget_simple_extent_dims","Export","Integer32","%rax").
abi_typelocation("a","H5Epush2","Import","Integer32","%rdi").
abi_typelocation("a","H5Sget_select_bounds","Both","Void","((%rdi))").
abi_typelocation("a","H5Sget_select_bounds","Both","Void","((%rsi))").
abi_typelocation("a","H5Screate_simple","Both","Void","(%rdi)").
abi_typelocation("a","H5Screate_simple","Both","Void","(%rsi)").
abi_typelocation("a","H5Sselect_hyperslab","Both","Void","(%rdi)").
abi_typelocation("a","H5Sselect_hyperslab","Both","Void","(%rsi)").
abi_typelocation("a","H5Sselect_hyperslab","Both","Void","(%rdx)").
abi_typelocation("a","H5Sselect_hyperslab","Both","Void","(%rcx)").
abi_typelocation("a","H5Pget_layout","Export","Integer64","%rax").
abi_typelocation("a","H5Sget_simple_extent_dims","Both","Void","((%rdi))").
abi_typelocation("a","H5Sget_simple_extent_dims","Both","Void","((%rsi))").
abi_typelocation("a","H5Epush2","Import","Empty","none").
abi_typelocation("a","H5Epush2","Import","Empty","none").
abi_typelocation("a","H5Epush2","Import","Empty","none").
abi_typelocation("a","H5Dopen2","Import","Empty","none").
abi_typelocation("a","H5Tget_size","Import","Integer16","()").
abi_typelocation("a","H5Tget_size","Import","Integer16","()+2").
abi_typelocation("a","H5Tget_size","Import","Integer32","()+4").
abi_typelocation("a","H5Tget_size","Import","Array[8:8]","()+8").
abi_typelocation("a","H5Tget_size","Import","Integer8","()+8").
abi_typelocation("a","H5Epush2","Import","Integer16","()").
abi_typelocation("a","H5Epush2","Import","Integer16","()+2").
abi_typelocation("a","H5Epush2","Import","Integer32","()+4").
abi_typelocation("a","H5Epush2","Import","Array[8:8]","()+8").
abi_typelocation("a","H5Epush2","Import","Integer8","()+8").
abi_typelocation("a","H5Epush2","Import","Integer32","%rdi").
abi_typelocation("a","H5Epush2","Import","Integer16","()").
abi_typelocation("a","H5Epush2","Import","Integer16","()+2").
abi_typelocation("a","H5Epush2","Import","Integer32","()+4").
abi_typelocation("a","H5Epush2","Import","Array[8:8]","()+8").
abi_typelocation("a","H5Epush2","Import","Integer8","()+8").
abi_typelocation("a","H5Epush2","Import","Integer16","()").
abi_typelocation("a","H5Epush2","Import","Integer16","()+2").
abi_typelocation("a","H5Epush2","Import","Integer32","()+4").
abi_typelocation("a","H5Epush2","Import","Array[8:8]","()+8").
abi_typelocation("a","H5Epush2","Import","Integer8","()+8").
abi_typelocation("a","H5Epush2","Import","Integer16","()").
abi_typelocation("a","H5Epush2","Import","Integer16","()+2").
abi_typelocation("a","H5Epush2","Import","Integer32","()+4").
abi_typelocation("a","H5Epush2","Import","Array[8:8]","()+8").
abi_typelocation("a","H5Epush2","Import","Integer8","()+8").
abi_typelocation("a","H5Tget_native_type","Import","Integer16","()").
abi_typelocation("a","H5Tget_native_type","Import","Integer16","()+2").
abi_typelocation("a","H5Tget_native_type","Import","Integer32","()+4").
abi_typelocation("a","H5Tget_native_type","Import","Array[8:8]","()+8").
abi_typelocation("a","H5Tget_native_type","Import","Integer8","()+8").
abi_typelocation("a","H5Tget_native_type","Import","Integer16","()").
abi_typelocation("a","H5Tget_native_type","Import","Integer16","()+2").
abi_typelocation("a","H5Tget_native_type","Import","Integer32","()+4").
abi_typelocation("a","H5Tget_native_type","Import","Array[8:8]","()+8").
abi_typelocation("a","H5Tget_native_type","Import","Integer8","()+8").
abi_typelocation("a","H5Tclose","Import","Integer16","()").
abi_typelocation("a","H5Tclose","Import","Integer16","()+2").
abi_typelocation("a","H5Tclose","Import","Integer32","()+4").
abi_typelocation("a","H5Tclose","Import","Array[8:8]","()+8").
abi_typelocation("a","H5Tclose","Import","Integer8","()+8").
abi_typelocation("a","H5Tequal","Import","Integer16","()").
abi_typelocation("a","H5Tequal","Import","Integer16","()+2").
abi_typelocation("a","H5Tequal","Import","Integer32","()+4").
abi_typelocation("a","H5Tequal","Import","Array[8:8]","()+8").
abi_typelocation("a","H5Tequal","Import","Integer8","()+8").
abi_typelocation("a","H5Tequal","Import","Integer16","()").
abi_typelocation("a","H5Tequal","Import","Integer16","()+2").
abi_typelocation("a","H5Tequal","Import","Integer32","()+4").
abi_typelocation("a","H5Tequal","Import","Array[8:8]","()+8").
abi_typelocation("a","H5Tequal","Import","Integer8","()+8").
abi_typelocation("a","H5Tget_class","Import","Integer16","()").
abi_typelocation("a","H5Tget_class","Import","Integer16","()+2").
abi_typelocation("a","H5Tget_class","Import","Integer32","()+4").
abi_typelocation("a","H5Tget_class","Import","Array[8:8]","()+8").
abi_typelocation("a","H5Tget_class","Import","Integer8","()+8").
abi_typelocation("a","H5Sget_simple_extent_ndims","Export","Integer32","%rax").
abi_typelocation("a","H5Sget_simple_extent_dims","Export","Integer32","%rax").
abi_typelocation("a","H5Dread","Both","Void","(%rdi)").
abi_typelocation("a","H5Screate_simple","Import","Integer32","%rdi").
abi_typelocation("a","H5Tget_array_dims2","Export","Integer32","%rax").
abi_typelocation("a","H5Tget_array_ndims","Export","Integer32","%rax").
abi_typelocation("a","H5Tget_member_offset","Export","Integer64","%rax").
abi_typelocation("a","H5Tget_size","Export","Integer64","%rax").
abi_typelocation("a","H5Tget_nmembers","Export","Integer32","%rax").
abi_typelocation("a","H5Eset_auto1","Both","Void","(%rdi)").
abi_typelocation("a","H5Eauto_is_v2","Import","Empty","none").
abi_typelocation("a","MPI_Finalized","Export","Integer32","%rax").
abi_typelocation("a","MPI_Initialized","Export","Integer32","%rax").
abi_typelocation("a","H5Pset_fapl_core","Import","Integer64","%rdi").
abi_typelocation("a","H5Pset_fapl_log","Import","Integer64","%rdi").
abi_typelocation("a","H5Pset_fapl_log","Import","Integer64","%rsi").
abi_typelocation("a","H5Idec_ref","Export","Integer32","%rax").
abi_typelocation("a","H5VLfree_connector_info","Both","Void","(%rdi)").
abi_typelocation("a","H5Epop","Import","Integer64","%rdi").
abi_typelocation("a","H5Eset_auto2","Both","Void","(%rdi)").
abi_typelocation("a","H5Oget_comment","Import","Array","%rax").
abi_typelocation("a","H5Oget_comment","Import","Integer32","%rax").
abi_typelocation("a","H5Sis_regular_hyperslab","Import","Integer32","%rax").
abi_typelocation("a","H5Sis_regular_hyperslab","Import","Integer32","%rax+4").
abi_typelocation("a","H5Sis_regular_hyperslab","Import","Integer32","%rax+8").
abi_typelocation("a","H5Sis_regular_hyperslab","Import","Integer32","%rax+12").
abi_typelocation("a","H5Sis_regular_hyperslab","Import","Integer64","%rax+16").
abi_typelocation("a","H5Pget_virtual_dsetname","Import","Array","%rax").
abi_typelocation("a","H5Pget_virtual_dsetname","Import","Integer32","%rax").
abi_typelocation("a","H5Pget_virtual_filename","Import","Array","%rax").
abi_typelocation("a","H5Pget_virtual_filename","Import","Integer32","%rax").
abi_typelocation("a","H5Dget_storage_size","Import","Integer32","%rax").
abi_typelocation("a","H5Dget_storage_size","Import","Integer32","%rax+4").
abi_typelocation("a","H5Dget_storage_size","Import","Integer32","%rax+8").
abi_typelocation("a","H5Dget_storage_size","Import","Integer32","%rax+12").
abi_typelocation("a","H5Dget_storage_size","Import","Integer64","%rax+16").
abi_typelocation("a","H5Tis_variable_str","Import","Integer32","%rax").
abi_typelocation("a","H5Tis_variable_str","Import","Integer32","%rax+4").
abi_typelocation("a","H5Tis_variable_str","Import","Integer32","%rax+8").
abi_typelocation("a","H5Tis_variable_str","Import","Integer32","%rax+12").
abi_typelocation("a","H5Tis_variable_str","Import","Integer64","%rax+16").
abi_typelocation("a","H5Tequal","Import","Integer32","%rax").
abi_typelocation("a","H5Tequal","Import","Integer32","%rax+4").
abi_typelocation("a","H5Tequal","Import","Integer32","%rax+8").
abi_typelocation("a","H5Tequal","Import","Integer32","%rax+12").
abi_typelocation("a","H5Tequal","Import","Integer64","%rax+16").
abi_typelocation("a","H5Tcommitted","Import","Integer32","%rax").
abi_typelocation("a","H5Tcommitted","Import","Integer32","%rax+4").
abi_typelocation("a","H5Tcommitted","Import","Integer32","%rax+8").
abi_typelocation("a","H5Tcommitted","Import","Integer32","%rax+12").
abi_typelocation("a","H5Tcommitted","Import","Integer64","%rax+16").
abi_typelocation("a","H5Sis_simple","Import","Integer32","%rax").
abi_typelocation("a","H5Sis_simple","Import","Integer32","%rax+4").
abi_typelocation("a","H5Sis_simple","Import","Integer32","%rax+8").
abi_typelocation("a","H5Sis_simple","Import","Integer32","%rax+12").
abi_typelocation("a","H5Sis_simple","Import","Integer64","%rax+16").
abi_typelocation("a","H5Sget_select_elem_pointlist","Export","Integer32","%rdi").
abi_typelocation("a","H5Sget_select_elem_pointlist","Export","Integer32","%rdi").
abi_typelocation("a","H5Sget_select_elem_pointlist","Export","Integer32","%rsi").
abi_typelocation("a","H5Sget_select_elem_pointlist","Export","Integer32","%rsi").
abi_typelocation("a","H5Sget_select_elem_pointlist","Export","Integer64","%rdx").
abi_typelocation("a","H5Sget_select_elem_pointlist","Export","Integer32","%rcx").
abi_typelocation("a","H5Sget_select_elem_pointlist","Export","Integer32","%rcx").
abi_typelocation("a","H5Sget_select_elem_pointlist","Export","Integer32","%r8").
abi_typelocation("a","H5Sget_select_elem_pointlist","Export","Integer32","%r8").
abi_typelocation("a","H5Sget_select_elem_pointlist","Export","Integer64","%r9").
abi_typelocation("a","H5Sget_select_hyper_blocklist","Export","Integer32","%rdi").
abi_typelocation("a","H5Sget_select_hyper_blocklist","Export","Integer32","%rdi").
abi_typelocation("a","H5Sget_select_hyper_blocklist","Export","Integer32","%rsi").
abi_typelocation("a","H5Sget_select_hyper_blocklist","Export","Integer32","%rsi").
abi_typelocation("a","H5Sget_select_hyper_blocklist","Export","Integer64","%rdx").
abi_typelocation("a","H5Sget_select_hyper_blocklist","Export","Integer32","%rcx").
abi_typelocation("a","H5Sget_select_hyper_blocklist","Export","Integer32","%rcx").
abi_typelocation("a","H5Sget_select_hyper_blocklist","Export","Integer32","%r8").
abi_typelocation("a","H5Sget_select_hyper_blocklist","Export","Integer32","%r8").
abi_typelocation("a","H5Sget_select_hyper_blocklist","Export","Integer64","%r9").
abi_typelocation("a","H5Tget_native_type","Import","Void","()").
abi_typelocation("a","H5Pget_filter2","Import","Integer32","%rdi").
abi_typelocation("a","H5Epush2","Import","Integer32","%rdi").
abi_typelocation("a","H5Tget_size","Export","Void","()").
abi_typelocation("a","H5Pclose","Import","Integer32","%rdi").
abi_typelocation("a","H5Oget_info_by_name3","Import","Integer32","%rdi").
abi_typelocation("a","H5Oget_info_by_name3","Import","Integer32","%rsi").
abi_typelocation("a","H5Oget_info_by_name3","Import","Integer32","%rdx").
abi_typelocation("a","H5Oexists_by_name","Import","Integer32","%rdi").
abi_typelocation("a","H5Oexists_by_name","Import","Integer32","%rsi").
abi_typelocation("a","H5Pset_elink_fapl","Import","Integer32","%rdi").
abi_typelocation("a","H5Pset_elink_fapl","Import","Integer32","%rsi").
abi_typelocation("a","H5Pset_fapl_sec2","Import","Integer32","%rdi").
abi_typelocation("a","H5Pcreate","Import","Integer32","%rdi").
abi_typelocation("a","H5Pcreate","Export","Integer32","%rax").
abi_typelocation("a","H5Lget_val","Import","Integer32","%rdi").
abi_typelocation("a","H5Lget_val","Import","Integer32","%rsi").
abi_typelocation("a","H5Lget_info2","Import","Integer32","%rdi").
abi_typelocation("a","H5Lget_info2","Import","Integer32","%rsi").
abi_typelocation("a","H5Lexists","Import","Integer32","%rdi").
abi_typelocation("a","H5Lexists","Import","Integer32","%rsi").
abi_typelocation("a","H5Dclose","Import","Integer32","%rdi").
abi_typelocation("a","H5Tclose","Import","Integer32","%rdi").
abi_typelocation("a","H5Oget_info3","Import","Integer32","%rdi").
abi_typelocation("a","H5Oget_info3","Import","Integer32","%rsi").
abi_typelocation("a","H5Tcommitted","Import","Integer32","%rdi").
abi_typelocation("a","H5Dget_type","Import","Integer32","%rdi").
abi_typelocation("a","H5Dget_type","Export","Integer32","%rax").
abi_typelocation("a","H5Dopen2","Import","Integer32","%rdi").
abi_typelocation("a","H5Dopen2","Import","Integer32","%rsi").
abi_typelocation("a","H5Dopen2","Export","Integer32","%rax").
abi_typelocation("a","H5Epush2","Import","Integer32","%rdi").
abi_typelocation("a","H5Epush2","Import","Integer32","%rsi").
abi_typelocation("a","H5Epush2","Import","Integer32","%rdx").
abi_typelocation("a","H5Epush2","Import","Integer32","%rcx").
abi_typelocation("a","H5Epush2","Import","Integer32","%r8").
abi_typelocation("a","H5Otoken_cmp","Import","Integer32","%rdi").
abi_typelocation("a","H5Aiterate_by_name","Both","Void","(%rdi)").
abi_typelocation("a","H5Lunpack_elink_val","Import","Integer64","%rdi").
abi_typelocation("a","H5Lget_val","Both","Void","(%rdi)").
abi_typelocation("a","H5Lget_val","Import","Integer64","%rsi").
abi_typelocation("a","H5Literate_by_name2","Both","Void","(%rdi)").
abi_typelocation("a","H5Lvisit_by_name2","Both","Void","(%rdi)").
abi_typelocation("a","H5Epush2","Import","Integer32","%rdi").
abi_typelocation("a","H5Oget_info3","Import","Integer32","%rdi").
abi_typelocation("a","H5Oget_info_by_name3","Import","Integer32","%rdi").

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-11.2.0/hdf5-develop-1.13-7tahw76nqp5aizyigd3zf4g4jee7ox6h/lib/libhdf5.so.1000.0.0
%----------------------------------------------------------------------------
abi_typelocation("b","H5P_LST_FILE_ACCESS_ID_g","Import","Integer16","var").
abi_typelocation("b","H5T_STD_REF_OBJ_g","Import","Empty","none").
abi_typelocation("b","H5T_STD_REF_DSETREG_g","Import","Empty","none").
abi_typelocation("b","H5T_STD_REF_g","Import","Empty","none").
abi_typelocation("b","H5T_VAX_F32_g","Import","Empty","none").
abi_typelocation("b","H5T_VAX_F64_g","Import","Empty","none").
abi_typelocation("b","H5Eget_auto2","Import","Integer64","%rdi").
abi_typelocation("b","H5Eget_auto2","Both","Void","((%rsi))").
abi_typelocation("b","H5Eget_auto2","Both","Void","((%rdx))").
abi_typelocation("b","H5Eget_auto2","Export","Integer32","%rax").
abi_typelocation("b","H5FD_sec2_init","Export","Integer64","%rax").
abi_typelocation("b","H5free_memory","Both","Void","(%rdi)").
abi_typelocation("b","H5free_memory","Export","Integer32","%rax").
abi_typelocation("b","H5close","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","H5Aclose","Export","Integer32","(%rax)").
abi_typelocation("b","H5Aiterate_by_name","Export","Integer32","(%rax)").
abi_typelocation("b","H5Aread","Export","Integer32","(%rax)").
abi_typelocation("b","H5SL_search","Export","Integer8","()").
abi_typelocation("b","H5SL_insert","Import","Integer8","()").
abi_typelocation("b","H5SL_insert","Import","Integer8","()").
abi_typelocation("b","H5SL_insert","Both","Void","(%rdi)").
abi_typelocation("b","H5Epush2","Import","Integer32","%rdi").
abi_typelocation("b","H5Epush2","Import","Integer32","%rsi").
abi_typelocation("b","H5Epush2","Import","Integer32","%rdx").
abi_typelocation("b","H5Ecreate_stack","Import","Union","%rax").
abi_typelocation("b","H5Ecreate_msg","Import","Integer32","%rsi").
abi_typelocation("b","H5Ecreate_msg","Import","Union","%rax").
abi_typelocation("b","H5Eregister_class","Import","Integer32","%rdi").
abi_typelocation("b","H5Eregister_class","Import","Integer32","%rsi").
abi_typelocation("b","H5Eregister_class","Import","Integer32","%rdx").
abi_typelocation("b","H5Eregister_class","Import","Union","%rax").
abi_typelocation("b","H5SL_insert","Import","Array","None").
abi_typelocation("b","H5SL_insert","Import","Integer8","()").
abi_typelocation("b","H5SL_create","Import","Array","None").
abi_typelocation("b","H5SL_search","Import","Array","None").
abi_typelocation("b","H5SL_search","Export","Integer8","()").
abi_typelocation("b","H5Eset_auto1","Import","Array","%rdi").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","%rdi").
abi_typelocation("b","H5Eset_auto2","Import","Array","%rdi").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","%rdi").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","()").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","()").
abi_typelocation("b","H5Pset_fapl_family","Both","Integer32","(%rdi)").
abi_typelocation("b","H5FDperform_init","Import","Void","(())").
abi_typelocation("b","H5Pset_fapl_log","Import","Void","()").
abi_typelocation("b","H5Pset_fapl_mpio","Export","Integer32","%rax").
abi_typelocation("b","H5Tconvert","Import","Integer8","%rdi").
abi_typelocation("b","H5Tconvert","Both","Void","(%rsi)").
abi_typelocation("b","H5Tconvert","Both","Void","(%rdx)").
abi_typelocation("b","H5Eset_auto1","Both","Void","(%rdi)").
abi_typelocation("b","H5Eset_auto2","Both","Void","(%rdi)").
abi_typelocation("b","H5Pget_driver","Import","Empty","none").
abi_typelocation("b","H5Pget_driver","Import","Empty","none").
abi_typelocation("b","H5FDperform_init","Import","Empty","none").
abi_typelocation("b","H5Epush2","Import","Integer8","()").
abi_typelocation("b","H5Epush2","Import","Integer8","()").
abi_typelocation("b","H5Epush2","Import","Integer8","%rdi").
abi_typelocation("b","H5Epush2","Import","Integer8","()").
abi_typelocation("b","H5SL_insert","Import","Empty","none").
abi_typelocation("b","H5SL_insert","Import","Integer32","()").
abi_typelocation("b","H5SL_insert","Import","Integer8","(()+8)").
abi_typelocation("b","H5SL_insert","Import","Integer8","(()+16)").
abi_typelocation("b","H5SL_insert","Import","Integer8","(()+24)").
abi_typelocation("b","H5SL_insert","Import","Integer8","(()+32)").
abi_typelocation("b","H5SL_insert","Import","Integer8","(()+40)").
abi_typelocation("b","H5SL_insert","Import","Integer8","(()+48)").
abi_typelocation("b","H5SL_insert","Import","Integer8","(()+56)").
abi_typelocation("b","H5SL_insert","Import","Integer8","(()+64)").
abi_typelocation("b","H5SL_insert","Import","Integer8","(()+72)").
abi_typelocation("b","H5SL_insert","Import","Integer8","(()+80)").
abi_typelocation("b","H5SL_insert","Import","Integer8","(()+88)").
abi_typelocation("b","H5SL_insert","Import","Empty","(()+96)").
abi_typelocation("b","H5SL_insert","Import","Opaque","(()+104)").
abi_typelocation("b","H5SL_insert","Import","Integer32","()+112").
abi_typelocation("b","H5SL_insert","Import","Integer32","()+116").
abi_typelocation("b","H5SL_insert","Import","Integer64","()+120").
abi_typelocation("b","H5SL_insert","Import","Integer16","()+128").
abi_typelocation("b","H5SL_insert","Import","Integer8","()+130").
abi_typelocation("b","H5SL_insert","Import","Array[1:1]","()+131").
abi_typelocation("b","H5SL_insert","Import","Integer8","()+131").
abi_typelocation("b","H5SL_insert","Import","Integer64","()+144").
abi_typelocation("b","H5SL_insert","Import","Empty","(()+152)").
abi_typelocation("b","H5SL_insert","Import","Empty","(()+160)").
abi_typelocation("b","H5SL_insert","Import","Opaque","(()+168)").
abi_typelocation("b","H5SL_insert","Import","Void","(()+176)").
abi_typelocation("b","H5SL_insert","Import","Integer64","()+184").
abi_typelocation("b","H5SL_insert","Import","Integer32","()+192").
abi_typelocation("b","H5SL_insert","Import","Array[20:20]","()+196").
abi_typelocation("b","H5SL_insert","Import","Integer8","()+196").
abi_typelocation("b","H5SL_search","Import","Empty","none").
abi_typelocation("b","H5SL_search","Import","Integer32","()").
abi_typelocation("b","H5SL_search","Import","Integer8","(()+8)").
abi_typelocation("b","H5SL_search","Import","Integer8","(()+16)").
abi_typelocation("b","H5SL_search","Import","Integer8","(()+24)").
abi_typelocation("b","H5SL_search","Import","Integer8","(()+32)").
abi_typelocation("b","H5SL_search","Import","Integer8","(()+40)").
abi_typelocation("b","H5SL_search","Import","Integer8","(()+48)").
abi_typelocation("b","H5SL_search","Import","Integer8","(()+56)").
abi_typelocation("b","H5SL_search","Import","Integer8","(()+64)").
abi_typelocation("b","H5SL_search","Import","Integer8","(()+72)").
abi_typelocation("b","H5SL_search","Import","Integer8","(()+80)").
abi_typelocation("b","H5SL_search","Import","Integer8","(()+88)").
abi_typelocation("b","H5SL_search","Import","Empty","(()+96)").
abi_typelocation("b","H5SL_search","Import","Opaque","(()+104)").
abi_typelocation("b","H5SL_search","Import","Integer32","()+112").
abi_typelocation("b","H5SL_search","Import","Integer32","()+116").
abi_typelocation("b","H5SL_search","Import","Integer64","()+120").
abi_typelocation("b","H5SL_search","Import","Integer16","()+128").
abi_typelocation("b","H5SL_search","Import","Integer8","()+130").
abi_typelocation("b","H5SL_search","Import","Array[1:1]","()+131").
abi_typelocation("b","H5SL_search","Import","Integer8","()+131").
abi_typelocation("b","H5SL_search","Import","Integer64","()+144").
abi_typelocation("b","H5SL_search","Import","Empty","(()+152)").
abi_typelocation("b","H5SL_search","Import","Empty","(()+160)").
abi_typelocation("b","H5SL_search","Import","Opaque","(()+168)").
abi_typelocation("b","H5SL_search","Import","Void","(()+176)").
abi_typelocation("b","H5SL_search","Import","Integer64","()+184").
abi_typelocation("b","H5SL_search","Import","Integer32","()+192").
abi_typelocation("b","H5SL_search","Import","Array[20:20]","()+196").
abi_typelocation("b","H5SL_search","Import","Integer8","()+196").
abi_typelocation("b","H5SL_create","Import","Empty","%rax").
abi_typelocation("b","H5close","Export","Integer32","%rax").
abi_typelocation("b","H5Eget_auto2","Both","Void","(%rdi)").
abi_typelocation("b","H5Oget_comment","Import","Array","%rax").
abi_typelocation("b","H5Oget_comment","Import","Integer8","%rax").
abi_typelocation("b","H5SL_search","Import","Empty","none").
abi_typelocation("b","H5SL_destroy","Import","Function","%rdi").
abi_typelocation("b","H5SL_insert","Import","Empty","none").
abi_typelocation("b","H5Pget_fill_value","Import","Integer8","()").
abi_typelocation("b","H5Pget_external","Import","Function","%rdi").
abi_typelocation("b","H5Pget_virtual_dsetname","Import","Empty","%rax").
abi_typelocation("b","H5Pget_virtual_filename","Import","Empty","%rax").
abi_typelocation("b","H5SL_create","Import","Function","%rdi").
abi_typelocation("b","H5Pset_elink_fapl","Import","Integer16","%rdi").
abi_typelocation("b","H5Pset_elink_fapl","Import","Integer16","%rsi").
abi_typelocation("b","H5Pset_elink_fapl","Import","Empty","%rax").
abi_typelocation("b","H5Pget_nfilters","Export","Integer32","%rax").
abi_typelocation("b","H5SL_insert","Import","Integer8","()").
abi_typelocation("b","H5SL_insert","Import","Integer32","%rdi").
abi_typelocation("b","H5SL_search","Import","Integer32","%rdi").
abi_typelocation("b","H5SL_search","Export","Integer8","()").
abi_typelocation("b","H5SL_destroy","Import","Integer8","()").
abi_typelocation("b","H5Rget_name","Import","Array","%rax").
abi_typelocation("b","H5Rget_name","Import","Integer8","%rax").
abi_typelocation("b","H5Sget_select_hyper_nblocks","Export","Void","()").
abi_typelocation("b","H5Sget_select_elem_pointlist","Import","Array","%rdi").
abi_typelocation("b","H5Sget_select_elem_pointlist","Import","Integer8","%rdi").
abi_typelocation("b","H5Sget_select_elem_npoints","Import","Array","%rdi").
abi_typelocation("b","H5Sget_select_elem_npoints","Import","Integer8","%rdi").
abi_typelocation("b","H5Sget_select_type","Import","Array","+2").
abi_typelocation("b","H5Sget_select_type","Import","Integer8","+2").
abi_typelocation("b","H5Sget_select_bounds","Import","Array","+2").
abi_typelocation("b","H5Sget_select_bounds","Import","Integer8","+2").
abi_typelocation("b","H5Sget_select_npoints","Import","Array","+2").
abi_typelocation("b","H5Sget_select_npoints","Import","Integer8","+2").
abi_typelocation("b","H5SL_destroy","Import","Integer64","%rdi").
abi_typelocation("b","H5SL_search","Export","Integer64","%rax").
abi_typelocation("b","H5SL_insert","Import","Integer64","%rdi").
abi_typelocation("b","H5Treclaim","Import","Empty","none").
abi_typelocation("b","H5Treclaim","Import","Empty","none").
abi_typelocation("b","H5Treclaim","Import","Empty","none").
abi_typelocation("b","H5Tconvert","Import","Empty","none").
abi_typelocation("b","H5Tconvert","Import","Empty","none").
abi_typelocation("b","H5Tconvert","Import","Integer64","%rdi").
abi_typelocation("b","H5Tconvert","Import","Empty","none").
abi_typelocation("b","H5Tget_super","Import","Empty","none").
abi_typelocation("b","H5Tget_super","Import","Empty","none").
abi_typelocation("b","H5Tset_size","Import","Empty","none").
abi_typelocation("b","H5Tset_size","Import","Integer64","%rdi").
abi_typelocation("b","H5Tget_size","Import","Empty","none").
abi_typelocation("b","H5Tget_size","Export","Integer64","%rax").
abi_typelocation("b","H5Tis_variable_str","Import","Empty","none").
abi_typelocation("b","H5Tdetect_class","Import","Empty","none").
abi_typelocation("b","H5Tget_class","Import","Empty","none").
abi_typelocation("b","H5Tequal","Import","Empty","none").
abi_typelocation("b","H5Tequal","Import","Empty","none").
abi_typelocation("b","H5Tclose","Import","Empty","none").
abi_typelocation("b","H5Tcopy","Import","Empty","none").
abi_typelocation("b","H5Tcopy","Import","Empty","none").
abi_typelocation("b","H5Epop","Import","Array","%rdi").
abi_typelocation("b","H5Epop","Import","Integer8","%rdi").
abi_typelocation("b","H5Eset_auto1","Import","Integer16","%rdi").
abi_typelocation("b","H5Eget_auto1","Import","Array[8:8]","None").
abi_typelocation("b","H5Eget_auto2","Import","Integer8","%rdi").
abi_typelocation("b","H5Eget_auto2","Import","Array[8:8]","None").
abi_typelocation("b","H5VLconnector_str_to_info","Import","Array[8:8]","None").
abi_typelocation("b","H5SL_insert","Import","Empty","(%rdi)").
abi_typelocation("b","H5SL_create","Import","Empty","(%rax)").
abi_typelocation("b","H5SL_search","Import","Empty","(%rdi)").
abi_typelocation("b","H5SL_destroy","Import","Empty","(%rdi)").
abi_typelocation("b","H5VLfree_connector_info","Import","Empty","(%rax)").
abi_typelocation("b","H5VLconnector_str_to_info","Import","Empty","(%rax)").
abi_typelocation("b","H5VLregister_connector_by_value","Import","Integer16","()").
abi_typelocation("b","H5VLregister_connector_by_value","Import","Integer16","()+2").
abi_typelocation("b","H5VLregister_connector_by_value","Import","Integer32","()+4").
abi_typelocation("b","H5VLregister_connector_by_value","Import","Union","()+8").
abi_typelocation("b","H5VLregister_connector_by_value","Import","Integer32","()+24").
abi_typelocation("b","H5Pclose","Import","Empty","(%rax)").
abi_typelocation("b","H5Pset_vol","Import","Empty","(%rax)").

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-11.2.0/openmpi-4.1.4-axm3au7q4x7g5kxocoyoq4tkxobmyio4/lib/libmpi.so.40.30.4
%----------------------------------------------------------------------------
