
%============================================================================
% Library Facts
%============================================================================

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-11.2.0/hdf5-1.8.19-zrpdyarowniwim7fzxaprycjtxxq5rdc/lib/libhdf5_tools.so
%----------------------------------------------------------------------------
abi_typelocation("a","ompi_mpi_comm_world","Import","Empty","none").
abi_typelocation("a","ompi_mpi_char","Import","Empty","none").
abi_typelocation("a","ompi_mpi_byte","Import","Empty","none").
abi_typelocation("a","H5Gclose","Import","Integer32","%rdi").
abi_typelocation("a","H5Gclose","Export","Integer32","%rax").
abi_typelocation("a","H5Gopen2","Import","Integer32","%rdi").
abi_typelocation("a","H5Gopen2","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Gopen2","Import","Integer32","%rdx").
abi_typelocation("a","H5Gopen2","Export","Integer32","%rax").
abi_typelocation("a","H5Tclose","Import","Integer32","%rdi").
abi_typelocation("a","H5Tclose","Export","Integer32","%rax").
abi_typelocation("a","H5Tequal","Import","Integer32","%rdi").
abi_typelocation("a","H5Tequal","Import","Integer32","%rsi").
abi_typelocation("a","H5Tequal","Export","Integer32","%rax").
abi_typelocation("a","H5Topen2","Import","Integer32","%rdi").
abi_typelocation("a","H5Topen2","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Topen2","Import","Integer32","%rdx").
abi_typelocation("a","H5Topen2","Export","Integer32","%rax").
abi_typelocation("a","H5Dclose","Import","Integer32","%rdi").
abi_typelocation("a","H5Dclose","Export","Integer32","%rax").
abi_typelocation("a","H5Dopen2","Import","Integer32","%rdi").
abi_typelocation("a","H5Dopen2","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Dopen2","Import","Integer32","%rdx").
abi_typelocation("a","H5Dopen2","Export","Integer32","%rax").
abi_typelocation("a","MPI_Finalize","Export","Integer32","%rax").
abi_typelocation("a","MPI_Probe","Import","Integer32","%rdi").
abi_typelocation("a","MPI_Probe","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Probe","Import","Empty","(%rdx)").
abi_typelocation("a","MPI_Probe","Import","Integer32","(%rcx)").
abi_typelocation("a","MPI_Probe","Import","Integer32","(%rcx)+4").
abi_typelocation("a","MPI_Probe","Import","Integer32","(%rcx)+8").
abi_typelocation("a","MPI_Probe","Import","Integer32","(%rcx)+12").
abi_typelocation("a","MPI_Probe","Import","Integer64","(%rcx)+16").
abi_typelocation("a","MPI_Probe","Export","Integer32","%rax").
abi_typelocation("a","MPI_Recv","Both","Void","(%rdi)").
abi_typelocation("a","MPI_Recv","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Recv","Import","Empty","(%rdx)").
abi_typelocation("a","MPI_Recv","Import","Integer32","%rcx").
abi_typelocation("a","MPI_Recv","Import","Integer32","%r8").
abi_typelocation("a","MPI_Recv","Import","Empty","(%r9)").
abi_typelocation("a","MPI_Recv","Import","Integer32","(framebase+8)").
abi_typelocation("a","MPI_Recv","Import","Integer32","(framebase+8)+4").
abi_typelocation("a","MPI_Recv","Import","Integer32","(framebase+8)+8").
abi_typelocation("a","MPI_Recv","Import","Integer32","(framebase+8)+12").
abi_typelocation("a","MPI_Recv","Import","Integer64","(framebase+8)+16").
abi_typelocation("a","MPI_Recv","Export","Integer32","%rax").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","%rdi").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Iprobe","Import","Empty","(%rdx)").
abi_typelocation("a","MPI_Iprobe","Both","Integer32","(%rcx)").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","(%r8)").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","(%r8)+4").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","(%r8)+8").
abi_typelocation("a","MPI_Iprobe","Import","Integer32","(%r8)+12").
abi_typelocation("a","MPI_Iprobe","Import","Integer64","(%r8)+16").
abi_typelocation("a","MPI_Iprobe","Export","Integer32","%rax").
abi_typelocation("a","H5Lunpack_elink_val","Import","Integer64","%rsi").
abi_typelocation("a","H5Lunpack_elink_val","Both","Integer32","(%rdx)").
abi_typelocation("a","H5Lunpack_elink_val","Both","Integer8","((%rcx))").
abi_typelocation("a","H5Lunpack_elink_val","Both","Integer8","((%r8))").
abi_typelocation("a","H5Lunpack_elink_val","Export","Integer32","%rax").
abi_typelocation("a","H5Fclose","Import","Integer32","%rdi").
abi_typelocation("a","H5Fclose","Export","Integer32","%rax").
abi_typelocation("a","MPI_Abort","Import","Empty","(%rdi)").
abi_typelocation("a","MPI_Abort","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Abort","Export","Integer32","%rax").
abi_typelocation("a","HDfprintf","Import","Integer32","(%rdi)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+8)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+16)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+24)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+32)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+40)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+48)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+56)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+64)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+72)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+80)").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+88)").
abi_typelocation("a","HDfprintf","Import","Empty","((%rdi)+96)").
abi_typelocation("a","HDfprintf","Import","Integer32","((%rdi)+104)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+8)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+16)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+24)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+32)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+40)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+48)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+56)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+64)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+72)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+80)").
abi_typelocation("a","HDfprintf","Import","Integer8","(((%rdi)+104)+88)").
abi_typelocation("a","HDfprintf","Import","Empty","(((%rdi)+104)+96)").
abi_typelocation("a","HDfprintf","Import","Opaque","(((%rdi)+104)+104)").
abi_typelocation("a","HDfprintf","Import","Integer32","((%rdi)+104)+112").
abi_typelocation("a","HDfprintf","Import","Integer32","((%rdi)+104)+116").
abi_typelocation("a","HDfprintf","Import","Integer64","((%rdi)+104)+120").
abi_typelocation("a","HDfprintf","Import","Integer16","((%rdi)+104)+128").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+104)+130").
abi_typelocation("a","HDfprintf","Import","Array[1:1]","((%rdi)+104)+131").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+104)+131").
abi_typelocation("a","HDfprintf","Import","Integer64","((%rdi)+104)+144").
abi_typelocation("a","HDfprintf","Import","Empty","(((%rdi)+104)+152)").
abi_typelocation("a","HDfprintf","Import","Empty","(((%rdi)+104)+160)").
abi_typelocation("a","HDfprintf","Import","Opaque","(((%rdi)+104)+168)").
abi_typelocation("a","HDfprintf","Import","Void","(((%rdi)+104)+176)").
abi_typelocation("a","HDfprintf","Import","Integer64","((%rdi)+104)+184").
abi_typelocation("a","HDfprintf","Import","Integer32","((%rdi)+104)+192").
abi_typelocation("a","HDfprintf","Import","Array[20:20]","((%rdi)+104)+196").
abi_typelocation("a","HDfprintf","Import","Integer8","((%rdi)+104)+196").
abi_typelocation("a","HDfprintf","Import","Integer32","(%rdi)+112").
abi_typelocation("a","HDfprintf","Import","Integer32","(%rdi)+116").
abi_typelocation("a","HDfprintf","Import","Integer64","(%rdi)+120").
abi_typelocation("a","HDfprintf","Import","Integer16","(%rdi)+128").
abi_typelocation("a","HDfprintf","Import","Integer8","(%rdi)+130").
abi_typelocation("a","HDfprintf","Import","Array[1:1]","(%rdi)+131").
abi_typelocation("a","HDfprintf","Import","Integer8","(%rdi)+131").
abi_typelocation("a","HDfprintf","Import","Integer64","(%rdi)+144").
abi_typelocation("a","HDfprintf","Import","Empty","((%rdi)+152)").
abi_typelocation("a","HDfprintf","Import","Empty","((%rdi)+160)").
abi_typelocation("a","HDfprintf","Import","Opaque","((%rdi)+168)").
abi_typelocation("a","HDfprintf","Import","Void","((%rdi)+176)").
abi_typelocation("a","HDfprintf","Import","Integer64","(%rdi)+184").
abi_typelocation("a","HDfprintf","Import","Integer32","(%rdi)+192").
abi_typelocation("a","HDfprintf","Import","Array[20:20]","(%rdi)+196").
abi_typelocation("a","HDfprintf","Import","Integer8","(%rdi)+196").
abi_typelocation("a","HDfprintf","Both","Integer8","(%rsi)").
abi_typelocation("a","HDfprintf","Export","Integer32","%rax").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer32","%rdi").
abi_typelocation("a","H5Oget_info_by_name","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+8").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer32","(%rdx)+16").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer32","(%rdx)+20").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+24").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+32").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+40").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+48").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+56").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer32","(%rdx)+64").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer32","(%rdx)+68").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer32","(%rdx)+72").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer32","(%rdx)+76").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+80").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+88").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+96").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+104").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+112").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+120").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+128").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+136").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+144").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer64","(%rdx)+152").
abi_typelocation("a","H5Oget_info_by_name","Import","Integer32","%rcx").
abi_typelocation("a","H5Oget_info_by_name","Export","Integer32","%rax").
abi_typelocation("a","H5Lget_info","Import","Integer32","%rdi").
abi_typelocation("a","H5Lget_info","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Lget_info","Import","Integer32","(%rdx)").
abi_typelocation("a","H5Lget_info","Import","Integer32","(%rdx)+4").
abi_typelocation("a","H5Lget_info","Import","Integer64","(%rdx)+8").
abi_typelocation("a","H5Lget_info","Import","Integer32","(%rdx)+16").
abi_typelocation("a","H5Lget_info","Import","Union","(%rdx)+24").
abi_typelocation("a","H5Lget_info","Import","Integer32","%rcx").
abi_typelocation("a","H5Lget_info","Export","Integer32","%rax").
abi_typelocation("a","H5Lexists","Import","Integer32","%rdi").
abi_typelocation("a","H5Lexists","Both","Integer8","(%rsi)").
abi_typelocation("a","H5Lexists","Import","Integer32","%rdx").
abi_typelocation("a","H5Lexists","Export","Integer32","%rax").
abi_typelocation("a","H5Eset_auto1","Import","Void","(%rdi)").
abi_typelocation("a","H5Eset_auto1","Both","Void","(%rsi)").
abi_typelocation("a","H5Eset_auto1","Export","Integer32","%rax").
abi_typelocation("a","H5Eget_auto1","Both","Void","((%rdi))").
abi_typelocation("a","H5Eget_auto1","Both","Void","((%rsi))").
abi_typelocation("a","H5Eget_auto1","Export","Integer32","%rax").
abi_typelocation("a","H5Eset_auto2","Import","Integer32","%rdi").
abi_typelocation("a","H5Eset_auto2","Import","Void","(%rsi)").
abi_typelocation("a","H5Eset_auto2","Both","Void","(%rdx)").
abi_typelocation("a","H5Eset_auto2","Export","Integer32","%rax").
abi_typelocation("a","H5Eget_auto2","Import","Integer32","%rdi").
abi_typelocation("a","H5Eget_auto2","Both","Void","((%rsi))").
abi_typelocation("a","H5Eget_auto2","Both","Void","((%rdx))").
abi_typelocation("a","H5Eget_auto2","Export","Integer32","%rax").
abi_typelocation("a","H5Eauto_is_v2","Import","Integer32","%rdi").
abi_typelocation("a","H5Eauto_is_v2","Both","Integer32","(%rsi)").
abi_typelocation("a","H5Eauto_is_v2","Export","Integer32","%rax").
abi_typelocation("a","MPI_Send","Import","Integer32","%rsi").
abi_typelocation("a","MPI_Send","Import","Empty","(%rdx)").
abi_typelocation("a","MPI_Send","Import","Integer32","%rcx").
abi_typelocation("a","MPI_Send","Import","Integer32","%r8").
abi_typelocation("a","MPI_Send","Import","Empty","(%r9)").
abi_typelocation("a","MPI_Send","Export","Integer32","%rax").
abi_typelocation("a","H5Tget_member_offset","Import","Integer8","()").
abi_typelocation("a","H5Tget_member_type","Import","Integer8","()").
abi_typelocation("a","H5Eauto_is_v2","Import","Integer32","%rdi").
abi_typelocation("a","H5Sselect_hyperslab","Import","Integer8","()").
abi_typelocation("a","H5Dread","Import","Integer64","%rdi").
abi_typelocation("a","H5Sselect_hyperslab","Import","Integer8","()").
abi_typelocation("a","H5Tget_member_offset","Import","Integer32","%rdi").
abi_typelocation("a","H5Tget_member_offset","Export","Integer64","%rax").
abi_typelocation("a","H5Epush2","Import","Integer32","%rdi").
abi_typelocation("a","H5Tget_size","Export","Integer64","%rax").
abi_typelocation("a","H5Tget_member_type","Import","Integer32","%rdi").
abi_typelocation("a","H5Pset_fapl_mpio","Import","Empty","none").
abi_typelocation("a","H5Fopen","Import","Integer32","%rdi").
abi_typelocation("a","H5Eset_auto1","Import","Integer64","%rdi").
abi_typelocation("a","H5Eset_auto2","Import","Integer64","%rdi").
abi_typelocation("a","H5Aread","Import","Integer64","%rdi").
abi_typelocation("a","H5Pget_external","Import","Integer32","%rdi").
abi_typelocation("a","H5Pget_filter2","Import","Integer32","%rdi").
abi_typelocation("a","H5Pget_fill_value","Import","Integer64","%rdi").
abi_typelocation("a","H5Tconvert","Import","Integer64","%rdi").
abi_typelocation("a","H5Tconvert","Import","Integer64","%rsi").
abi_typelocation("a","H5Tget_member_value","Import","Integer32","%rdi").
abi_typelocation("a","H5Tget_member_value","Import","Integer64","%rsi").
abi_typelocation("a","H5Tget_member_type","Import","Integer32","%rdi").
abi_typelocation("a","H5Tget_member_name","Import","Integer32","%rdi").
abi_typelocation("a","H5free_memory","Import","Integer64","%rdi").
abi_typelocation("a","H5Dvlen_reclaim","Import","Integer64","%rdi").
abi_typelocation("a","H5Dread","Import","Integer64","%rdi").
abi_typelocation("a","H5Epush2","Import","Integer32","%rdi").
abi_typelocation("a","H5SL_search","Export","Integer64","%rax").
abi_typelocation("a","H5SL_insert","Import","Integer64","%rdi").
abi_typelocation("a","H5SL_destroy","Import","Integer64","%rdi").
abi_typelocation("a","H5Tget_member_type","Import","Integer64","%rdi").
abi_typelocation("a","H5Tget_member_offset","Import","Integer64","%rdi").
abi_typelocation("a","H5Tget_member_name","Import","Integer64","%rdi").
abi_typelocation("a","H5Tget_sign","Import","Empty","(%rax)").
abi_typelocation("a","H5Lget_val","Import","Empty","none").
abi_typelocation("a","H5Lunpack_elink_val","Import","Integer8","()").
abi_typelocation("a","H5Lget_val","Import","Integer8","()").
abi_typelocation("a","MPI_Wtime","Export","Integer8","()").

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-11.2.0/hdf5-1.8.19-z36zc5lbtkavg37ingqvo4uijvuauw2a/lib/libhdf5.so.1.8.19
%----------------------------------------------------------------------------
abi_typelocation("b","HDfprintf","Import","Integer32","(%rdi)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+8)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+16)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+24)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+32)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+40)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+48)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+56)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+64)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+72)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+80)").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+88)").
abi_typelocation("b","HDfprintf","Import","Empty","((%rdi)+96)").
abi_typelocation("b","HDfprintf","Import","Integer32","((%rdi)+104)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+8)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+16)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+24)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+32)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+40)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+48)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+56)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+64)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+72)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+80)").
abi_typelocation("b","HDfprintf","Import","Integer8","(((%rdi)+104)+88)").
abi_typelocation("b","HDfprintf","Import","Empty","(((%rdi)+104)+96)").
abi_typelocation("b","HDfprintf","Import","Opaque","(((%rdi)+104)+104)").
abi_typelocation("b","HDfprintf","Import","Integer32","((%rdi)+104)+112").
abi_typelocation("b","HDfprintf","Import","Integer32","((%rdi)+104)+116").
abi_typelocation("b","HDfprintf","Import","Integer64","((%rdi)+104)+120").
abi_typelocation("b","HDfprintf","Import","Integer16","((%rdi)+104)+128").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+104)+130").
abi_typelocation("b","HDfprintf","Import","Array[1:1]","((%rdi)+104)+131").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+104)+131").
abi_typelocation("b","HDfprintf","Import","Integer64","((%rdi)+104)+144").
abi_typelocation("b","HDfprintf","Import","Empty","(((%rdi)+104)+152)").
abi_typelocation("b","HDfprintf","Import","Empty","(((%rdi)+104)+160)").
abi_typelocation("b","HDfprintf","Import","Opaque","(((%rdi)+104)+168)").
abi_typelocation("b","HDfprintf","Import","Void","(((%rdi)+104)+176)").
abi_typelocation("b","HDfprintf","Import","Integer64","((%rdi)+104)+184").
abi_typelocation("b","HDfprintf","Import","Integer32","((%rdi)+104)+192").
abi_typelocation("b","HDfprintf","Import","Array[20:20]","((%rdi)+104)+196").
abi_typelocation("b","HDfprintf","Import","Integer8","((%rdi)+104)+196").
abi_typelocation("b","HDfprintf","Import","Integer32","(%rdi)+112").
abi_typelocation("b","HDfprintf","Import","Integer32","(%rdi)+116").
abi_typelocation("b","HDfprintf","Import","Integer64","(%rdi)+120").
abi_typelocation("b","HDfprintf","Import","Integer16","(%rdi)+128").
abi_typelocation("b","HDfprintf","Import","Integer8","(%rdi)+130").
abi_typelocation("b","HDfprintf","Import","Array[1:1]","(%rdi)+131").
abi_typelocation("b","HDfprintf","Import","Integer8","(%rdi)+131").
abi_typelocation("b","HDfprintf","Import","Integer64","(%rdi)+144").
abi_typelocation("b","HDfprintf","Import","Empty","((%rdi)+152)").
abi_typelocation("b","HDfprintf","Import","Empty","((%rdi)+160)").
abi_typelocation("b","HDfprintf","Import","Opaque","((%rdi)+168)").
abi_typelocation("b","HDfprintf","Import","Void","((%rdi)+176)").
abi_typelocation("b","HDfprintf","Import","Integer64","(%rdi)+184").
abi_typelocation("b","HDfprintf","Import","Integer32","(%rdi)+192").
abi_typelocation("b","HDfprintf","Import","Array[20:20]","(%rdi)+196").
abi_typelocation("b","HDfprintf","Import","Integer8","(%rdi)+196").
abi_typelocation("b","HDfprintf","Both","Integer8","(%rsi)").
abi_typelocation("b","HDfprintf","Export","Integer32","%rax").
abi_typelocation("b","H5Eget_auto2","Import","Integer32","%rdi").
abi_typelocation("b","H5Eget_auto2","Both","Void","((%rsi))").
abi_typelocation("b","H5Eget_auto2","Both","Void","((%rdx))").
abi_typelocation("b","H5Eget_auto2","Export","Integer32","%rax").
abi_typelocation("b","H5free_memory","Both","Void","(%rdi)").
abi_typelocation("b","H5free_memory","Export","Integer32","%rax").
abi_typelocation("b","H5close","Export","Integer32","%rax").
abi_typelocation("b","H5open","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","H5Aiterate_by_name","Import","Integer8","()").
abi_typelocation("b","H5Aget_name","Export","Integer64","%rax").
abi_typelocation("b","H5Aread","Import","Integer8","()").
abi_typelocation("b","HDfprintf","Import","Integer32","()").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","H5Dvlen_reclaim","Import","Integer64","%rdi").
abi_typelocation("b","HDfprintf","Export","Integer16","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","H5Eauto_is_v2","Import","Array","%rdi").
abi_typelocation("b","H5Eauto_is_v2","Import","Integer8","%rdi").
abi_typelocation("b","H5Eget_auto2","Import","Function","%rdi").
abi_typelocation("b","H5Eget_auto1","Import","Function","%rdi").
abi_typelocation("b","H5Fopen","Import","Integer32","%rsi").
abi_typelocation("b","H5SL_insert","Both","Void","(%rdi)").
abi_typelocation("b","H5SL_search","Export","Void","(%rax)").
abi_typelocation("b","H5close","Export","Integer32","%rax").
abi_typelocation("b","H5close","Export","Integer32","%rax").
abi_typelocation("b","H5close","Export","Integer32","%rax").
abi_typelocation("b","H5Eset_auto1","Import","Integer8","%rdi").
abi_typelocation("b","H5Eget_auto1","Import","Function","%rdi").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","%rdi").
abi_typelocation("b","H5Eget_auto2","Import","Function","%rdi").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","H5Pset_fapl_mpio","Export","Integer8","(())").
abi_typelocation("b","H5Tconvert","Import","Integer8","%rdx").
abi_typelocation("b","H5Epush2","Import","Integer32","%rsi").
abi_typelocation("b","H5Epush2","Import","Integer32","%rdx").
abi_typelocation("b","H5Epush2","Import","Integer32","framebase+8").
abi_typelocation("b","H5Pset_fapl_split","Import","Integer32","%rsi").
abi_typelocation("b","H5Pset_fapl_split","Import","Integer32","%rcx").
abi_typelocation("b","H5Epush2","Import","Integer32","%rdi").
abi_typelocation("b","H5SL_destroy","Import","Integer64","%rdi").
abi_typelocation("b","H5SL_create","Import","Integer32","()").
abi_typelocation("b","H5Gclose","Export","Void","()").
abi_typelocation("b","H5close","Export","Integer32","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Import","Empty","(%rdi)").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Import","Integer8","()").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","H5Pget_fill_value","Import","Integer64","%rdi").
abi_typelocation("b","H5Pget_external","Import","Function","%rdi").
abi_typelocation("b","H5Pget_chunk","Import","Function","%rdi").
abi_typelocation("b","H5SL_search","Import","Empty","none").
abi_typelocation("b","H5SL_insert","Import","Empty","none").
abi_typelocation("b","H5SL_create","Import","Empty","none").
abi_typelocation("b","H5Pset_elink_fapl","Import","Array","%rax").
abi_typelocation("b","H5Pset_elink_fapl","Import","Integer8","%rax").
abi_typelocation("b","H5Pget_filter2","Import","Integer8","()").
abi_typelocation("b","H5Pget_nfilters","Import","Integer8","()").
abi_typelocation("b","H5Rget_name","Import","Integer8","()").
abi_typelocation("b","H5Rget_name","Import","Integer32","%rdi").
abi_typelocation("b","H5Rget_name","Import","Array","%rax").
abi_typelocation("b","H5Rget_name","Import","Integer8","%rax").
abi_typelocation("b","H5Rget_obj_type2","Import","Integer8","()").
abi_typelocation("b","H5Rget_obj_type2","Import","Integer32","%rdi").
abi_typelocation("b","H5Rget_obj_type2","Export","Integer32","()").
abi_typelocation("b","H5Rget_region","Import","Integer8","()").
abi_typelocation("b","H5Rget_region","Import","Integer32","%rdi").
abi_typelocation("b","H5Rget_region","Export","Integer8","()").
abi_typelocation("b","H5Rdereference","Import","Integer8","()").
abi_typelocation("b","H5Rdereference","Import","Integer32","%rdi").
abi_typelocation("b","H5Rdereference","Export","Integer8","()").
abi_typelocation("b","H5Screate_simple","Import","Empty","none").
abi_typelocation("b","H5Screate_simple","Import","Empty","none").
abi_typelocation("b","HDfprintf","Export","Integer64","%rax").
abi_typelocation("b","H5Tconvert","Import","Integer8","%rdi").
abi_typelocation("b","H5Tconvert","Import","Integer8","%rsi").
abi_typelocation("b","H5Tget_array_dims2","Export","Integer64","%rax").
abi_typelocation("b","H5Tget_array_ndims","Export","Integer64","%rax").
abi_typelocation("b","H5Tget_member_offset","Import","Array","%rax").
abi_typelocation("b","H5Tget_member_offset","Import","Integer8","%rax").
abi_typelocation("b","H5Tset_cset","Import","Integer8","()").
abi_typelocation("b","H5Tget_cset","Import","Integer8","()").
abi_typelocation("b","H5Tget_member_value","Import","Integer8","()").
abi_typelocation("b","H5Tget_nmembers","Export","Integer64","%rax").
abi_typelocation("b","H5Tget_sign","Import","Integer8","()").
abi_typelocation("b","H5Tget_tag","Import","Integer8","()").
abi_typelocation("b","H5Tset_order","Import","Integer8","()").
abi_typelocation("b","H5Tget_order","Import","Integer8","()").
abi_typelocation("b","H5Tset_strpad","Import","Integer8","()").
abi_typelocation("b","H5Tset_strpad","Import","Array[288:18]","None").
abi_typelocation("b","H5Tset_strpad","Import","Integer8","()").
abi_typelocation("b","H5Tset_strpad","Import","Integer32","(+8)").
abi_typelocation("b","H5Tset_strpad","Import","Integer8","((+8)+8)").
abi_typelocation("b","H5Tset_strpad","Import","Integer8","((+8)+16)").
abi_typelocation("b","H5Tset_strpad","Import","Integer8","((+8)+24)").
abi_typelocation("b","H5Tset_strpad","Import","Integer8","((+8)+32)").
abi_typelocation("b","H5Tset_strpad","Import","Integer8","((+8)+40)").
abi_typelocation("b","H5Tset_strpad","Import","Integer8","((+8)+48)").
abi_typelocation("b","H5Tset_strpad","Import","Integer8","((+8)+56)").
abi_typelocation("b","H5Tset_strpad","Import","Integer8","((+8)+64)").
abi_typelocation("b","H5Tset_strpad","Import","Integer8","((+8)+72)").
abi_typelocation("b","H5Tset_strpad","Import","Integer8","((+8)+80)").
abi_typelocation("b","H5Tset_strpad","Import","Integer8","((+8)+88)").
abi_typelocation("b","H5Tset_strpad","Import","Empty","((+8)+96)").
abi_typelocation("b","H5Tset_strpad","Import","Integer32","((+8)+104)").
abi_typelocation("b","H5Tset_strpad","Import","Integer8","(((+8)+104)+8)").
abi_typelocation("b","H5Tset_strpad","Import","Integer8","(((+8)+104)+16)").
abi_typelocation("b","H5Tset_strpad","Import","Integer8","(((+8)+104)+24)").
abi_typelocation("b","H5Tset_strpad","Import","Integer8","(((+8)+104)+32)").
abi_typelocation("b","H5Tset_strpad","Import","Integer8","(((+8)+104)+40)").
abi_typelocation("b","H5Tset_strpad","Import","Integer8","(((+8)+104)+48)").
abi_typelocation("b","H5Tset_strpad","Import","Integer8","(((+8)+104)+56)").
abi_typelocation("b","H5Tset_strpad","Import","Integer8","(((+8)+104)+64)").
abi_typelocation("b","H5Tset_strpad","Import","Integer8","(((+8)+104)+72)").
abi_typelocation("b","H5Tset_strpad","Import","Integer8","(((+8)+104)+80)").
abi_typelocation("b","H5Tset_strpad","Import","Integer8","(((+8)+104)+88)").
abi_typelocation("b","H5Tset_strpad","Import","Empty","(((+8)+104)+96)").
abi_typelocation("b","H5Tset_strpad","Import","Opaque","(((+8)+104)+104)").
abi_typelocation("b","H5Tset_strpad","Import","Integer32","((+8)+104)+112").
abi_typelocation("b","H5Tset_strpad","Import","Integer32","((+8)+104)+116").
abi_typelocation("b","H5Tset_strpad","Import","Integer64","((+8)+104)+120").
abi_typelocation("b","H5Tset_strpad","Import","Integer16","((+8)+104)+128").
abi_typelocation("b","H5Tset_strpad","Import","Integer8","((+8)+104)+130").
abi_typelocation("b","H5Tset_strpad","Import","Array[1:1]","((+8)+104)+131").
abi_typelocation("b","H5Tset_strpad","Import","Integer8","((+8)+104)+131").
abi_typelocation("b","H5Tset_strpad","Import","Integer64","((+8)+104)+144").
abi_typelocation("b","H5Tset_strpad","Import","Empty","(((+8)+104)+152)").
abi_typelocation("b","H5Tset_strpad","Import","Empty","(((+8)+104)+160)").
abi_typelocation("b","H5Tset_strpad","Import","Opaque","(((+8)+104)+168)").
abi_typelocation("b","H5Tset_strpad","Import","Void","(((+8)+104)+176)").
abi_typelocation("b","H5Tset_strpad","Import","Integer64","((+8)+104)+184").
abi_typelocation("b","H5Tset_strpad","Import","Integer32","((+8)+104)+192").
abi_typelocation("b","H5Tset_strpad","Import","Array[20:20]","((+8)+104)+196").
abi_typelocation("b","H5Tset_strpad","Import","Integer8","((+8)+104)+196").
abi_typelocation("b","H5Tset_strpad","Import","Integer32","(+8)+112").
abi_typelocation("b","H5Tset_strpad","Import","Integer32","(+8)+116").
abi_typelocation("b","H5Tset_strpad","Import","Integer64","(+8)+120").
abi_typelocation("b","H5Tset_strpad","Import","Integer16","(+8)+128").
abi_typelocation("b","H5Tset_strpad","Import","Integer8","(+8)+130").
abi_typelocation("b","H5Tset_strpad","Import","Array[1:1]","(+8)+131").
abi_typelocation("b","H5Tset_strpad","Import","Integer8","(+8)+131").
abi_typelocation("b","H5Tset_strpad","Import","Integer64","(+8)+144").
abi_typelocation("b","H5Tset_strpad","Import","Empty","((+8)+152)").
abi_typelocation("b","H5Tset_strpad","Import","Empty","((+8)+160)").
abi_typelocation("b","H5Tset_strpad","Import","Opaque","((+8)+168)").
abi_typelocation("b","H5Tset_strpad","Import","Void","((+8)+176)").
abi_typelocation("b","H5Tset_strpad","Import","Integer64","(+8)+184").
abi_typelocation("b","H5Tset_strpad","Import","Integer32","(+8)+192").
abi_typelocation("b","H5Tset_strpad","Import","Array[20:20]","(+8)+196").
abi_typelocation("b","H5Tset_strpad","Import","Integer8","(+8)+196").
abi_typelocation("b","H5Tget_strpad","Import","Integer8","()").
abi_typelocation("b","H5Tget_strpad","Import","Array[288:18]","None").
abi_typelocation("b","H5Tget_strpad","Import","Integer8","()").
abi_typelocation("b","H5Tget_strpad","Import","Integer32","(+8)").
abi_typelocation("b","H5Tget_strpad","Import","Integer8","((+8)+8)").
abi_typelocation("b","H5Tget_strpad","Import","Integer8","((+8)+16)").
abi_typelocation("b","H5Tget_strpad","Import","Integer8","((+8)+24)").
abi_typelocation("b","H5Tget_strpad","Import","Integer8","((+8)+32)").
abi_typelocation("b","H5Tget_strpad","Import","Integer8","((+8)+40)").
abi_typelocation("b","H5Tget_strpad","Import","Integer8","((+8)+48)").
abi_typelocation("b","H5Tget_strpad","Import","Integer8","((+8)+56)").
abi_typelocation("b","H5Tget_strpad","Import","Integer8","((+8)+64)").
abi_typelocation("b","H5Tget_strpad","Import","Integer8","((+8)+72)").
abi_typelocation("b","H5Tget_strpad","Import","Integer8","((+8)+80)").
abi_typelocation("b","H5Tget_strpad","Import","Integer8","((+8)+88)").
abi_typelocation("b","H5Tget_strpad","Import","Empty","((+8)+96)").
abi_typelocation("b","H5Tget_strpad","Import","Integer32","((+8)+104)").
abi_typelocation("b","H5Tget_strpad","Import","Integer8","(((+8)+104)+8)").
abi_typelocation("b","H5Tget_strpad","Import","Integer8","(((+8)+104)+16)").
abi_typelocation("b","H5Tget_strpad","Import","Integer8","(((+8)+104)+24)").
abi_typelocation("b","H5Tget_strpad","Import","Integer8","(((+8)+104)+32)").
abi_typelocation("b","H5Tget_strpad","Import","Integer8","(((+8)+104)+40)").
abi_typelocation("b","H5Tget_strpad","Import","Integer8","(((+8)+104)+48)").
abi_typelocation("b","H5Tget_strpad","Import","Integer8","(((+8)+104)+56)").
abi_typelocation("b","H5Tget_strpad","Import","Integer8","(((+8)+104)+64)").
abi_typelocation("b","H5Tget_strpad","Import","Integer8","(((+8)+104)+72)").
abi_typelocation("b","H5Tget_strpad","Import","Integer8","(((+8)+104)+80)").
abi_typelocation("b","H5Tget_strpad","Import","Integer8","(((+8)+104)+88)").
abi_typelocation("b","H5Tget_strpad","Import","Empty","(((+8)+104)+96)").
abi_typelocation("b","H5Tget_strpad","Import","Opaque","(((+8)+104)+104)").
abi_typelocation("b","H5Tget_strpad","Import","Integer32","((+8)+104)+112").
abi_typelocation("b","H5Tget_strpad","Import","Integer32","((+8)+104)+116").
abi_typelocation("b","H5Tget_strpad","Import","Integer64","((+8)+104)+120").
abi_typelocation("b","H5Tget_strpad","Import","Integer16","((+8)+104)+128").
abi_typelocation("b","H5Tget_strpad","Import","Integer8","((+8)+104)+130").
abi_typelocation("b","H5Tget_strpad","Import","Array[1:1]","((+8)+104)+131").
abi_typelocation("b","H5Tget_strpad","Import","Integer8","((+8)+104)+131").
abi_typelocation("b","H5Tget_strpad","Import","Integer64","((+8)+104)+144").
abi_typelocation("b","H5Tget_strpad","Import","Empty","(((+8)+104)+152)").
abi_typelocation("b","H5Tget_strpad","Import","Empty","(((+8)+104)+160)").
abi_typelocation("b","H5Tget_strpad","Import","Opaque","(((+8)+104)+168)").
abi_typelocation("b","H5Tget_strpad","Import","Void","(((+8)+104)+176)").
abi_typelocation("b","H5Tget_strpad","Import","Integer64","((+8)+104)+184").
abi_typelocation("b","H5Tget_strpad","Import","Integer32","((+8)+104)+192").
abi_typelocation("b","H5Tget_strpad","Import","Array[20:20]","((+8)+104)+196").
abi_typelocation("b","H5Tget_strpad","Import","Integer8","((+8)+104)+196").
abi_typelocation("b","H5Tget_strpad","Import","Integer32","(+8)+112").
abi_typelocation("b","H5Tget_strpad","Import","Integer32","(+8)+116").
abi_typelocation("b","H5Tget_strpad","Import","Integer64","(+8)+120").
abi_typelocation("b","H5Tget_strpad","Import","Integer16","(+8)+128").
abi_typelocation("b","H5Tget_strpad","Import","Integer8","(+8)+130").
abi_typelocation("b","H5Tget_strpad","Import","Array[1:1]","(+8)+131").
abi_typelocation("b","H5Tget_strpad","Import","Integer8","(+8)+131").
abi_typelocation("b","H5Tget_strpad","Import","Integer64","(+8)+144").
abi_typelocation("b","H5Tget_strpad","Import","Empty","((+8)+152)").
abi_typelocation("b","H5Tget_strpad","Import","Empty","((+8)+160)").
abi_typelocation("b","H5Tget_strpad","Import","Opaque","((+8)+168)").
abi_typelocation("b","H5Tget_strpad","Import","Void","((+8)+176)").
abi_typelocation("b","H5Tget_strpad","Import","Integer64","(+8)+184").
abi_typelocation("b","H5Tget_strpad","Import","Integer32","(+8)+192").
abi_typelocation("b","H5Tget_strpad","Import","Array[20:20]","(+8)+196").
abi_typelocation("b","H5Tget_strpad","Import","Integer8","(+8)+196").
abi_typelocation("b","H5SL_insert","Import","Integer64","%rdi").
abi_typelocation("b","H5SL_search","Export","Integer64","%rax").
abi_typelocation("b","H5Eset_auto2","Import","Integer32","(%rdi)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","((%rdi)+8)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","((%rdi)+16)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","((%rdi)+24)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","((%rdi)+32)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","((%rdi)+40)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","((%rdi)+48)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","((%rdi)+56)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","((%rdi)+64)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","((%rdi)+72)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","((%rdi)+80)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","((%rdi)+88)").
abi_typelocation("b","H5Eset_auto2","Import","Empty","((%rdi)+96)").
abi_typelocation("b","H5Eset_auto2","Import","Integer32","((%rdi)+104)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","(((%rdi)+104)+8)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","(((%rdi)+104)+16)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","(((%rdi)+104)+24)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","(((%rdi)+104)+32)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","(((%rdi)+104)+40)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","(((%rdi)+104)+48)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","(((%rdi)+104)+56)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","(((%rdi)+104)+64)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","(((%rdi)+104)+72)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","(((%rdi)+104)+80)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","(((%rdi)+104)+88)").
abi_typelocation("b","H5Eset_auto2","Import","Empty","(((%rdi)+104)+96)").
abi_typelocation("b","H5Eset_auto2","Import","Opaque","(((%rdi)+104)+104)").
abi_typelocation("b","H5Eset_auto2","Import","Integer32","((%rdi)+104)+112").
abi_typelocation("b","H5Eset_auto2","Import","Integer32","((%rdi)+104)+116").
abi_typelocation("b","H5Eset_auto2","Import","Integer64","((%rdi)+104)+120").
abi_typelocation("b","H5Eset_auto2","Import","Integer16","((%rdi)+104)+128").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","((%rdi)+104)+130").
abi_typelocation("b","H5Eset_auto2","Import","Array[1:1]","((%rdi)+104)+131").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","((%rdi)+104)+131").
abi_typelocation("b","H5Eset_auto2","Import","Integer64","((%rdi)+104)+144").
abi_typelocation("b","H5Eset_auto2","Import","Empty","(((%rdi)+104)+152)").
abi_typelocation("b","H5Eset_auto2","Import","Empty","(((%rdi)+104)+160)").
abi_typelocation("b","H5Eset_auto2","Import","Opaque","(((%rdi)+104)+168)").
abi_typelocation("b","H5Eset_auto2","Import","Void","(((%rdi)+104)+176)").
abi_typelocation("b","H5Eset_auto2","Import","Integer64","((%rdi)+104)+184").
abi_typelocation("b","H5Eset_auto2","Import","Integer32","((%rdi)+104)+192").
abi_typelocation("b","H5Eset_auto2","Import","Array[20:20]","((%rdi)+104)+196").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","((%rdi)+104)+196").
abi_typelocation("b","H5Eset_auto2","Import","Integer32","(%rdi)+112").
abi_typelocation("b","H5Eset_auto2","Import","Integer32","(%rdi)+116").
abi_typelocation("b","H5Eset_auto2","Import","Integer64","(%rdi)+120").
abi_typelocation("b","H5Eset_auto2","Import","Integer16","(%rdi)+128").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","(%rdi)+130").
abi_typelocation("b","H5Eset_auto2","Import","Array[1:1]","(%rdi)+131").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","(%rdi)+131").
abi_typelocation("b","H5Eset_auto2","Import","Integer64","(%rdi)+144").
abi_typelocation("b","H5Eset_auto2","Import","Empty","((%rdi)+152)").
abi_typelocation("b","H5Eset_auto2","Import","Empty","((%rdi)+160)").
abi_typelocation("b","H5Eset_auto2","Import","Opaque","((%rdi)+168)").
abi_typelocation("b","H5Eset_auto2","Import","Void","((%rdi)+176)").
abi_typelocation("b","H5Eset_auto2","Import","Integer64","(%rdi)+184").
abi_typelocation("b","H5Eset_auto2","Import","Integer32","(%rdi)+192").
abi_typelocation("b","H5Eset_auto2","Import","Array[20:20]","(%rdi)+196").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","(%rdi)+196").
abi_typelocation("b","H5Eset_auto2","Import","Integer32","((%rsi+8))").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","(((%rsi+8))+8)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","(((%rsi+8))+16)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","(((%rsi+8))+24)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","(((%rsi+8))+32)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","(((%rsi+8))+40)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","(((%rsi+8))+48)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","(((%rsi+8))+56)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","(((%rsi+8))+64)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","(((%rsi+8))+72)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","(((%rsi+8))+80)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","(((%rsi+8))+88)").
abi_typelocation("b","H5Eset_auto2","Import","Empty","(((%rsi+8))+96)").
abi_typelocation("b","H5Eset_auto2","Import","Integer32","(((%rsi+8))+104)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","((((%rsi+8))+104)+8)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","((((%rsi+8))+104)+16)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","((((%rsi+8))+104)+24)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","((((%rsi+8))+104)+32)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","((((%rsi+8))+104)+40)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","((((%rsi+8))+104)+48)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","((((%rsi+8))+104)+56)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","((((%rsi+8))+104)+64)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","((((%rsi+8))+104)+72)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","((((%rsi+8))+104)+80)").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","((((%rsi+8))+104)+88)").
abi_typelocation("b","H5Eset_auto2","Import","Empty","((((%rsi+8))+104)+96)").
abi_typelocation("b","H5Eset_auto2","Import","Opaque","((((%rsi+8))+104)+104)").
abi_typelocation("b","H5Eset_auto2","Import","Integer32","(((%rsi+8))+104)+112").
abi_typelocation("b","H5Eset_auto2","Import","Integer32","(((%rsi+8))+104)+116").
abi_typelocation("b","H5Eset_auto2","Import","Integer64","(((%rsi+8))+104)+120").
abi_typelocation("b","H5Eset_auto2","Import","Integer16","(((%rsi+8))+104)+128").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","(((%rsi+8))+104)+130").
abi_typelocation("b","H5Eset_auto2","Import","Array[1:1]","(((%rsi+8))+104)+131").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","(((%rsi+8))+104)+131").
abi_typelocation("b","H5Eset_auto2","Import","Integer64","(((%rsi+8))+104)+144").
abi_typelocation("b","H5Eset_auto2","Import","Empty","((((%rsi+8))+104)+152)").
abi_typelocation("b","H5Eset_auto2","Import","Empty","((((%rsi+8))+104)+160)").
abi_typelocation("b","H5Eset_auto2","Import","Opaque","((((%rsi+8))+104)+168)").
abi_typelocation("b","H5Eset_auto2","Import","Void","((((%rsi+8))+104)+176)").
abi_typelocation("b","H5Eset_auto2","Import","Integer64","(((%rsi+8))+104)+184").
abi_typelocation("b","H5Eset_auto2","Import","Integer32","(((%rsi+8))+104)+192").
abi_typelocation("b","H5Eset_auto2","Import","Array[20:20]","(((%rsi+8))+104)+196").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","(((%rsi+8))+104)+196").
abi_typelocation("b","H5Eset_auto2","Import","Integer32","((%rsi+8))+112").
abi_typelocation("b","H5Eset_auto2","Import","Integer32","((%rsi+8))+116").
abi_typelocation("b","H5Eset_auto2","Import","Integer64","((%rsi+8))+120").
abi_typelocation("b","H5Eset_auto2","Import","Integer16","((%rsi+8))+128").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","((%rsi+8))+130").
abi_typelocation("b","H5Eset_auto2","Import","Array[1:1]","((%rsi+8))+131").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","((%rsi+8))+131").
abi_typelocation("b","H5Eset_auto2","Import","Integer64","((%rsi+8))+144").
abi_typelocation("b","H5Eset_auto2","Import","Empty","(((%rsi+8))+152)").
abi_typelocation("b","H5Eset_auto2","Import","Empty","(((%rsi+8))+160)").
abi_typelocation("b","H5Eset_auto2","Import","Opaque","(((%rsi+8))+168)").
abi_typelocation("b","H5Eset_auto2","Import","Void","(((%rsi+8))+176)").
abi_typelocation("b","H5Eset_auto2","Import","Integer64","((%rsi+8))+184").
abi_typelocation("b","H5Eset_auto2","Import","Integer32","((%rsi+8))+192").
abi_typelocation("b","H5Eset_auto2","Import","Array[20:20]","((%rsi+8))+196").
abi_typelocation("b","H5Eset_auto2","Import","Integer8","((%rsi+8))+196").
abi_typelocation("b","H5Eset_auto2","Import","Opaque","((%rsi+8)+8)").
abi_typelocation("b","H5SL_create","Both","Void","((%rdi))").

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-11.2.0/openmpi-4.1.4-axm3au7q4x7g5kxocoyoq4tkxobmyio4/lib/libmpi.so.40.30.4
%----------------------------------------------------------------------------
