
%============================================================================
% Library Facts
%============================================================================

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-11.2.0/hdf5-1.8.14-l3awvrdruqoyzvffma5bak2fetomzfqq/lib/libhdf5.so.1.8.14
%----------------------------------------------------------------------------
abi_typelocation("a","MPI_Bcast","Both","Void","(%rdi)").
abi_typelocation("a","MPI_Barrier","Both","Void","(%rdi)").
abi_typelocation("a","MPI_Type_free","Export","Integer16","%rax").
abi_typelocation("a","MPI_Barrier","Export","Integer16","%rax").
abi_typelocation("a","MPI_Type_commit","Export","Integer16","%rax").
abi_typelocation("a","MPI_Type_create_hvector","Import","Integer16","%rdi").
abi_typelocation("a","MPI_Type_create_hvector","Import","Integer16","%rsi").
abi_typelocation("a","MPI_Type_create_hvector","Export","Integer16","%rax").
abi_typelocation("a","MPI_Type_create_hindexed","Import","Integer16","%rdi").
abi_typelocation("a","MPI_Type_create_hindexed","Export","Integer16","%rax").
abi_typelocation("a","MPI_Error_string","Import","Integer16","%rdi").
abi_typelocation("a","MPI_Error_string","Export","Integer16","%rax").
abi_typelocation("a","MPI_Type_contiguous","Import","Integer16","%rdi").
abi_typelocation("a","MPI_Type_contiguous","Export","Integer16","%rax").
abi_typelocation("a","MPI_Gather","Import","Array[288:18]","None").
abi_typelocation("a","MPI_Gather","Import","Integer8","()").
abi_typelocation("a","MPI_Gather","Import","Integer32","(+8)").
abi_typelocation("a","MPI_Gather","Import","Integer8","((+8)+8)").
abi_typelocation("a","MPI_Gather","Import","Integer8","((+8)+16)").
abi_typelocation("a","MPI_Gather","Import","Integer8","((+8)+24)").
abi_typelocation("a","MPI_Gather","Import","Integer8","((+8)+32)").
abi_typelocation("a","MPI_Gather","Import","Integer8","((+8)+40)").
abi_typelocation("a","MPI_Gather","Import","Integer8","((+8)+48)").
abi_typelocation("a","MPI_Gather","Import","Integer8","((+8)+56)").
abi_typelocation("a","MPI_Gather","Import","Integer8","((+8)+64)").
abi_typelocation("a","MPI_Gather","Import","Integer8","((+8)+72)").
abi_typelocation("a","MPI_Gather","Import","Integer8","((+8)+80)").
abi_typelocation("a","MPI_Gather","Import","Integer8","((+8)+88)").
abi_typelocation("a","MPI_Gather","Import","Empty","((+8)+96)").
abi_typelocation("a","MPI_Gather","Import","Integer32","((+8)+104)").
abi_typelocation("a","MPI_Gather","Import","Integer8","(((+8)+104)+8)").
abi_typelocation("a","MPI_Gather","Import","Integer8","(((+8)+104)+16)").
abi_typelocation("a","MPI_Gather","Import","Integer8","(((+8)+104)+24)").
abi_typelocation("a","MPI_Gather","Import","Integer8","(((+8)+104)+32)").
abi_typelocation("a","MPI_Gather","Import","Integer8","(((+8)+104)+40)").
abi_typelocation("a","MPI_Gather","Import","Integer8","(((+8)+104)+48)").
abi_typelocation("a","MPI_Gather","Import","Integer8","(((+8)+104)+56)").
abi_typelocation("a","MPI_Gather","Import","Integer8","(((+8)+104)+64)").
abi_typelocation("a","MPI_Gather","Import","Integer8","(((+8)+104)+72)").
abi_typelocation("a","MPI_Gather","Import","Integer8","(((+8)+104)+80)").
abi_typelocation("a","MPI_Gather","Import","Integer8","(((+8)+104)+88)").
abi_typelocation("a","MPI_Gather","Import","Empty","(((+8)+104)+96)").
abi_typelocation("a","MPI_Gather","Import","Opaque","(((+8)+104)+104)").
abi_typelocation("a","MPI_Gather","Import","Integer32","((+8)+104)+112").
abi_typelocation("a","MPI_Gather","Import","Integer32","((+8)+104)+116").
abi_typelocation("a","MPI_Gather","Import","Integer64","((+8)+104)+120").
abi_typelocation("a","MPI_Gather","Import","Integer16","((+8)+104)+128").
abi_typelocation("a","MPI_Gather","Import","Integer8","((+8)+104)+130").
abi_typelocation("a","MPI_Gather","Import","Array[1:1]","((+8)+104)+131").
abi_typelocation("a","MPI_Gather","Import","Integer8","((+8)+104)+131").
abi_typelocation("a","MPI_Gather","Import","Integer64","((+8)+104)+144").
abi_typelocation("a","MPI_Gather","Import","Empty","(((+8)+104)+152)").
abi_typelocation("a","MPI_Gather","Import","Empty","(((+8)+104)+160)").
abi_typelocation("a","MPI_Gather","Import","Opaque","(((+8)+104)+168)").
abi_typelocation("a","MPI_Gather","Import","Void","(((+8)+104)+176)").
abi_typelocation("a","MPI_Gather","Import","Integer64","((+8)+104)+184").
abi_typelocation("a","MPI_Gather","Import","Integer32","((+8)+104)+192").
abi_typelocation("a","MPI_Gather","Import","Array[20:20]","((+8)+104)+196").
abi_typelocation("a","MPI_Gather","Import","Integer8","((+8)+104)+196").
abi_typelocation("a","MPI_Gather","Import","Integer32","(+8)+112").
abi_typelocation("a","MPI_Gather","Import","Integer32","(+8)+116").
abi_typelocation("a","MPI_Gather","Import","Integer64","(+8)+120").
abi_typelocation("a","MPI_Gather","Import","Integer16","(+8)+128").
abi_typelocation("a","MPI_Gather","Import","Integer8","(+8)+130").
abi_typelocation("a","MPI_Gather","Import","Array[1:1]","(+8)+131").
abi_typelocation("a","MPI_Gather","Import","Integer8","(+8)+131").
abi_typelocation("a","MPI_Gather","Import","Integer64","(+8)+144").
abi_typelocation("a","MPI_Gather","Import","Empty","((+8)+152)").
abi_typelocation("a","MPI_Gather","Import","Empty","((+8)+160)").
abi_typelocation("a","MPI_Gather","Import","Opaque","((+8)+168)").
abi_typelocation("a","MPI_Gather","Import","Void","((+8)+176)").
abi_typelocation("a","MPI_Gather","Import","Integer64","(+8)+184").
abi_typelocation("a","MPI_Gather","Import","Integer32","(+8)+192").
abi_typelocation("a","MPI_Gather","Import","Array[20:20]","(+8)+196").
abi_typelocation("a","MPI_Gather","Import","Integer8","(+8)+196").
abi_typelocation("a","MPI_Allreduce","Import","Array[288:18]","None").
abi_typelocation("a","MPI_Allreduce","Import","Integer8","()").
abi_typelocation("a","MPI_Allreduce","Import","Integer32","(+8)").
abi_typelocation("a","MPI_Allreduce","Import","Integer8","((+8)+8)").
abi_typelocation("a","MPI_Allreduce","Import","Integer8","((+8)+16)").
abi_typelocation("a","MPI_Allreduce","Import","Integer8","((+8)+24)").
abi_typelocation("a","MPI_Allreduce","Import","Integer8","((+8)+32)").
abi_typelocation("a","MPI_Allreduce","Import","Integer8","((+8)+40)").
abi_typelocation("a","MPI_Allreduce","Import","Integer8","((+8)+48)").
abi_typelocation("a","MPI_Allreduce","Import","Integer8","((+8)+56)").
abi_typelocation("a","MPI_Allreduce","Import","Integer8","((+8)+64)").
abi_typelocation("a","MPI_Allreduce","Import","Integer8","((+8)+72)").
abi_typelocation("a","MPI_Allreduce","Import","Integer8","((+8)+80)").
abi_typelocation("a","MPI_Allreduce","Import","Integer8","((+8)+88)").
abi_typelocation("a","MPI_Allreduce","Import","Empty","((+8)+96)").
abi_typelocation("a","MPI_Allreduce","Import","Integer32","((+8)+104)").
abi_typelocation("a","MPI_Allreduce","Import","Integer8","(((+8)+104)+8)").
abi_typelocation("a","MPI_Allreduce","Import","Integer8","(((+8)+104)+16)").
abi_typelocation("a","MPI_Allreduce","Import","Integer8","(((+8)+104)+24)").
abi_typelocation("a","MPI_Allreduce","Import","Integer8","(((+8)+104)+32)").
abi_typelocation("a","MPI_Allreduce","Import","Integer8","(((+8)+104)+40)").
abi_typelocation("a","MPI_Allreduce","Import","Integer8","(((+8)+104)+48)").
abi_typelocation("a","MPI_Allreduce","Import","Integer8","(((+8)+104)+56)").
abi_typelocation("a","MPI_Allreduce","Import","Integer8","(((+8)+104)+64)").
abi_typelocation("a","MPI_Allreduce","Import","Integer8","(((+8)+104)+72)").
abi_typelocation("a","MPI_Allreduce","Import","Integer8","(((+8)+104)+80)").
abi_typelocation("a","MPI_Allreduce","Import","Integer8","(((+8)+104)+88)").
abi_typelocation("a","MPI_Allreduce","Import","Empty","(((+8)+104)+96)").
abi_typelocation("a","MPI_Allreduce","Import","Opaque","(((+8)+104)+104)").
abi_typelocation("a","MPI_Allreduce","Import","Integer32","((+8)+104)+112").
abi_typelocation("a","MPI_Allreduce","Import","Integer32","((+8)+104)+116").
abi_typelocation("a","MPI_Allreduce","Import","Integer64","((+8)+104)+120").
abi_typelocation("a","MPI_Allreduce","Import","Integer16","((+8)+104)+128").
abi_typelocation("a","MPI_Allreduce","Import","Integer8","((+8)+104)+130").
abi_typelocation("a","MPI_Allreduce","Import","Array[1:1]","((+8)+104)+131").
abi_typelocation("a","MPI_Allreduce","Import","Integer8","((+8)+104)+131").
abi_typelocation("a","MPI_Allreduce","Import","Integer64","((+8)+104)+144").
abi_typelocation("a","MPI_Allreduce","Import","Empty","(((+8)+104)+152)").
abi_typelocation("a","MPI_Allreduce","Import","Empty","(((+8)+104)+160)").
abi_typelocation("a","MPI_Allreduce","Import","Opaque","(((+8)+104)+168)").
abi_typelocation("a","MPI_Allreduce","Import","Void","(((+8)+104)+176)").
abi_typelocation("a","MPI_Allreduce","Import","Integer64","((+8)+104)+184").
abi_typelocation("a","MPI_Allreduce","Import","Integer32","((+8)+104)+192").
abi_typelocation("a","MPI_Allreduce","Import","Array[20:20]","((+8)+104)+196").
abi_typelocation("a","MPI_Allreduce","Import","Integer8","((+8)+104)+196").
abi_typelocation("a","MPI_Allreduce","Import","Integer32","(+8)+112").
abi_typelocation("a","MPI_Allreduce","Import","Integer32","(+8)+116").
abi_typelocation("a","MPI_Allreduce","Import","Integer64","(+8)+120").
abi_typelocation("a","MPI_Allreduce","Import","Integer16","(+8)+128").
abi_typelocation("a","MPI_Allreduce","Import","Integer8","(+8)+130").
abi_typelocation("a","MPI_Allreduce","Import","Array[1:1]","(+8)+131").
abi_typelocation("a","MPI_Allreduce","Import","Integer8","(+8)+131").
abi_typelocation("a","MPI_Allreduce","Import","Integer64","(+8)+144").
abi_typelocation("a","MPI_Allreduce","Import","Empty","((+8)+152)").
abi_typelocation("a","MPI_Allreduce","Import","Empty","((+8)+160)").
abi_typelocation("a","MPI_Allreduce","Import","Opaque","((+8)+168)").
abi_typelocation("a","MPI_Allreduce","Import","Void","((+8)+176)").
abi_typelocation("a","MPI_Allreduce","Import","Integer64","(+8)+184").
abi_typelocation("a","MPI_Allreduce","Import","Integer32","(+8)+192").
abi_typelocation("a","MPI_Allreduce","Import","Array[20:20]","(+8)+196").
abi_typelocation("a","MPI_Allreduce","Import","Integer8","(+8)+196").
abi_typelocation("a","MPI_Info_free","Export","Integer32","%rax").
abi_typelocation("a","MPI_Comm_free","Export","Integer32","%rax").
abi_typelocation("a","MPI_Info_dup","Export","Integer32","%rax").
abi_typelocation("a","MPI_Error_string","Import","Integer32","%rdi").
abi_typelocation("a","MPI_Error_string","Both","Integer8","(%rsi)").
abi_typelocation("a","MPI_Error_string","Export","Integer32","%rax").
abi_typelocation("a","MPI_Comm_dup","Export","Integer32","%rax").
abi_typelocation("a","MPI_File_open","Import","Integer8","()").
abi_typelocation("a","MPI_File_close","Import","Integer8","()").
abi_typelocation("a","MPI_Error_string","Import","Integer8","%rdi").
abi_typelocation("a","MPI_Error_string","Import","Integer64","%rdi").
abi_typelocation("a","compress2","Import","Array","%rdi").
abi_typelocation("a","compress2","Import","Integer8","%rdi").
abi_typelocation("a","compress2","Import","Integer32","%rdx").
abi_typelocation("a","compress2","Export","Integer32","%rax").
abi_typelocation("a","inflateEnd","Export","Integer32","%rax").
abi_typelocation("a","inflate","Import","Integer32","%rdi").
abi_typelocation("a","inflate","Export","Integer32","%rax").
abi_typelocation("a","inflateInit_","Import","Integer32","%rdi").
abi_typelocation("a","inflateInit_","Export","Integer32","%rax").

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-11.2.0/openmpi-4.1.4-hzocyocg5hkiwuxly4e6q4cgtakurmv4/lib/libmpi.so.40
%----------------------------------------------------------------------------

%----------------------------------------------------------------------------
% Library: /spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-11.2.0/zlib-1.2.12-luwgiwun44dt7hmxv4ki6xjnxyucze7f/lib/libz.so.1.2.12
%----------------------------------------------------------------------------
abi_typelocation("b","compress2","Import","Integer8","%rdi").
abi_typelocation("b","compress2","Import","Integer64","%rsi").
abi_typelocation("b","compress2","Export","Integer64","%rax").
abi_typelocation("b","inflateEnd","Export","Integer64","%rax").
abi_typelocation("b","inflate","Import","Integer64","%rdi").
abi_typelocation("b","inflate","Export","Integer64","%rax").
abi_typelocation("b","inflateInit_","Import","Integer64","%rdi").
abi_typelocation("b","inflateInit_","Export","Integer64","%rax").
abi_typelocation("b","inflateEnd","Export","Integer8","%rax").
abi_typelocation("b","inflate","Import","Integer8","%rdi").
abi_typelocation("b","inflate","Export","Integer8","%rax").
